### ISSUE TITLE
ElasticClient.Get<T>(...) fails with Could not parse server exception when document doesn't exist

### ISSUE THREAD

**Issue by kohner86** [elastic/elasticsearch-net#1026]
When doing a get request on a document which doesn't exist (it was deleted) the call throws an exception of type 'Elasticsearch.Net.ElasticsearchServerException' with a message of 'Could not parse server exception' with the following stack trace:

at Nest.ElasticClient.<>c__DisplayClass261`4.b__260(Task`1 r) in c:\Users\gmarz\code\elasticsearch-net\src\Nest\ElasticClient.cs:line 145
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WorkerRoleService.InstagramV2.QueryActor.d__6b.MoveNext() in c:\Zoomph\Web\Azure\myStanlyWeb\Releases\Brontosaurus\myStanlySolution\WorkerRoleService\InstagramV2\QueryActor.cs:line 622

Is this expected behavior?  The IGetResponse<T> interface has a 'Found' property on it which I would expect to check to see if the get failed rather than the exception being thrown.

We're using NEST 1.1.1 with Elastic Search 1.3.4

-Lee

**Comment by HunterMcEwan** [comment]
Seems like Get (and Delete) were removed from the 404-is-valid list in 0992779bf9b4a30afb034ed737fc3f840d03f74a, was this intentional?
