### ISSUE TITLE
 An item with the same key has already been added

### ISSUE THREAD

**Issue by chetanra** [elastic/elasticsearch-net#1379]
I am trying to use dynamic to avoid defining types in my client code.  Any kind of simple query results in the exception, is dynamic supported?

var settings = new ConnectionSettings(new UriBuilder("https", "localhost, -1, "esapi/_all/_search").Uri);
            var client1 = new ElasticClient(settings, new HttpConnection(settings));
            var response = client1.Search<dynamic>(s => s.From(0).Size(10));

System.ArgumentException was unhandled
  HResult=-2147024809
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at System.Collections.ObjectModel.KeyedCollection`2.AddKey(TKey key, TItem item)
       at System.Collections.ObjectModel.KeyedCollection`2.InsertItem(Int32 index, TItem item)
       at System.Collections.ObjectModel.Collection`1.Add(T item)
       at Newtonsoft.Json.Utilities.CollectionUtils.AddRange[T](IList`1 initial, IEnumerable`1 collection)
       at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
       at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
       at Nest.Resolvers.ElasticContractResolver.CreateContract(Type objectType) in C:\code\elasticsearch-net\src\Nest\Resolvers\ElasticContractResolver.cs:line 29
       at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
       at Nest.Resolvers.SettingsContractResolver.ResolveContract(Type type) in C:\code\elasticsearch-net\src\Nest\Resolvers\SettingsContractResolver.cs:line 34
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(Object value)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
       at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
       at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
       at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
       at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, Formatting formatting, JsonSerializerSettings settings)
       at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
       at Nest.NestSerializer.Serialize(Object data, SerializationFormatting formatting) in C:\code\elasticsearch-net\src\Nest\ExposedInternals\NestSerializer.cs:line 30
       at Elasticsearch.Net.Connection.RequestHandlers.RequestHandlerBase.PostData(Object data) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\RequestHandlers\RequestHandlerBase.cs:line 63
       at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.Request[T](TransportRequestState`1 requestState, Object data) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\RequestHandlers\RequestHandler.cs:line 31
       at Elasticsearch.Net.Connection.Transport.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:line 343
       at Elasticsearch.Net.ElasticsearchClient.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters) in C:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticsearchClient.cs:line 65
       at Elasticsearch.Net.ElasticsearchClient.Search[T](String index, String type, Object body, Func`2 requestParameters) in C:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticsearchClient.Generated.cs:line 33515
       at Nest.RawDispatch.SearchDispatch[T](ElasticsearchPathInfo`1 pathInfo, Object body) in C:\code\elasticsearch-net\src\Nest\RawDispatch.generated.cs:line 3512
       at Nest.ElasticClient.Search[T,TResult](Func`2 searchSelector) in C:\code\elasticsearch-net\src\Nest\ElasticClient-Search.cs:line 32
       at Nest.ElasticClient.Search[T](Func`2 searchSelector) in C:\code\elasticsearch-net\src\Nest\ElasticClient-Search.cs:line 16
       at ConsoleApplication1.Program.Main(String[] args) in \\tkzaw-pro-19\mydocs1\My Documents\Visual Studio 2013\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs:line 28
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by chetanra** [comment]
Same is the issue with typed search.  I am using the latest version of NEST and elasticsearch.net.  Any idea what I am missing?

var response = client.Search<Person>(s => s.Index("blah").Type("blah1").Size(10));

**Comment by chetanra** [comment]
same error with Object Initializer Syntax also.

            QueryContainer query = new TermQuery
            {
                Field = "Id",
                Value = "123"
            };

            var searchRequest = new SearchRequest
            {
                From = 0,
                Size = 10,
                Query = query
            };


            var response = client1.Search<Person>(searchRequest);

**Comment by chetanra** [comment]
This happened due to latest version of NEST along with latest version of Json.NET pre-release.  When I moved to following, it just worked.

  <package id="Elasticsearch.Net" version="1.3.1" targetFramework="net45" />
    <package id="NEST" version="1.3.1" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="6.0.1" targetFramework="net45" />

**Comment by chetanra** [comment]
Elasticsearch.Net" version="1.3.1" targetFramework="net45" 
NEST" version="1.3.1" targetFramework="net45" 
Newtonsoft.Json" version="6.0.1" targetFramework="net45"
