### ISSUE TITLE
NEST Count API throws exceptions when default index is not defined

### ISSUE THREAD

**Issue by krisze** [elastic/elasticsearch-net#1404]
Version 1.0.0 beta, 1.4.2
When a default index is not defined upon client creation, even if the index name is defined in the request for Count API, it will throws a `No default index defined` exception.
When I tried to upgrade to 1.4.2, it will throw the an error saying 
`Elastic Nest violates the constraint of type parameter "P"`.

**Comment by gmarz** [comment]
Hey @krisze I'm having trouble reproducing this.  Could you provide an example?

**Comment by krisze** [comment]
Hi @gmarz, I'm tried on both 1.0.0 and 1.4.2:

If no default index was given:
```c#
    var settings = new ConnectionSettings(uri);
     container.Register(
                Component.For<IElasticClient>()
                    .ImplementedBy<ElasticClient>()
                    .DependsOn(new { settings = settings })
                    .LifestyleScoped()
    );
```
then try getting count by running the following query:
````c#

    var response = client.Count<objectName>(count => count
                .Index(indexName)
                .Type(typeName)
                .Query(q => q
                    .Match(m => m
                        .OnField(f => f.id)
                        .Query(id))));
```
for 1.0.0 (beta) the following error occured:
```xml
  
    <Error>
    <Message>An error has occurred.</Message>
        <ExceptionMessage>No default index set on connection!</ExceptionMessage>
        <ExceptionType>System.NullReferenceException</ExceptionType>
        <StackTrace>
    at System.Web.Http.ApiController.<InvokeActionWithExceptionFilters>d__1.MoveNext() --- End of     stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__0.MoveNext()
        </StackTrace>
    </Error>`
```
for 1.4.2 the following error occurred, and if you debug into it, you will see the no index error in the client object at runtime as well:

```xml

    <Error>
     <Message>An error has occurred.</Message>
     <ExceptionMessage>
     GenericArguments[0],   'Nest.CountDescriptor`1[Workopolis.CandidateSourcing.ElasticSearchAdapters.ElasticSearchApplicant]', on 'Nest.QueryPathDescriptorBase`3[P,T,K]' violates the constraint of type parameter 'P'.
     </ExceptionMessage>
    <ExceptionType>System.TypeLoadException</ExceptionType>
    <StackTrace>
at System.Web.Http.ApiController.<InvokeActionWithExceptionFilters>d__1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__0.MoveNext()
     </StackTrace>
    </Error>
```

**Comment by gmarz** [comment]
@krisze thanks for the example, but unfortunately I'm still not able to reproduce the problem.

The `TypeLoadException` makes me think there's something fudged up on your end.  Can you you clear your bin folder, rebuild all your assemblies and make sure there isn't an old NEST reference hanging around somewhere?

Also, see http://stackoverflow.com/questions/6809457/why-am-i-getting-a-generic-constraint-violation-at-runtime

**Comment by gmarz** [comment]
@krisze any news on this?

**Comment by krisze** [comment]
Well this was resolved when I added the default index name when I created the client in the installer (please see the first response for details), but I shouldn't need to do that because on query level, I am defining the index.

**Comment by Mpdreamz** [comment]
Tried to reproduce this [here](https://github.com/elastic/elasticsearch-net/commit/23ef718c30136e48394bf27c218f6fd8bebdb607) to no avail. This should not happen in later versions of NEST.
