### ISSUE TITLE
Unexpected token when deserializing object

### ISSUE THREAD

**Issue by ksujeet** [elastic/elasticsearch-net#1515]
Error: {"Unexpected token when deserializing object: Integer. Path 'aggregations.location.doc_count_error_upper_bound', line 1, position 185."}

StackTrace: 
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Nest.NestSerializer.DeserializeUsingSettings[T](Stream stream, JsonSerializerSettings settings)
   at Nest.NestSerializer.Deserialize[T](Stream stream)
   at Nest.NestSerializer.DeserializeInternal[T](Stream stream, JsonConverter converter)
   at Nest.ElasticClient.FieldsSearchDeserializer[T,TResult](IElasticsearchResponse response, Stream stream, ISearchRequest d)
   at Nest.ElasticClient.<>c__DisplayClass1f9`2.<CreateSearchDeserializer>b__1f8(IElasticsearchResponse r, Stream s)
   at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.StreamToTypedResponse[T](ElasticsearchResponse`1 streamResponse, ITransportRequestState requestState, Byte[] readBytes)
   at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.ReturnTypedResponse[T](TransportRequestState`1 requestState, ElasticsearchResponse`1 streamResponse, ElasticsearchServerError& error)
   at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.CoordinateRequest[T](TransportRequestState`1 requestState, Int32 maxRetries, Int32 retried, Boolean& aliveResponse)
   at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.DoRequest[T](TransportRequestState`1 requestState)
   at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.Request[T](TransportRequestState`1 requestState, Object data)
   at Elasticsearch.Net.Connection.Transport.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticsearchClient.Search[T](Object body, Func`2 requestParameters)
   at Nest.ElasticClient.Search[T,TResult](Func`2 searchSelector)
   at THF.CMS.Api.SearchManager.GetSearchResults(SearchRequest input) in c:\inetpub\wwwroot\THF\THF.CMS.Prod\Api\SearchManager.cs:line 62

NEST Query:
var agg = esclient.Search<Artifact>(s => s.Aggregations(ag => ag
                .Nested("refineSearch", fi => fi.Path("refineSearch")).Filter("filtered", f => f
                    .Filter(fl =>
                        fl.Terms("multimediaReferenceList.mimeType", input.Filters.Media) ||
                        fl.Terms("physicalLocations.level1", input.Filters.Location) ||
                        fl.Terms("objectCategory", input.Filters.Type) ||
                        fl.Range(r => r.GreaterOrEquals(input.Years[0]).OnField(of => of.MinYear)) ||
                        fl.Range(ra => ra.LowerOrEquals(input.Years[1]).OnField(od => od.MaxYear)))))
                        .Aggregations(aa => aa
                            .Terms("type", tr => tr.Field("objectCategory").Size(10))
                            .Terms("media", trm => trm.Field("multimediaReferenceList.mimeType").Size(10))
                            .Terms("location", trms => trms.Field("physicalLocations.level1").Size(10)))
                            .SearchType(SearchType.Count));

Query DSL:
"aggs": {
    "refineSearch": {
      "filter": {
        "bool": {
          "should": [
            {
              "terms": {
                "multimediaReferenceList.mimeType": [
                  "image",
                  "audio",
                  "video",
                  "application"
                ]
              }
            },
            {
              "terms": {
                "physicalLocations.level1": [
                  "henry",
                  "benson"
                ]
              }
            },
            {
              "terms": {
                "objectCategory": [
                  "objects",
                  "documents"
                ]
              }
            },
            {
              "range": {
                "minYear": {
                  "gte": 1880
                  
                }
              }
            },
            {
              "range": {
                "maxYear": {
                  "lte": 1985
                  
                }
              }
            }
          ]
        }
      },
      "aggs": {
        "media": {
          "terms": {
            "field": "multimediaReferenceList.mimeType",
            "size": 10
          }
        },
        "location":{
          "terms": {
            "field": "physicalLocations.level1",
            "size": 10
          }
        },
        "type":{
          "terms": {
            "field": "objectCategory",
            "size": 10
          }
        }
      }
    } 
  }

I am trying to get this query to work but I always keep getting this exception. I am currently unable to debug further.  Please help me, I already wasted a lot of time on this.

**Comment by gmarz** [comment]
I've closed #1513 in favor of this, which looks to be the same thing.  Let's continue here and keep only one issue open, please.

I'm having a hard time trying to reproduce this, but also spotted a few issues with your examples above:

[1] The NEST snippet above is using a nested aggregation, whereas the query DSL example is not.

[2] The nested aggregation is being composed incorrectly, it should be:

```csharp
esclient.Search(s => s
  .Aggregations(ag => ag
    .Nested("refineSearch", fi => fi
      .Path("refineSearch")
      .Aggregations(aag => aag
        .Filter("filtered", f => f
          ...
        )
    )
```

as opposed to

```csharp
esclient.Search(s => s
  .Aggregations(ag => ag
    .Nested("refineSearch", fi => fi
      .Path("refineSearch")
    )
    .Filter("filtered", f => f
        ...
    )

```

**Comment by ksujeet** [comment]
Thank you for the input, I correct the query, But still getting the same exception, I am sorry I am novice to NEST

var agg = esclient.Search<Artifact>(s => s.Aggregations(ag => ag
                .Filter("filtered", f => f
                    .Filter(fl =>
                        fl.Terms("multimediaReferenceList.mimeType", input.Filters.Media) ||
                        fl.Terms("physicalLocations.level1", input.Filters.Location) ||
                        fl.Terms("objectCategory", input.Filters.Type) ||
                        fl.Range(r => r.GreaterOrEquals(input.Years[0]).OnField(of => of.MinYear)) ||
                        fl.Range(ra => ra.LowerOrEquals(input.Years[1]).OnField(od => od.MaxYear)))))
                        .Aggregations(aa => aa
                            .Terms("type", tr => tr.Field("objectCategory").Size(10))
                            .Terms("media", trm => trm.Field("multimediaReferenceList.mimeType").Size(10))
                            .Terms("location", trms => trms.Field("physicalLocations.level1").Size(10)))
                            .SearchType(SearchType.Count));

**Comment by ksujeet** [comment]
An exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in THF.CMS.dll but was not handled in user code

Additional information: Unexpected token when deserializing object: Integer. Path 'aggregations.names.doc_count_error_upper_bound', line 1629, position 62.

Nest Code: 
 var exp = esclient.Search<Artifact>(s => s.Aggregations(
                    ag =>
                        ag.Terms("names",
                            st =>
                                st.Field("objectCategory")
                                    .Size(10)
                                    .Aggregations(aa => aa.Terms("type", t => t.Field(f => f.ObjectCategory))))));

This nest code is the sample nest code from the NEST website but I still get the same exception

**Comment by ksujeet** [comment]
Anybody? looking at the issues. If you could please look at this issue. 

Thanks in advance

**Comment by gmarz** [comment]
@ksujeet I'm still having trouble reproducing this.  I've added the [above test](https://github.com/elastic/elasticsearch-net/commit/d9461d24d250523ec4a459fa9173c21bce4fbb92) and it passes, mind taking a look?  I've tested against ES 1.6.

Can you confirm the version of NEST and Elasticsearch you're running?  This was a bug that was fixed in our 1.2.2 [release](https://github.com/elastic/elasticsearch-net/releases/tag/1.2.2).  See #1025.

**Comment by ksujeet** [comment]
@gmarz 
Yeah, thats why I tried using the sample code from NEST and instead of avg I used terms. What I see is that it only happens when the query returns a JSON and when NEST tries to deserialize it. 
 
<package id="NEST" version="1.7.0" targetFramework="net40" />
  <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net40" />
 <package id="Elasticsearch.Net" version="1.7.0" targetFramework="net40" />
Elastic 1.6

**Comment by gmarz** [comment]
What version of NEST?

**Comment by ksujeet** [comment]
1.7

**Comment by ksujeet** [comment]
I downloaded that from the Package Manager in Visual Studio

**Comment by ksujeet** [comment]
I saw your ticket and checkin regarding the DocCountErrorUpperBound and I see that you have declared that as a long and I am getting an exception that NewtonSoft is trying to parse that as an integer. 
Unexpected token while deserializing object:Integer Path "aggregations.type.doc_count_error_upper_bound"

**Comment by gmarz** [comment]
That should be okay.

This sounds oddly like #1025 which was already fixed.  Is this happening locally in VS, or on a server where your application is deployed and running?

If locally, for good measure, can you uninstall and reinstall NEST 1.7 from the package manager?  I wan't to make sure you're not somehow on a version < 1.2.2.

If on a server, can you ensure the correct version of NEST is deployed?

**Comment by ksujeet** [comment]
That worked. Thank you very much.
