### ISSUE TITLE
Cannot create an instance of Nest.CatResponse`1

### ISSUE THREAD

**Issue by asafc64** [elastic/elasticsearch-net#1649]
I have this weird behavior when I recovering a snapshot, and trying to get its status by calling `CatRecovery`. 
Most the time, it works. But sometime I get this error:

```
System.AggregateException: One or more errors occurred. ---> System.Exception: Cannot create an instance of Nest.CatResponse`1[[Nest.CatRecoveryRecord, Nest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d]]because it has no constructor taking 0 arguments
   at Nest.TypeExtensions.CreateInstance(Type t, Object[] args)
   at Nest.ElasticClient.CreateInvalidInstance[R](IElasticsearchResponse response)
   at Nest.ElasticClient.ResultsSelector[D,Q,R](ElasticsearchResponse`1 c, D descriptor)
   at Nest.ElasticClient.Dispatch[D,Q,R](D descriptor, Func`3 dispatch)
   at Nest.ElasticClient.DoCat[TRequest,TParams,TCatRecord](Func`2 selector, Func`2 dispatch)
```

Can you tell what might be problem? if not, how can I get you more information?

**Comment by Mpdreamz** [comment]
CatRecord used to have a constructor that took a response which broke cat responses. This should be fixed since `1.5.1`
