### ISSUE TITLE
Documentation is badly out of date

### ISSUE THREAD

**Issue by mgrigajtis** [elastic/elasticsearch-net#1735]
I'd like to use this nuget package, but I can't figure out how to get anything into ElasticSearch using it.  For example, the documentation only shows one parameter going into the Index function, however, there is no overload of Index that takes only one parameter.

**Comment by russcam** [comment]
@mgrigajtis Which version of NEST are you using? 

[There is documentation for NEST 1.x](http://nest.azurewebsites.net/nest/quick-start.html) but it is out of date in places. If you come across issues, please feel free to raise; PRs are also most welcome :smile: 

The `Index()` method in NEST 1.x has the following overloads

```c#
public partial class ElasticClient : IElasticClient
{
	public IIndexResponse Index<T>(T @object, Func<IndexDescriptor<T>, IndexDescriptor<T>> indexSelector = null)
		where T : class
	{
		// ... 
	}

	public IIndexResponse Index<T>(IIndexRequest<T> indexRequest)
		where T : class
	{
		// ...
	}

	public Task<IIndexResponse> IndexAsync<T>(T @object, Func<IndexDescriptor<T>, IndexDescriptor<T>> indexSelector = null)
		where T : class
	{
		// ...
	}

	public Task<IIndexResponse> IndexAsync<T>(IIndexRequest<T> indexRequest)
		where T : class
	{
		// ...
	}
}
```

the method can take the object `T` to index and an optional delegate to additional describe the index operation, or take an index request object. There are also async versions of both methods. You can find examples of doing bulk indexing on [stackoverflow](http://stackoverflow.com/questions/34736586/elasticsearch-bulk-indexing) and on [blog posts](http://forloop.co.uk/blog/geospatial-search-with-elasticsearch-and-nest); if you're indexing many documents, you're very likely to want to use the bulk api to do this.

We are working on [documentation for NEST 2.x](https://github.com/elastic/elasticsearch-net/tree/master/docs/asciidoc) which is generated from literal tests to assert that it aligns with any changes that are made to source.

**Comment by mgrigajtis** [comment]
Strange, it's the default package that Nuget installs into a DotNet project, version 1.7.1.  Unless I'm missing something really obvious, the package seems broken since it can't write to ElasticSearch.

**Comment by jonyadamit** [comment]
@mgrigajtis if you could post an example of what you're trying to do, or what error message you receive, I'll gladly try to help.

**Comment by mgrigajtis** [comment]
Sure thing, here' the code snipet in my application:
```
private static void WriteInfoToElasticSearch(string currentDateTime, string logWriterName, string message)
        {
            var node = new Uri("http://10.40.50.146:9200");
            var config = new ConnectionConfiguration(node);
            var client = new ElasticsearchClient(config);

            var lo = new LogObject();
            lo.logWriter = logWriterName;
            lo.message = message;
            lo.timestamp = currentDateTime.ToString();

            try
            {
                var response = client.Index(logWriterName, "SentMessage", new JavaScriptSerializer().Serialize(lo), null);
            }
            catch (Exception ex)
            {
                WriteErrorToTextFile(currentDateTime, logWriterName, " problem sending to Elastic Search ", logWriterName + "Error.log", ex);
            }
        }
```

The LogObject that I am instantiating only has the three properties that I am initializing above.  Here is the error that I get from this result.

```
1/19/2016 9:31:47 AM MessageReaderWriter ERROR  problem sending to Elastic Search  System.NullReferenceException: Object reference not set to an instance of an object.
   at Elasticsearch.Net.Serialization.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
   at Elasticsearch.Net.Serialization.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
   at Elasticsearch.Net.Serialization.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy)
   at Elasticsearch.Net.Serialization.SimpleJson.DeserializeObject[T](String json)
   at Elasticsearch.Net.Serialization.ElasticsearchDefaultSerializer.Deserialize[T](Stream stream)
   at Elasticsearch.Net.Connection.Transport.ThrowOrGetErrorFromStreamResponse[T](TransportRequestState`1 requestState, ElasticsearchResponse`1 streamResponse)
   at Elasticsearch.Net.Connection.Transport.DoRequest[T](TransportRequestState`1 requestState)
   at Elasticsearch.Net.Connection.Transport.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticsearchClient.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticsearchClient.Index(String index, String type, Object body, Func`2 requestParameters)
   at UNITE.LogWriter.WriteInfoToElasticSearch(String currentDateTime, String logWriterName, String message)
```

No further information is available.

**Comment by jonyadamit** [comment]
`ElasticsearchClient` is the low level client.
If you have no special reason to do so, I suggest you use `ElasticClient` class instead.
Then you could just `client.Index(lo);` :smile:

**Comment by mgrigajtis** [comment]
I do have a reason for using the low level client.  There are going to be many different message writers and we want them separately indexed.

**Comment by mgrigajtis** [comment]
Actually, the high level might be adequate.  I'll see if that fits.

**Comment by jonyadamit** [comment]
Seperate indices can be easily accomplished like so:
`client.Index(lo, d => d.Index(logWriterName));`
If I do not understand you correctly and still you wish to use the low level client, can you try remove the call to `new JavaScriptSerializer().Serialize()`?

**Comment by mgrigajtis** [comment]
I have tried the low level client without the JavaScript serializer, same error.

Well, I tried the high level client.  Also broken.

```
private static void WriteInfoToElasticSearch(string currentDateTime, string logWriterName, string message)
        {
            var node = new Uri("http://10.40.50.146:9200");
            //var config = new ConnectionConfiguration(node);
            //var client = new ElasticsearchClient(config);
            var settings = new ConnectionSettings(node, defaultIndex: logWriterName);
            var client = new ElasticClient(settings);

            var lo = new LogObject();
            lo.logWriter = logWriterName;
            lo.message = message;
            lo.timestamp = currentDateTime;

            try
            {
                // var response = client.Index(logWriterName, "SentMessage", new JavaScriptSerializer().Serialize(lo), null);
                var response = client.Index(lo);
            }
            catch (Exception ex)
            {
                WriteErrorToTextFile(currentDateTime, logWriterName, " problem sending to Elastic Search ", logWriterName + "Error.log", ex);
            }
        }
```

And the error message:
```
1/19/2016 9:57:03 AM MessageReaderWriter ERROR  problem sending to Elastic Search  Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'error', line 1, position 10.
   at Newtonsoft.Json.JsonReader.ReadAsStringInternal()
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Nest.NestSerializer.DeserializeUsingSettings[T](Stream stream, JsonSerializerSettings settings)
   at Nest.NestSerializer.Deserialize[T](Stream stream)
   at Elasticsearch.Net.Connection.Transport.ThrowOrGetErrorFromStreamResponse[T](TransportRequestState`1 requestState, ElasticsearchResponse`1 streamResponse)
   at Elasticsearch.Net.Connection.Transport.DoRequest[T](TransportRequestState`1 requestState)
   at Elasticsearch.Net.Connection.Transport.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticsearchClient.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticsearchClient.Index[T](String index, String type, Object body, Func`2 requestParameters)
   at Nest.RawDispatch.IndexDispatch[T](ElasticsearchPathInfo`1 pathInfo, Object body)
   at Nest.ElasticClient.<>c__DisplayClass459_0`1.<Index>b__1(ElasticsearchPathInfo`1 p, IndexDescriptor`1 d)
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[D,Q,R](D descriptor, Func`3 dispatch)
   at Nest.ElasticClient.Index[T](T object, Func`2 indexSelector)
   at UNITE.LogWriter.WriteInfoToElasticSearch(String currentDateTime, String logWriterName, String message)
```

Note that our installation of Elastic Search does work and indexes properly from other applications.

**Comment by Mpdreamz** [comment]
Are you using NEST 1.x with Elasticsearch 2.x ?

**Comment by mgrigajtis** [comment]
Here's the version of ElasticSearch (remote host)
```
{
  "name" : "Mikula Golubev",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.1.1",
    "build_hash" : "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
    "build_timestamp" : "2015-12-15T13:05:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}
```

The Nuget packages ones used were the ones that Visual Studio 2015 recognized as stable.
ElasticSearch.Net 1.7.1
Nest 1.7.1

**Comment by jonyadamit** [comment]
Seems like ES 2.1 is returning an error that the 1.7.1 version cannot understand.. can you try manually sending the same index request (by using head plugin/curl/postman) and see what response you get?

**Comment by gmarz** [comment]
@jonyadamit  That's correct.  Error responses have changed drastically in ES 2.x and are more structured now.  This is one of the many reasons NEST 1.x is not compatible with ES 2.x.

@mgrigajtis our ES 2.x compatible client (NEST 2.0.0-alpha1) is now in pre-release mode.  If you're installing via the package manager UI make sure you check `Include pre-releases`.  If you're using the console, then use the `Pre` flag.

**Comment by mgrigajtis** [comment]
Version 2 alpha nuget packages do not work either.  I've tried them.

Using postman everything works as expected.

**Comment by mgrigajtis** [comment]
Allow me to be a bit more specific.  I have cleaned out all of the packages, and installed the 2.0.0 alpha1 version.  It no longer throws an error, but the error is encapsulated in the response object.  Here's the error:

```
{StatusCode: 400, 
	Method: PUT, 
	Url: http://10.40.50.146:9200/Test/logobject, 
	Request: {"timestamp":"1/19/2016 11:38:39 AM","message":"System.Exception: Exception of type 'System.Exception' was thrown.","logWriter":"Test"}, 
	Response: <Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
	ExceptionMessage: The remote server returned an error: (400) Bad Request.
	 StackTrace:    at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 138}
```

The strange thing here is that I did trigger the DisabledDirectStreaming() method before calling this object.

**Comment by mgrigajtis** [comment]
Ok, I got it to work, using the low level library.  Here's how:

```
private static void WriteInfoToElasticSearch(string currentDateTime, string logWriterName, string message)
        {
            var node = new Uri("http://10.40.50.146:9200");
            var config = new ConnectionConfiguration(node);
            var client = new ElasticsearchClient(config);

            var lo = new LogObject();
            lo.logWriter = logWriterName;
            lo.message = message;
            lo.timestamp = currentDateTime.ToString();

            try
            {
                var response = client.Index<object>(logWriterName.ToLower(), "sent_message", lo);
            }
            catch (Exception ex)
            {
                WriteErrorToTextFile(currentDateTime, logWriterName, " problem sending to Elastic Search ", logWriterName + "Error.log", ex);
            }
```

It's interesting that I had to force the index name to lower string.  Elastic search doesn't like capitals as an index name for some reason, and can't handle it.  I'm not sure if type follows the same rules, but I applied the rule to it anyway.  Also, I had to specify the return type from the method.  Seemed awkward, but it does the trick.

**Comment by Mpdreamz** [comment]
Good to hear the uppercase in index name explains the 400. 

Just as an FYI:
In the lowlevel client we have no mapped responses so a call to 

`Index()` returns a dynamic object (deserialized using an embedded SimpleJson. 
`Index<T>()` behaves differently depending on `T`


`T` is `Stream` returns you direct access to the response stream
`T` is `string` returns response as string
`T` is `byte[]` returns response as byte[]
`T` is `VoidResponse` body is ignored.

any other `T` we attempt deserialize the entire body to `T` e.g `object` in your case.

**Comment by mgrigajtis** [comment]
Actually, the upper case doesn't explain the 400, because I tried that on the high level DLL before switching back to the low level.  That one is still a mystery to me.
