### ISSUE TITLE
CreatePropertyMapping does not have an implementation Error with ConnectionSettings constructor

### ISSUE THREAD

**Issue by JefStat** [elastic/elasticsearch-net#1802]
The following line creates this stack trace with NEST 2.0.0-RC1 

````
var connectionSettings = new ConnectionSettings(nodeUri)
                .DefaultIndex(safeIndexName)
                .DisableDirectStreaming()
                .OnRequestCompleted(RequestLogger);
````

````
Method 'CreatePropertyMapping' in type 'Nest.JsonNetSerializer' from assembly 'Nest, Version=2.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d' does not have an implementation."
   at Nest.ConnectionSettings`1.DefaultSerializer(TConnectionSettings settings)
   at Elasticsearch.Net.ConnectionConfiguration`1.<.ctor>b__89_0(T c) in C:\users\russ\source\elasticsearch-net\src\Elasticsearch.Net\Configuration\ConnectionConfiguration.cs:line 163
   at Elasticsearch.Net.ConnectionConfiguration`1..ctor(IConnectionPool connectionPool, IConnection connection, Func`2 serializerFactory) in C:\users\russ\source\elasticsearch-net\src\Elasticsearch.Net\Configuration\ConnectionConfiguration.cs:line 165
   at Nest.ConnectionSettings`1..ctor(IConnectionPool connectionPool, IConnection connection, Func`2 serializerFactory) in C:\Users\russ\source\elasticsearch-net\src\Nest\CommonAbstractions\ConnectionSettings\ConnectionSettings.cs:line 67
   at Nest.ConnectionSettings..ctor(Uri uri) in C:\Users\russ\source\elasticsearch-net\src\Nest\CommonAbstractions\ConnectionSettings\ConnectionSettings.cs:line 19
```

**Comment by Mpdreamz** [comment]
Can you make sure you have a clean build? No trailing refs in the outpitdir. Also make sure all your projects are on the rc1. 

Sounds like an older dll makes it way into bin.

**Comment by JefStat** [comment]
Yup that was the PEBKAC issue. I had updated Elasticsearch-net from Alpha-2.0 to RC1 and missed updating NEST in parallel.
