### ISSUE TITLE
IndicesStats - Cannot access a disposed object. / Cannot access a closed Stream.

### ISSUE THREAD

**Issue by attilalaszlo** [elastic/elasticsearch-net#1851]
Hello!

I'm using ElasticSearch.Net and Nest 2.0.2 in an ASP.NET 5 application, hosted on Ubuntu.
I'm calling client.IndicesStats(Indices.AllIndices) in one of my method and randomly the response is not valid. The OriginalException in the IResponse is these two:

<code>
An unhandled exception was thrown by the application.
      System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'System.Net.Http.ByteArrayContent'.
         at System.Net.Http.HttpContent.CheckDisposed()
         at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context)
         at System.Net.Http.CurlHandler.HttpContentAsyncStream.<Run>b__26_0()
         at System.Threading.Tasks.Task`1.InnerInvoke()
         at System.Threading.Tasks.Task.Execute()
</code>

and

<code>
An unhandled exception was thrown by the application.
      System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.ObjectDisposedException: Cannot access a closed Stream.
         at System.IO.__Error.StreamIsClosed()
         at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
         at System.IO.MemoryStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
</code>

Do you have any idea about this situation? I did not found solution for this.

Thanks!

**Comment by attilalaszlo** [comment]
maybe something in the HttpConnection-CoreFx.cs but I didn't find any relevant thing

**Comment by attilalaszlo** [comment]
I investigated it for several days, finally I got it.
It's a corefx issue, not an elasticsearch-net bug.
Created an issue for this: https://github.com/dotnet/corefx/issues/8113

I think this bug can be closed.

**Comment by russcam** [comment]
@attilalaszlo glad you managed to find the root cause, thanks for the update :+1:
