### ISSUE TITLE
Duplicate Key in Enum Cache

### ISSUE THREAD

**Issue by zeus82** [elastic/elasticsearch-net#1857]
Looks like the enum cache is not thread safe.  When our application starts up, it makes a bunch of requests and more often that not we get a duplicate key exception which traces back to the enum cache.

Here is the stack trace:

```
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Nest.Extensions.ToEnum[T](String str) in c:\code\elasticsearch-net\src\Nest\CommonAbstractions\Extensions\Extensions.cs:line 93
   at Nest.Time..ctor(String timeUnit) in c:\code\elasticsearch-net\src\Nest\CommonOptions\TimeUnit\Time.cs:line 66
   at Nest.Time.op_Implicit(String expression) in c:\code\elasticsearch-net\src\Nest\CommonOptions\TimeUnit\Time.cs:line 26

```

**Comment by baddonkey** [comment]
Have exactly the same issue.

**Comment by zeus82** [comment]
I have submitted a pull request with a fix.

https://github.com/elastic/elasticsearch-net/pull/1858

**Comment by Mpdreamz** [comment]
doh! I thought I did a proper pass over the code to make sure this wouldn't slip in :cry: 

Thanks for reporting this one guys, we'll do a patch release later today.
