### ISSUE TITLE
NullReferenceException is thrown while trying to map an attachment type with fluent api

### ISSUE THREAD

**Issue by nerdomancer** [elastic/elasticsearch-net#1864]
This mapping was working on NEST 1.7 but with 2.0.2 I am getting a NullReferenceException.
{"Object reference not set to an instance of an object."}

Is there something I am doing wrong?

NEST 2.0.2
Elasticsearch 2.2.0
.NET 4.5.1
Windows 7

Code for easy view:

![image](https://cloud.githubusercontent.com/assets/11947866/13288236/c0b66d90-db13-11e5-8bd3-81093c7c5870.png)

Code for copy & paste
`var mappingResponse = elasticClient.Map<Doc>(pmd => pmd
                                    .Index(Indices.Index(defaultIndexName))
                                    .Properties(ps => ps
                                        .Attachment( atm => atm                                           
                                            .Name (p => p.base64string)
                                            .FileField(f => f                                                   
                                                   .Index(FieldIndexOption.Analyzed).TermVector(TermVectorOption.WithPositionsOffsets))                                                   
                                            .TitleField( t => t
                                                   .Name( p => p.filename)
                                                   .Index(FieldIndexOption.NotAnalyzed)
                                                   .Store(true)))));`

Related callstack:
   at Nest.AttachmentPropertyDescriptor`1.SetMetadataField[TDescriptor,TInterface](Func`2 selector, String fieldName)
   at Nest.AttachmentPropertyDescriptor`1.FileField(Func`2 selector)  
   at Nest.PropertiesDescriptor`1.SetProperty[TDescriptor,TInterface](Func`2 selector)
   at Nest.PropertiesDescriptor`1.Attachment(Func`2 selector)   
   at Nest.PutMappingDescriptor`1.<>c__DisplayClass103_0.<Properties>b__0(ITypeMapping a)
   at Nest.Fluent.Assign[TDescriptor,TInterface](TDescriptor self, Action`1 assign)
   at Nest.PutMappingDescriptor`1.Assign(Action`1 assigner)
   at Nest.PutMappingDescriptor`1.Properties(Func`2 propertiesSelector)   
   at Nest.ElasticClient.Map[T](Func`2 selector)

**Comment by nerdomancer** [comment]
I think this is a duplicate of #1826 and can be closed if you agree.

**Comment by gmarz** [comment]
Closed via #1827
