### ISSUE TITLE
Trying to Sort Mixed Type Query in NEST 2.X

### ISSUE THREAD

**Issue by tveyes** [elastic/elasticsearch-net#1929]
Hello,

I'm trying to figure out how to set a sort field when querying. I've looked at the tests, but can't figure out how they apply when dealing with multiple types. As near as I can tell all of the examples in SortUsageTests apply only to a single type.

To simplify things I decided to try sorting using DocumentIndexOrder:

   ```
         var response = esClient.Search<object>(s => s
                .From(request.from)
                .Size(request.size)
                .Index("matches")
                .Type(Types.Type(typeof(TypeA), typeof(TypeB)))
                .Query(q=>q
                    .QueryString(qs => qs.Query(request.query))
                )
                .Sort(ss=>ss
                    .Descending(SortSpecialField.DocumentIndexOrder)
                )
            );
```

This, however, throws an exception:

```
An exception of type 'Elasticsearch.Net.UnexpectedElasticsearchClientException' occurred in Elasticsearch.Net.dll but was not handled in user code

Additional information: Cannot implicitly convert type 'Newtonsoft.Json.Linq.JValue' to 'double'. An explicit conversion exists (are you missing a cast?)
```

What's the right way to sort by a field by Name in a multi-type situation?
What's the right way to sort by DocumentIndexOrder?

Many Thanks!

-D

**Comment by tbrooks007** [comment]
I ran into this issue last night. I am using v2.0.2 as well. I was sorting on both the _score field and a mapped date field. When sorting by the score only, I didn't receive the error but when I tried to sort on both the score and the date fields I received the same error listed in this ticket.  In NEST 1.4 this worked. After doing some more reading on sorting, I see that scores will not be returned if you are sorting on a field unless you set TrackScores to true. This will ensure that the that scores will be tracked and computed. After I add this to my query, the query returned mixed type results using both _score and the mapped date field. All serialization worked as well.

Hope this helps.

**Comment by tveyes** [comment]
Thanks for that suggestion, but it hasn't solved my issue.

My new Query looks like this:

```
           var response = esClient.Search<object>(s => s
                .From(request.from)
                .Size(request.size)
                .Index("matches")
                .Type(Types.Type(typeof(TypeA), typeof(TypeB)))
                .Query(q=>q
                    .QueryString(qs => qs.Query(request.query))
                )
                .TrackScores(true)
                .Sort(ss=>ss
                    .Descending(SortSpecialField.DocumentIndexOrder)
                )
            );
```

It's still blowing up when trying to sort. Here's the full debug stack trace:

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException was unhandled by user code
  HResult=-2146233088
  Message=Cannot implicitly convert type 'Newtonsoft.Json.Linq.JValue' to 'double'. An explicit conversion exists (are you missing a cast?)
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       at CallSite.Target(Closure , CallSite , Object )
       at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
       at Nest.ConcreteTypeConverter.GetConcreteTypeUsingSelector[T](JsonSerializer serializer, ConcreteTypeConverter`1 realConcreteConverter, JObject jObject) in C:\es\src\Nest\CommonAbstractions\SerializationBehavior\StatefulDeserialization\ConcreteTypeConverter.cs:line 125
       at Nest.ConcreteTypeConverter.GetUsingConcreteTypeConverter[T](JsonReader reader, JsonSerializer serializer, ConcreteTypeConverter`1 realConcreteConverter) in C:\es\src\Nest\CommonAbstractions\SerializationBehavior\StatefulDeserialization\ConcreteTypeConverter.cs:line 83
       at Nest.ConcreteTypeConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\es\src\Nest\CommonAbstractions\SerializationBehavior\StatefulDeserialization\ConcreteTypeConverter.cs:line 62
       at Nest.DefaultHitJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\es\src\Nest\CommonAbstractions\SerializationBehavior\StatefulDeserialization\ConcreteTypeConverter.cs:line 30
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
  InnerException: 
```

I'm pretty sure this is a bug. But I'm not sure.

Thanks!

-Dave
