### ISSUE TITLE
IndexMany: A connection that was expected to be kept alive was closed by the server

### ISSUE THREAD

**Issue by andrewrimmer** [elastic/elasticsearch-net#2019]
I am consistently getting "The underlying connection was closed: A connection that was expected to be kept alive was closed by the server." error when indexing using IndexMany().

I have tried various batch sizes, but I consistently get the same errors. The latest run was with indexing 500 small documents, and the error comes back sub-second (so it isn't as if this is a long running request).

I can retry the same batch and it will go through after 1 or 2 retries.

I do not get this error for any other action, like getting a 1000 records via a search or indexing one at a time etc.

I am running NEST/Elasticsearch.net 2.1.1 and have tried against Elasticsearch 2.0 and 2.3 with the same results.

The full stack trace is below:-

System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security._SslStream.StartFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\users\russ\source\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 138

**Comment by russcam** [comment]
@andrewrimmer Would you be able to show how you're using IndexMany() when you get this exception? A small example that can replicate it would be awesome :+1: 

You're connecting via HTTPS?

**Comment by andrewrimmer** [comment]
I am using HTTPS along with basic authentication.

In an effort to isolate the issue, I now also bypass our load balancer and configure my ElasticClient with just one node.

I still get the issue even if I instantiate a new ElasticClient immediately before the call to IndexMany().

The application gets a batch of 100k documents, and then sends them in chunks of 500 to IndexMany(). Out of 200 calls, it will error about 5-10 times. The error always comes back in less than a second.

I will try get to extract a small example later.

**Comment by Mpdreamz** [comment]
Hi @andrewrimmer 

Can you play with `KeepAlive` on `WebRequest` setting it to true and false and see if that gives you better results?


```csharp
public class MyHttpConnection : HttpConnection
{
	protected override HttpWebRequest CreateHttpWebRequest(RequestData requestData)
	{
		var request = base.CreateHttpWebRequest(requestData);
		request.KeepAlive = false;
		return request;
	}
}
```

And register this as the `IConnection` on the constructor in you `ConnectionSettings`

We also set TCPKeepAlive's which you could try and kill it by adding this override:

```csharp
protected override void AlterServicePoint(ServicePoint requestServicePoint, RequestData requestData)
{
	requestServicePoint.UseNagleAlgorithm = false;
	requestServicePoint.Expect100Continue = false;
	requestServicePoint.ConnectionLimit = 10000;
}
```

**Comment by andrewrimmer** [comment]
Thanks @Mpdreamz  I have tried various combinations of the above, and it didn't make any difference.

I will see if there is anything I can tweak with the reverse proxy (nginx) that may resolve the issue. When I run the program over http, directly against elasticsearch I don't have any issues.

We have had our application in production for nearly a year and it has worked fine through the reverse proxy using SSL. It is only when I've added a new application using IndexMany and also using NEST 2.x rather than 1.x that I've experienced problems.

**Comment by russcam** [comment]
It'd be worth [**enabling Network Tracing**] (https://msdn.microsoft.com/en-us/library/hyb3xww8.aspx) to get the output from `HttpWebRequest` and correlating this with when the exception is thrown; this should give us more information on determining whether it's something in the client or your environment.

Please post here any interesting findings from tracing

**Comment by russcam** [comment]
@andrewrimmer I wonder if you are exceeding `http.max_content_length` - https://github.com/elastic/elasticsearch/issues/2902

Should see this in Elasticsearch logs if that's the case.

**Comment by andrewrimmer** [comment]
@russcam I will check to see if I can see anything in the logs. If I was hitting any limits, I would expect them regardless of going through a reverse proxy or not? At the moment I only get this problem going through nginx and SSL.

**Comment by russcam** [comment]
> If I was hitting any limits, I would expect them regardless of going through a reverse proxy or not? At the moment I only get this problem going through nginx and SSL.

Agreed, you would see them with or without a proxy.

Might be worth seeing whether it happens going via nginx proxy _without_ SSL?

**Comment by Mpdreamz** [comment]
@andrewrimmer are you still experiencing problems? Do you have a stacktrace for us if you connect over HTTP?

**Comment by Mpdreamz** [comment]
@andrewrimmer and other future googlers: closing this due to inactivity and our inabiliy to reproduce this if you get a similar exception please let us know!

**Comment by kbandrew** [comment]
Apologies for lack of response, I have been using the workaround of running my applications on the same network as the Elasticsearch cluster. 

I will revisit this soon, and will let you know if it is still a problem and any more info I can find.

**Comment by Mpdreamz** [comment]
Much appreciated @andrewrimmer! When you do let us here know maybe we can reproduce a similar environment as yours on azure to reproduce this.
