### ISSUE TITLE
SimpleJson Bug (Method may only be called on a Type for which Type.IsGenericParameter is true.)

### ISSUE THREAD

**Issue by peske** [elastic/elasticsearch-net#2052]
**NEST/Elasticsearch.Net version**: 2.2.0

**Elasticsearch version**: The latest (but not important)

**Description of the problem including expected versus actual behavior**: 

I've already posted this as a comment at https://github.com/elastic/elasticsearch-net/issues/1228, but now I have better description of the bug, so I've decided to open a new issue.

The bug causes `System.InvalidOperationException` to be thrown by `IElasticLowLevelClient.Bulk<byte[]>()` method, but possibly not only there since the bug is caused by `SimpleJson` which is probably used for serialization by many other methods. The following code snippets shows how you can reproduce the error:

```
Exception ex; // Some exception caught.

Dictionary<string,object> document = new Dictionary<string,object>{
    { "message", "My message"}, 
    { "exception", ex }
};

IElasticLowLevelClient client; // Client is initialized and works well

List<object> payload = new List<object>{
    new { index = new { _index = "myIndex", _type = "myDocumentType" } }, 
    document
};

client.Bulk<byte[]>(payload);// The line that throws the exception.
```

The exception is thrown only if `Exception` instance from the previous code snippet (`ex`) **is actually thrown and caught**. It will not happen if it is only created without being thrown/caught (i.e. `Exception ex = new Exception("An exception");` It makes sense because throwing an exception _enriches_ its content.

Simply put, `SimpleJson` class is not able to serialize `Exception` instance.

The problem is even bigger due to misleading exception message. As you can below FailureReason message states that the problem arose while trying to POST, although no POST request is emitted in the first place (thanks to Fiddler).

Workaround: Until the bug is fixed I've came out with a workaround that will do the trick - Not to send the `Exception` instance, but `ExpandoObject` created from it (by using Newtonsoft JSON). The exception will not be thrown if the document creation line from the previous code snippet is replaced with:
```
Dictionary<string,object> document = new Dictionary<string,object>{
    { "message", "My message"}, 
    { "exception", JsonConvert.DeserializeObject<ExpandoObject>(JsonConvert.SerializeObject(ex)) }
};
```

Well, I admit that this workaround is not perfect when it comes to performances, but in scenarios with up to 100 exceptions per second it will do the trick.

**Steps to reproduce**: Described above.

**Provide `DebugInformation` (if relevant)**:
```
FailureReason: Unexpected when trying to POST http://es.myserver.com:9200/_bulk

PingSuccess: Node: http://es.myserver.com:9200/ Took: 00:00:00.1320008
BadResponse: Node: http://es.myserver.com:9200/ Exception: InvalidOperationException Took: 00:00:00.3010120

InvalidOperationException Took: 00:00:00.2799696

Audit exception in step 1 BadResponse:

System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
at System.RuntimeType.get_DeclaringMethod()
at lambda_method(Closure , Object )
at Elasticsearch.Net.ReflectionUtils.<>c__DisplayClass33_0.b__0(Object source) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1864
at Elasticsearch.Net.PocoJsonSerializerStrategy.TrySerializeUnknownTypes(Object input, Object& output) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1463
at Elasticsearch.Net.PocoJsonSerializerStrategy.TrySerializeNonPrimitiveObject(Object input, Object& output) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1278
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1016
at Elasticsearch.Net.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1018
at Elasticsearch.Net.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1018
at Elasticsearch.Net.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
at Elasticsearch.Net.SimpleJson.SerializeObject(Object json, IJsonSerializerStrategy jsonSerializerStrategy) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 582
at Elasticsearch.Net.ElasticsearchDefaultSerializer.Serialize(Object data, Stream writableStream, SerializationFormatting formatting) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\ElasticsearchDefaultSerializer.cs:line 48
at Elasticsearch.Net.PostData1.Write(Stream writableStream, IConnectionConfigurationValues settings) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\PostData.cs:line 90 at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 128 at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 395 at Elasticsearch.Net.Transport1.RequestTReturn in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 68

Inner Exception: Method may only be called on a Type for which Type.IsGenericParameter is true.

System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
at System.RuntimeType.get_DeclaringMethod()
at lambda_method(Closure , Object )
at Elasticsearch.Net.ReflectionUtils.<>c__DisplayClass33_0.b__0(Object source) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1864
at Elasticsearch.Net.PocoJsonSerializerStrategy.TrySerializeUnknownTypes(Object input, Object& output) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1463
at Elasticsearch.Net.PocoJsonSerializerStrategy.TrySerializeNonPrimitiveObject(Object input, Object& output) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1278
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1016
at Elasticsearch.Net.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1018
at Elasticsearch.Net.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1018
at Elasticsearch.Net.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
at Elasticsearch.Net.SimpleJson.SerializeObject(Object json, IJsonSerializerStrategy jsonSerializerStrategy) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 582
at Elasticsearch.Net.ElasticsearchDefaultSerializer.Serialize(Object data, Stream writableStream, SerializationFormatting formatting) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\ElasticsearchDefaultSerializer.cs:line 48
at Elasticsearch.Net.PostData1.Write(Stream writableStream, IConnectionConfigurationValues settings) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\PostData.cs:line 90 at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 128 at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 395 at Elasticsearch.Net.Transport1.RequestTReturn in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 68

Exception:

Elasticsearch.Net.UnexpectedElasticsearchClientException: Method may only be called on a Type for which Type.IsGenericParameter is true. ---> System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
at System.RuntimeType.get_DeclaringMethod()
at lambda_method(Closure , Object )
at Elasticsearch.Net.ReflectionUtils.<>c__DisplayClass33_0.b__0(Object source) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1864
at Elasticsearch.Net.PocoJsonSerializerStrategy.TrySerializeUnknownTypes(Object input, Object& output) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1463
at Elasticsearch.Net.PocoJsonSerializerStrategy.TrySerializeNonPrimitiveObject(Object input, Object& output) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1278
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1016
at Elasticsearch.Net.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1018
at Elasticsearch.Net.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1018
at Elasticsearch.Net.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
at Elasticsearch.Net.SimpleJson.SerializeObject(Object json, IJsonSerializerStrategy jsonSerializerStrategy) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 582
at Elasticsearch.Net.ElasticsearchDefaultSerializer.Serialize(Object data, Stream writableStream, SerializationFormatting formatting) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\ElasticsearchDefaultSerializer.cs:line 48
at Elasticsearch.Net.PostData1.Write(Stream writableStream, IConnectionConfigurationValues settings) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\PostData.cs:line 90 at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 128 at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 395 at Elasticsearch.Net.Transport1.RequestTReturn in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 68
--- End of inner exception stack trace ---
at Elasticsearch.Net.Transport1.Request[TReturn](HttpMethod method, String path, PostData1 data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 88
at Elasticsearch.Net.ElasticLowLevelClient.DoRequestT in c:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticLowLevelClient.cs:line 58
at Elasticsearch.Net.ElasticLowLevelClient.BulkT in c:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 32
at 
... (my code)
```

**Comment by russcam** [comment]
@peske Thank you for the detailed report :+1: 

SimpleJson is used by the low level client, Elasticsearch.Net, in order to not have any dependencies with regards to json serialization. NEST, the high level client, on the other hand uses Json.Net so I would expect it to be able to handle caught exceptions with the stacktrace and other data similar to your workaround.

I'll see if we can handle this more gracefully and also return a better exception message.

**Comment by Mpdreamz** [comment]
Attached commit improves the exception message by introducing a clear separation between `BadResponse` and a new stage in the pipeline `BadRequest`. 

If the pipeline failure reason is `Unexpected` we attempt to fetch a more useful failure reason from the audit trail. 

Another subtle change is that the `DebugInformation` printed a step number that is 0 based. Since this a message intendend for humans and humans read ordinals starting from 1. This is now starts at 1 and we print the step number in the audit trail too.

New `DebugInformation`:

```
System.Exception: # FailureReason: Unrecoverable/Unexpected BadRequest while attempting POST http://localhost:9200/_bulk
 - [1] PingSuccess: Node: http://localhost:9200/ Took: 00:00:00.0156239
 - [2] BadRequest: Node: http://localhost:9200/ Exception: InvalidOperationException Took: 00:00:00.0997982
# Audit exception in step 2 BadRequest:
System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
...
...
...
```

**Comment by Mpdreamz** [comment]
^ this commit adds an exception writer to our simplejson strategy because simplejson by itself does not support thrown exceptions. 

The current writer just writes a single object and ignores inner exceptions

@gmarz @russcam @mivano @nblumhardt should we attempt to mimic the same behavior as [the serilog json formatter](https://github.com/serilog/serilog-sinks-elasticsearch/blob/master/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchJsonFormatter.cs)? 

e.g write out a single `exception` as a `list` of `(exception + flattened innerexceptions).Select((e, i) => e.Depth = i).Take(20)` ?

This could potentially help in cleaning up serilogs elasticsearch sink custom formatter which is still based on serilog `JsonFormatter` [which is now deprecated(ish) in serilog 2.0](https://nblumhardt.com/2016/07/serilog-2-0-json-improvements/).

**Comment by peske** [comment]
Suggestion: I'm not sure why you are trying so hard to avoid adding dependency on Newtonsoft JSON. It would resolve the issue, make your life easier, and _unify_ all internal JSON serialization.

**Comment by Mpdreamz** [comment]
There are many usecases/scenarios where that dependency is not practical which is what we try to accomodate and by having a json dependency free version we open serialization up to others as well. 

FYI if all you want is the low level client with the json.net serializer use `NEST` and call `client.LowLevel.*`. This won't use the internal simplejson for these lowlevel api calls but json.net.

Our long term goal however is very much to converge back to a single client with no dependencies. Wether that is through internalizing json.net or something else remains TBD.

**Comment by Mpdreamz** [comment]
Closing this, exception now gets written out as a flattened array which is the most useful way to query this data in elasticsearch.

Also cherry-picked related commits to `master`
