### ISSUE TITLE
Get exception when producing searchdescriptor

### ISSUE THREAD

**Issue by serefbilge** [elastic/elasticsearch-net#2131]
When producing of searchdescriptor from a jsonQuery I get an exception. What is wrong in my code ? (nest 2.3.3, Newtonsoft.Json 8.0.1)

code block where exception was thrown:
```
searchDesc = _nestClient.Serializer.Deserialize<SearchDescriptor<dynamic>>(new MemoryStream(Encoding.UTF8.GetBytes(queryJson)));
```
value of queryJson parameter is:

```
{
   "query": {
      "filtered": {
         "filter": {
            "bool": {
               "must": [
                  {
                     "term": {
                        "event_id": 4625
                     }
                  },
                  {
                     "range": {
                        "date_time": {
                           "lte": "2016-01-19T15:15:57.459Z",
                           "gt": "2016-01-19T15:10:57.459Z"
                        }
                     }
                  }
               ],
               "must_not": []
            }
         }
      }
   },
   "aggs": {
      "username": {
         "terms": {
            "field": "username",
            "min_doc_count": 10,
            "shard_size": 0,
            "size": 0,
            "order": {
               "_count": "desc"
            }
         }
      }
   }
}
```

and result of this query in sense is:

```
{
   "took": 32,
   "timed_out": false,
   "_shards": {
      "total": 4,
      "successful": 4,
      "failed": 0
   },
   "hits": {
      "total": 0,
      "max_score": null,
      "hits": []
   },
   "aggregations": {
      "username": {
         "doc_count_error_upper_bound": 0,
         "sum_other_doc_count": 0,
         "buckets": []
      }
   }
}
```

And the exception is:

```
Unexpected initial token 'Integer' when populating object. Expected JSON object or array. Path 'query.filtered.filter.bool.must[0].term.event_id', line 1, position 72. , 
 Stack Trace :    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Nest.FromJson.ReadAs[T](JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReadAsTypeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReserializeJsonConverter`2.ReadAs(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.FieldNameQueryJsonConverter`1.DeserializeJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReserializeJsonConverter`2.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Nest.FromJson.ReadAs[T](JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReadAsTypeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReserializeJsonConverter`2.ReadAs(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReserializeJsonConverter`2.DeserializeJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReserializeJsonConverter`2.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.QueryContainerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Nest.FromJson.ReadAs[T](JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReadAsTypeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Nest.FromJson.ReadAs[T](JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReadAsTypeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReserializeJsonConverter`2.ReadAs(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReserializeJsonConverter`2.DeserializeJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReserializeJsonConverter`2.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.QueryContainerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Nest.FromJson.ReadAs[T](JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReadAsTypeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Nest.FromJson.ReadAs[T](JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReadAsTypeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReserializeJsonConverter`2.ReadAs(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReserializeJsonConverter`2.DeserializeJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReserializeJsonConverter`2.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.QueryContainerJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Nest.FromJson.ReadAs[T](JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReadAsTypeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Nest.JsonNetSerializer.Deserialize[T](Stream stream)
```

**Comment by russcam** [comment]
NEST generally supports the _full_ form of the query DSL e.g.

```javascript
{
    "term": {
        "event_id": 4625
    }
}
```

needs to be the following for NEST to be able to deserialize

```javascript
{
    "term": {
        "event_id": { 
            "value" : 4625 
        }
    }
}
```

Similarly, terms aggregation `order` is expected to be a collection of orders.

When deserializing an `ISearchRequest`, the interface that `SearchRequestDescriptor<T>` implements it is deserialized as a concrete `SearchRequest`; deserialzing to this will work.

**Comment by serefbilge** [comment]
It was working with previous Nest(1.7.1) and it costs a lot to us :( By the way, I edited the query for testing; and it gave error for order as you said. I'm using aggregation order format as in documentation at the link below. What does nest expects as format of order ?

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html

error for edited query(event_id part was edited):

```
Cannot deserialize the current JSON object (e.g. {\"name\":\"value\"}) into type 'System.Collections.Generic.IList`1[Nest.TermsOrder]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.\r\nPath 'aggs.username.terms.order._count', line 35, position 48.
```

stacktrace:

```
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Nest.FromJson.ReadAs[T](JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReadAsTypeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Nest.FromJson.ReadAs[T](JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReadAsTypeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Nest.FromJson.ReadAs[T](JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.ReadAsTypeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Nest.JsonNetSerializer.Deserialize[T](Stream stream)
   at ElasticSearchEngine_Tests.ElasticSearchEngine_Methods.GetSearchDescriptor() in y:\Repos\SIEM\Back-End\Correlation-Engine\Natek.Siem.Correlation\SourceCode\ElasticSearchEngine_Tests\ElasticSearchEngine_Methods.cs:line 65

```

**Comment by russcam** [comment]
`order` is expected to be a collection of orders e.g. 

```javascript
"order": [{
    "_count": "desc"
}]
```

The [TermsAggregation has order defined as an `IList<TermsOrder>`](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/Aggregations/Bucket/Terms/TermsAggregation.cs#L31)

**Comment by russcam** [comment]
The following works

```c#
var json = @"{
	""query"": {
		""filtered"": {
		""filter"": {
			""bool"": {
				""must"": [
			{
				""term"": {
				""event_id"": { ""value"" : 4625 }

				}
			},
			{
				""range"": {
				""date_time"": {
					""lte"": ""2016-01-19T15:15:57.459Z"",
					""gt"": ""2016-01-19T15:10:57.459Z""
				}
				}
			}
		],
		""must_not"": []
			}
			}
		}
	},
	""aggs"": {
		""username"": {
			""terms"": {
			""field"": ""username"",
			""min_doc_count"": 10,
			""shard_size"": 0,
			""size"": 0,
			""order"": [{
				""_count"": ""desc""
			}]
			}
		}
	}
}";

var client = new ElasticClient();
var descriptor = client.Serializer.Deserialize<ISearchRequest>(new MemoryStream(Encoding.UTF8.GetBytes(json)));
```

**Comment by Mpdreamz** [comment]
Just wondering if you have the query already as stream/string/anonmous object why are you deserialzing to the `SearchDescriptor` ? 

You can also use `client.LowLevel.Search<SearchResponse<dynamic>(...)` to send that query in string directly to elasticsearch. 

We only test that json generated from NEST can be serialized and deserialized. In some cases we only support the long form of a construct in elsticsearch (such as the term query).

**Comment by serefbilge** [comment]
I'm deserializing it to use Nest's searchresult object. Like below:

```
var searchDescriptor = ElasticSearchEngine.GetSearchDescriptor(elasticQuery)
                                                                          .Index(rule.IndexName)
                                                                          .AllTypes().SearchType(SearchType.Count);

                                queryLast = ElasticSearchEngine.ConvertToJsonQuery(searchDescriptor);

                                NLogger.Debug("CorrelationProcess", "RunForAggregationType", "Updated elastic query for rule(ruleId = " + ruleId + ", frameTimeReference = " + frameTimeReference.ToLocalTime() + ", policyName = " + Policy.Name + ") is - " + Environment.NewLine + queryLast);

                                result = ElasticSearchEngine.GetSearchResult(searchDescriptor);
```

**Comment by serefbilge** [comment]
Thanks for answers. By the way what another things out of terms aggregation is changed for nest ? Is there any documentation for it ? Thanks in advance.

**Comment by russcam** [comment]
There's some documentation on [Terms Aggregation Usage](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/terms-aggregation-usage.html) and [a blog post with links to the summaries of breaking changes between 1.x and 2.x](https://www.elastic.co/blog/ga-release-of-nest-2-0-our-dot-net-client-for-elasticsearch); the changes were generated with tooling so it's possible that a few things have been missed.

**Comment by serefbilge** [comment]
One more question. Can I set index parameter after deserializing into SearchRequest ? As I searched, indexName for SearchRequest is set by its constructor; but after deserialization how can I set indexname property of SearchRequest ? Thanks for your patient.

**Comment by russcam** [comment]
@serefbilge There's no easy way to set this from a deserialized `SearchRequest` instance.

**Comment by gmarz** [comment]
Closing.  Feel free to continue commenting @serefbilge if you have any other questions.
