### ISSUE TITLE
EnableHttpCompression doesn't work correctly

### ISSUE THREAD

**Issue by darkfeanor** [elastic/elasticsearch-net#2150]
NEST/Elasticsearch.Net version : 2.3.3

Elasticsearch version: 2.3.2

Description of the problem including expected versus actual behavior:
I'm trying to use the compression between Client and Server and getting the following Error:

"System.InvalidOperationException: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects". 

I have used: "settings.EnableHttpCompression()"; at client and "http.compression:true" at server.

I'm using .net core rc1.

It seems to be a bug, or I'm making something wrong...

**Comment by gmarz** [comment]
Hey @darkfeanor I'm not having any success reproducing this (on .net core 1.0 rtm)

Mind sharing a complete code snippet that's failing for you?  Also, if you can paste the value of `DebugInformation` on the response here that would also be helpful.

**Comment by darkfeanor** [comment]
Hi! Here is an Example of my code:

` [Route("testES")]
        [HttpGet]
        public string testES()
        {
            var host = "localhost";
            var port = "9202";
            var node = new Uri("http://" + host + ":" + port + "/indexname/");
            var settings = new ConnectionSettings(node);
            settings.DisableDirectStreaming();
            settings.EnableHttpCompression();
            ElasticClient client = new ElasticClient(settings);

            var request = new SearchRequest()
            {
                Query = new TermsQuery() {
                    Field = "Test",
                    Terms = new string[] { "276055540680082", "528528001853706" },
                    Name = "Test"
                }
            };
            var response = client.Search<object>(request);
            return "";
        }`

And the DebugInformation:

`# FailureReason: Unexpected when trying to POST http://localhost:9202/indexname/_search
 - BadResponse: Node: http://localhost:9202/indexname/ Exception: InvalidOperationException Took: 00:00:00.3078855
# Audit exception in step 0 BadResponse:
System.InvalidOperationException: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
   at System.Net.Http.Headers.HttpHeaders.CheckHeaderName(String name)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at Elasticsearch.Net.HttpConnection.CreateHttpRequestMessage(RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 155
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 84
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 397
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 68
# Inner Exception: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
System.InvalidOperationException: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
   at System.Net.Http.Headers.HttpHeaders.CheckHeaderName(String name)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at Elasticsearch.Net.HttpConnection.CreateHttpRequestMessage(RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 155
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 84
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 397
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 68
# Exception:
Elasticsearch.Net.UnexpectedElasticsearchClientException: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects. ---> System.InvalidOperationException: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
   at System.Net.Http.Headers.HttpHeaders.CheckHeaderName(String name)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at Elasticsearch.Net.HttpConnection.CreateHttpRequestMessage(RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 155
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 84
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 397
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 68
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 88
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[T](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticLowLevelClient.cs:line 58
   at Elasticsearch.Net.ElasticLowLevelClient.Search[T](PostData`1 body, Func`2 requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 6778
   at Nest.LowLevelDispatch.SearchDispatch[T](IRequest`1 p, PostData`1 body) in c:\code\elasticsearch-net\src\Nest\_Generated\_LowLevelDispatch.generated.cs:line 2575
   at Nest.ElasticClient.<>c__DisplayClass486_0`2.<Search>b__0(ISearchRequest p, PostData`1 d) in c:\code\elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 73
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch) in c:\code\elasticsearch-net\src\Nest\ElasticClient.cs:line 56
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 dispatch) in c:\code\elasticsearch-net\src\Nest\ElasticClient.cs:line 46
   at Nest.ElasticClient.Search[T,TResult](ISearchRequest request) in c:\code\elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 71
   at Nest.ElasticClient.Search[T](ISearchRequest request) in c:\code\elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 65
   at TestProject.Controllers.WebApi.TestController.testES() in C:\Users\TestProject\Controllers\WebApi\TestController.cs:line 157
`

**Comment by darkfeanor** [comment]
Hi! Here is an Example of my code:

``` 
[Route("testES")]
[HttpGet]
public string testES()
{
var host = "localhost";
var port = "9202";
var node = new Uri("http://" + host + ":" + port + "/indexname/");
var settings = new ConnectionSettings(node);
settings.DisableDirectStreaming();
settings.EnableHttpCompression();
ElasticClient client = new ElasticClient(settings);
        var request = new SearchRequest()
        {
            Query = new TermsQuery() {
                Field = "Test",
                Terms = new string[] { "276055540680082", "528528001853706" },
                Name = "Test"
            }
        };
        var response = client.Search<object>(request);
        return "";
    }
```
And the DebugInformation:
```
# FailureReason: Unexpected when trying to POST http://localhost:9202/indexname/_search
BadResponse: Node: http://localhost:9202/indexname/ Exception: InvalidOperationException Took: 00:00:00.3078855 # Audit exception in step 0 BadResponse: System.InvalidOperationException: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects. at System.Net.Http.Headers.HttpHeaders.CheckHeaderName(String name) at System.Net.Http.Headers.HttpHeaders.Add(String name, String value) at Elasticsearch.Net.HttpConnection.CreateHttpRequestMessage(RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 155 at Elasticsearch.Net.HttpConnection.RequestTReturn in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 84 at Elasticsearch.Net.RequestPipeline.CallElasticsearchTReturn in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 397 at Elasticsearch.Net.Transport1.Request[TReturn](HttpMethod method, String path, PostData1 data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 68 # Inner Exception: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects. System.InvalidOperationException: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects. at System.Net.Http.Headers.HttpHeaders.CheckHeaderName(String name) at System.Net.Http.Headers.HttpHeaders.Add(String name, String value) at Elasticsearch.Net.HttpConnection.CreateHttpRequestMessage(RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 155 at Elasticsearch.Net.HttpConnection.RequestTReturn in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 84 at Elasticsearch.Net.RequestPipeline.CallElasticsearchTReturn in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 397 at Elasticsearch.Net.Transport1.Request[TReturn](HttpMethod method, String path, PostData1 data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 68 # Exception: Elasticsearch.Net.UnexpectedElasticsearchClientException: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects. ---> System.InvalidOperationException: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects. at System.Net.Http.Headers.HttpHeaders.CheckHeaderName(String name) at System.Net.Http.Headers.HttpHeaders.Add(String name, String value) at Elasticsearch.Net.HttpConnection.CreateHttpRequestMessage(RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 155 at Elasticsearch.Net.HttpConnection.RequestTReturn in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 84 at Elasticsearch.Net.RequestPipeline.CallElasticsearchTReturn in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 397 at Elasticsearch.Net.Transport1.Request[TReturn](HttpMethod method, String path, PostData1 data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 68 --- End of inner exception stack trace --- at Elasticsearch.Net.Transport1.Request[TReturn](HttpMethod method, String path, PostData1 data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 88 at Elasticsearch.Net.ElasticLowLevelClient.DoRequestT in c:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticLowLevelClient.cs:line 58 at Elasticsearch.Net.ElasticLowLevelClient.SearchT in c:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 6778 at Nest.LowLevelDispatch.SearchDispatchT in c:\code\elasticsearch-net\src\Nest_Generated_LowLevelDispatch.generated.cs:line 2575 at Nest.ElasticClient.<>c__DisplayClass486_02.<Search>b__0(ISearchRequest p, PostData1 d) in c:\code\elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 73 at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.DispatchTRequest,TQueryString,TResponse in c:\code\elasticsearch-net\src\Nest\ElasticClient.cs:line 56 at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.DispatchTRequest,TQueryString,TResponse in c:\code\elasticsearch-net\src\Nest\ElasticClient.cs:line 46 at Nest.ElasticClient.SearchT,TResult in c:\code\elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 71 at Nest.ElasticClient.SearchT in c:\code\elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 65 at TestProject.Controllers.WebApi.TestController.testES() in C:\Users\TestProject\Controllers\WebApi\TestController.cs:line 157 
```

**Comment by darkfeanor** [comment]
And here is the content of elasticsearch.yml :
```
cluster.name: cluster1
http.port: 9202
transport.tcp.port: 9302 
http.compression: true
```
