### ISSUE TITLE
Calling ElasticClient.Search method with DateRangeQuery and Source(true) throws exception

### ISSUE THREAD

**Issue by guneysus** [elastic/elasticsearch-net#2492]
**2.4.4 <= NEST/Elasticsearch.Net <= 2.5.0**:

**Elasticsearch version 2.4.1, 2.4.2, 5.0.2**:

The problem is only related to NEST >= 2.4.4, NEST<=2.5.0

Invoking `ElasticClient.Search` method giving a `DateRangeQuery` and `Source(true)` throws exception.

**Steps to reproduce**:
```csharp
var result = new ElasticClient().Search<object>(s => new SearchDescriptor<object>()
    .Source(true) // false does not throws exception.
    .Query(q => new DateRangeQuery()
    {
        Field = "date",
        GreaterThanOrEqualTo = new DateTime(2016, 1, 13),
        LessThanOrEqualTo = new DateTime(2016, 1, 14)
    }));
```

**Stack Trace**

**.NET**
    NestBugs.Reproduction.Tests.BugReproduction

    Elasticsearch.Net.UnexpectedElasticsearchClientException : Token PropertyName in state Property would result in an invalid JSON object. Path ''.
      ----> Newtonsoft.Json.JsonWriterException : Token PropertyName in state Property would result in an invalid JSON object. Path ''.
       at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Transport.cs:line 89
       at Elasticsearch.Net.ElasticLowLevelClient.Search[T](String index, PostData`1 body, Func`2 requestParameters) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 6835
       at Nest.LowLevelDispatch.SearchDispatch[T](IRequest`1 p, PostData`1 body) in C:\code\elasticsearch-net\src\Nest\_Generated\_LowLevelDispatch.generated.cs:line 2574
       at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch) in C:\code\elasticsearch-net\src\Nest\ElasticClient.cs:line 56
       at NestBugs.Reproduction.Tests.BugReproduction() in C:\Users\guneysu\workspace\repos\BugHunting\Nest\NestBugs.Reproduction\Tests.cs:line 59
    --JsonWriterException
       at Newtonsoft.Json.JsonWriter.AutoComplete(JsonToken tokenBeingWritten)
       at Newtonsoft.Json.JsonTextWriter.WritePropertyName(String name, Boolean escape)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
       at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
       at Nest.JsonNetSerializer.Serialize(Object data, Stream writableStream, SerializationFormatting formatting) in C:\code\elasticsearch-net\src\Nest\CommonAbstractions\SerializationBehavior\JsonNetSerializer.cs:line 89
       at Elasticsearch.Net.PostData`1.Write(Stream writableStream, IConnectionConfigurationValues settings) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\PostData.cs:line 104
       at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 120
       at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 414
       at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Transport.cs:line 69

**Elastic Search Console Output**
```
[2016-12-13 13:00:52,956][WARN ][http.netty               ] [Jean DeWolff] Caught exception while handling client http traffic, closing conn
ection [id: 0x014f941d, /0:0:0:0:0:0:0:1:53990 => /0:0:0:0:0:0:0:1:9200]
java.io.IOException: An existing connection was forcibly closed by the remote host.
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by russcam** [comment]
Thanks for reporting @guneysus; this is a bug and will be fixed in the next 2.x release.

In the meantime, if you need the source returned, you can omit the `.Source(true)` call altogether as the default behaviour is to return `_source` e.g.

```c#
var result = new ElasticClient().Search<object>(s => s
    .Query(q => q
        .DateRange(dr => dr
            .Field("date")
            .GreaterThanOrEquals(new DateTime(2016, 1, 13))
            .LessThanOrEquals(new DateTime(2016, 1, 14))
        )
    )
);
```

**Comment by russcam** [comment]
@guneysus This is now in [NEST 2.5.1 just released to Nuget](https://www.nuget.org/packages/NEST/2.5.1). Thanks again for opening the issue 👍
