### ISSUE TITLE
Exception when using SniffingConnectionPool with Uri list.  Works fine with StaticConnectionPool

### ISSUE THREAD

**Issue by ahazelwood** [elastic/elasticsearch-net#2499]
I am attempting to connect to a new ElasticSearch 5.1 cluster using the latest NEST library for a Service application running under .NET Framework 4.6.2.

This same code worked correctly in a earlier NEST version against a ElasticSearch 2.X cluster.

If I use a StaticConnectionPool, the connection works correctly.  As soon as I switch it to a SniffingConnectionPool, I get the exception messages show below.

My list of uris does not change and are generated using:  
```
                var uris = Config.GetAppSetting<string>("IndexUrls")
                    .Trim()
                    .Split(new[] { ' ', ';', ',' }, StringSplitOptions.RemoveEmptyEntries)
                    .Select(u => new Uri(u))
                    .ToList();

```
urls are stored in the format of:    http://host01.dc.domain.local:9200/,http://host02.dc.domain.local:9200/, etc...

Code being used that works:  

 ```
               var connectionPool = new StaticConnectionPool(uris, true);
                var settings = new ConnectionSettings(connectionPool);
                var client = new ElasticClient(settings);

                // Ensure that the Index exists
                if (!client.IndexExists(indexName).Exists) {
                           ... Do something here.

```
Code that does not work:

```
                var connectionPool = new SniffingConnectionPool(uris, true);
                var settings = new ConnectionSettings(connectionPool);
                settings.SniffOnStartup();
                settings.SniffOnConnectionFault();
                var client = new ElasticClient(settings);


                // Ensure that the Index exists
                if (!client.IndexExists(indexName).Exists) {
                           ... Do something here.

```
Fails with a "**Failed sniffing cluster state.**" exception.
```

StackTrace:

   at Elasticsearch.Net.RequestPipeline.Sniff() in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 355
   at Elasticsearch.Net.RequestPipeline.FirstPoolUsage(SemaphoreSlim semaphore) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 141
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Transport\Transport.cs:line 53
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[T](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\ElasticLowLevelClient.cs:line 61
   at Elasticsearch.Net.ElasticLowLevelClient.IndicesExists[T](String index, Func`2 requestParameters) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 2745
   at Nest.LowLevelDispatch.IndicesExistsDispatch[T](IRequest`1 p) in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\_Generated\_LowLevelDispatch.generated.cs:line 1339
   at Nest.ElasticClient.<IndexExists>b__295_0(IIndexExistsRequest p, PostData`1 d) in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\Indices\IndexManagement\IndicesExists\ElasticClient-IndexExists.cs:line 44
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch) in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\ElasticClient.cs:line 57
   at Nest.ElasticClient.IndexExists(IIndexExistsRequest request) in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\Indices\IndexManagement\IndicesExists\ElasticClient-IndexExists.cs:line 41
   at Nest.ElasticClient.IndexExists(Indices indices, Func`2 selector) in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\Indices\IndexManagement\IndicesExists\ElasticClient-IndexExists.cs:line 37
   at CI.Services.DocumentIndexer.IndexEngine.GetIndexClient(Int32 projectId) in D:\projects\3.25\source\processing\documents\CI.Services.DocumentIndexer\IndexEngine.cs:line 290
   
   
InnerException:

	Error converting value "inet[/0:0:0:0:0:0:0:0%0:9200]" to type 'System.Collections.Generic.IList`1[System.String]'. Path 'nodes.iRyes08bRR27iyeLGGeaPQ.http.bound_address', line 1, position 879.
	
StackTrace:

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Nest.JsonNetSerializer.Deserialize[T](Stream stream) in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\CommonAbstractions\SerializationBehavior\JsonNetSerializer.cs:line 124
   at Elasticsearch.Net.ResponseBuilder`1.SetBody(ElasticsearchResponse`1 response, Stream stream) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Transport\Pipeline\ResponseBuilder.cs:line 78
   at Elasticsearch.Net.ResponseBuilder`1.ToResponse() in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Transport\Pipeline\ResponseBuilder.cs:line 33
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 153
   at Elasticsearch.Net.RequestPipeline.Sniff() in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 337	
```

Thanks for all of the hard work on the client.

**Comment by russcam** [comment]
Thanks for reporting @ahazelwood. Would it be possible to capture the json response that causes this exception and add it here?

**Comment by ahazelwood** [comment]
Unfortunately, the client throws an Exception and doesn't allow me access to the ApiCall object.  Is there a way I'm not aware of to get this information from the ElasticClient?  

Here's the updated code I added:

```
                var connectionPool = new SniffingConnectionPool(uris, true);
                var settings = new ConnectionSettings(connectionPool);
                settings.SniffOnStartup();
                settings.SniffOnConnectionFault();
                settings.PrettyJson().OnRequestCompleted(details => 
                    logger.Debug( Encoding.UTF8.GetString(details.ResponseBodyInBytes))
                );
                settings.ThrowExceptions(false);
                var client = new ElasticClient(settings);

                IExistsResponse response1 = null;
                try {
                    response1 = client.IndexExists(indexName);
                    if (response1.ApiCall.ResponseBodyInBytes != null) {
                        var responseJson = Encoding.UTF8.GetString(response1.ApiCall.ResponseBodyInBytes);
                        logger.Info(responseJson);
                    }
                }
                catch (PipelineException pie) {
                    logger.Error(pie);
                }
```

The OnRequestCompleted handler never gets called.  I'm open to any other suggestions.

Thanks.

**Comment by gmarz** [comment]
@ahazelwood  can you paste the response from `_nodes/http,settings?flat_settings` on one of your nodes?

**Comment by ahazelwood** [comment]
`{"cluster_name":"document","nodes":{"iRyes08bRR27iyeLGGeaPQ":{"name":"docsearch02","transport_address":"inet[/10.0.3.2:9300]","host":"docsearch02","ip":"127.0.1.1","version":"1.7.3","build":"NA","http_address":"inet[/10.0.3.2:9200]","settings":{"path.logs":"/var/log/elasticsearch","path.work":"/tmp/elasticsearch","path.conf":"/etc/elasticsearch","path.data":"/var/lib/elasticsearch","path.home":"/usr/share/elasticsearch","pidfile":"/var/run/elasticsearch.pid","cluster.name":"document","transport.tcp.compress":"true","http.cors.enabled":"true","node.name":"docsearch02","index.number_of_replicas":"1","index.number_of_shards":"10","name":"docsearch02","client.type":"node","config":"/etc/elasticsearch/elasticsearch.yml","network.host.0":"10.0.3.2","network.host.1":"127.0.0.1","config.ignore_system_properties":"true"},"http":{"bound_address":"inet[/0:0:0:0:0:0:0:0%0:9200]","publish_address":"inet[/10.0.3.2:9200]","max_content_length_in_bytes":104857600}},"XPO9Z1V6TtCd54blhgevxw":{"name":"docsearch03","transport_address":"inet[/10.0.3.3:9300]","host":"docsearch03","ip":"127.0.1.1","version":"1.7.3","build":"NA","http_address":"inet[/10.0.3.3:9200]","settings":{"path.logs":"/var/log/elasticsearch","path.work":"/tmp/elasticsearch","path.conf":"/etc/elasticsearch","path.data":"/var/lib/elasticsearch","path.home":"/usr/share/elasticsearch","pidfile":"/var/run/elasticsearch.pid","cluster.name":"document","http.cors.enable":"true","node.name":"docsearch03","index.number_of_replicas":"1","index.number_of_shards":"10","name":"docsearch03","client.type":"node","config":"/etc/elasticsearch/elasticsearch.yml","network.host.0":"10.0.3.3","network.host.1":"127.0.0.1","config.ignore_system_properties":"true"},"http":{"bound_address":"inet[/0:0:0:0:0:0:0:0%0:9200]","publish_address":"inet[/10.0.3.3:9200]","max_content_length_in_bytes":104857600}},"Rf8IjdP3R5Kd06c5UpHECQ":{"name":"docsearch01","transport_address":"inet[/10.0.3.1:9300]","host":"docsearch01","ip":"127.0.1.1","version":"1.7.3","build":"NA","http_address":"inet[/10.0.3.1:9200]","settings":{"path.logs":"/var/log/elasticsearch","path.work":"/tmp/elasticsearch","path.conf":"/etc/elasticsearch","path.data":"/var/lib/elasticsearch","path.home":"/usr/share/elasticsearch","pidfile":"/var/run/elasticsearch.pid","cluster.name":"document","http.cors.enabled":"true","node.name":"docsearch01","index.number_of_replicas":"1","index.number_of_shards":"10","name":"docsearch01","client.type":"node","config":"/etc/elasticsearch/elasticsearch.yml","network.host.0":"10.0.3.1","network.host.1":"127.0.0.1","config.ignore_system_properties":"true"},"http":{"bound_address":"inet[/0:0:0:0:0:0:0:0:9200]","publish_address":"inet[/10.0.3.1:9200]","max_content_length_in_bytes":104857600}}}}`

**Comment by ahazelwood** [comment]
Here it is in pretty format.
```
{
  "cluster_name" : "document",
  "nodes" : {
    "iRyes08bRR27iyeLGGeaPQ" : {
      "name" : "docsearch02",
      "transport_address" : "inet[/10.0.3.2:9300]",
      "host" : "docsearch02",
      "ip" : "127.0.1.1",
      "version" : "1.7.3",
      "build" : "NA",
      "http_address" : "inet[/10.0.3.2:9200]",
      "settings" : {
        "path.logs" : "/var/log/elasticsearch",
        "path.work" : "/tmp/elasticsearch",
        "path.conf" : "/etc/elasticsearch",
        "path.data" : "/var/lib/elasticsearch",
        "path.home" : "/usr/share/elasticsearch",
        "pidfile" : "/var/run/elasticsearch.pid",
        "cluster.name" : "document",
        "transport.tcp.compress" : "true",
        "http.cors.enabled" : "true",
        "node.name" : "docsearch02",
        "index.number_of_replicas" : "1",
        "index.number_of_shards" : "10",
        "name" : "docsearch02",
        "client.type" : "node",
        "config" : "/etc/elasticsearch/elasticsearch.yml",
        "network.host.0" : "10.0.3.2",
        "network.host.1" : "127.0.0.1",
        "config.ignore_system_properties" : "true"
      },
      "http" : {
        "bound_address" : "inet[/0:0:0:0:0:0:0:0%0:9200]",
        "publish_address" : "inet[/10.0.3.2:9200]",
        "max_content_length_in_bytes" : 104857600
      }
    },
    "XPO9Z1V6TtCd54blhgevxw" : {
      "name" : "docsearch03",
      "transport_address" : "inet[/10.0.3.3:9300]",
      "host" : "docsearch03",
      "ip" : "127.0.1.1",
      "version" : "1.7.3",
      "build" : "NA",
      "http_address" : "inet[/10.0.3.3:9200]",
      "settings" : {
        "path.logs" : "/var/log/elasticsearch",
        "path.work" : "/tmp/elasticsearch",
        "path.conf" : "/etc/elasticsearch",
        "path.data" : "/var/lib/elasticsearch",
        "path.home" : "/usr/share/elasticsearch",
        "pidfile" : "/var/run/elasticsearch.pid",
        "cluster.name" : "document",
        "http.cors.enable" : "true",
        "node.name" : "docsearch03",
        "index.number_of_replicas" : "1",
        "index.number_of_shards" : "10",
        "name" : "docsearch03",
        "client.type" : "node",
        "config" : "/etc/elasticsearch/elasticsearch.yml",
        "network.host.0" : "10.0.3.3",
        "network.host.1" : "127.0.0.1",
        "config.ignore_system_properties" : "true"
      },
      "http" : {
        "bound_address" : "inet[/0:0:0:0:0:0:0:0%0:9200]",
        "publish_address" : "inet[/10.0.3.3:9200]",
        "max_content_length_in_bytes" : 104857600
      }
    },
    "Rf8IjdP3R5Kd06c5UpHECQ" : {
      "name" : "docsearch01",
      "transport_address" : "inet[/10.0.3.1:9300]",
      "host" : "docsearch01",
      "ip" : "127.0.1.1",
      "version" : "1.7.3",
      "build" : "NA",
      "http_address" : "inet[/10.0.3.1:9200]",
      "settings" : {
        "path.logs" : "/var/log/elasticsearch",
        "path.work" : "/tmp/elasticsearch",
        "path.conf" : "/etc/elasticsearch",
        "path.data" : "/var/lib/elasticsearch",
        "path.home" : "/usr/share/elasticsearch",
        "pidfile" : "/var/run/elasticsearch.pid",
        "cluster.name" : "document",
        "http.cors.enabled" : "true",
        "node.name" : "docsearch01",
        "index.number_of_replicas" : "1",
        "index.number_of_shards" : "10",
        "name" : "docsearch01",
        "client.type" : "node",
        "config" : "/etc/elasticsearch/elasticsearch.yml",
        "network.host.0" : "10.0.3.1",
        "network.host.1" : "127.0.0.1",
        "config.ignore_system_properties" : "true"
      },
      "http" : {
        "bound_address" : "inet[/0:0:0:0:0:0:0:0:9200]",
        "publish_address" : "inet[/10.0.3.1:9200]",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}

```

**Comment by gmarz** [comment]
@ahazelwood I noticed from the response that you're running version 1.7.3 of ES, which is not supported by NEST 5.x.

Support for inet addresses was removed in ES 5.0.0-alpha1: https://github.com/elastic/elasticsearch/pull/13905.

**Comment by ahazelwood** [comment]
@gmarz This is for a new installation of Elasticsearch following the documentation located at:  [https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html](https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html)  I'm open to any other suggestions, but this was a re-installation from what I believe is being published for Ubuntu Xenial on the Elasticsearch 5.X apt source.

**Comment by ahazelwood** [comment]
I made a few minor tweeks to the elasticearch.yml file (as I show below in the network section.  However, Elasticsearch is still reporting the following similar content in the http object for each node.   

`    "http" : {
        "bound_address" : "inet[/10.0.3.3:9200]",
        "publish_address" : "inet[/10.0.3.3:9200]",
        "max_content_length_in_bytes" : 104857600
      }
`

The underlying error messages are now resolving to:  

`Error converting value "inet[/10.0.3.3:9200]" to type 'System.Collections.Generic.IList`1[System.String]'. Path 'nodes.yKesZJ4HQLCj706UuJjTXg.http.bound_address', line 32, position 48.`

So I believe it is an issue with the way that the parsing is being done of the addresses. 

Here is the network section of my elasticsearch.yml files that were changed.

`############################## Network And HTTP ###############################

# Elasticsearch, by default, binds itself to the 0.0.0.0 address, and listens
# on port [9200-9300] for HTTP traffic and on port [9300-9400] for node-to-node
# communication. (the range means that if the port is busy, it will automatical
ly
# try the next port).

# Set the bind address specifically (IPv4 or IPv6):
#
#network.bind_host: 192.168.0.1

# Set the address other nodes will use to communicate with this node. If not
# set, it is automatically derived. It must point to an actual IP address.
#
#network.publish_host: 192.168.0.1

# Set both 'bind_host' and 'publish_host':
#
#network.host: 192.168.0.1
#network.host: ["10.0.3.2","127.0.0.1"]
#network.bind_host: ["10.0.3.2","127.0.0.1"]
#network.publish_host: ["10.0.3.2","127.0.0.1"]
network.bind_host: 10.0.3.2
network.publish_host: 10.0.3.2

# Set a custom port for the node to node communication (9300 by default):
#
#transport.tcp.port: 9300

# Enable compression for all communication between nodes (disabled by default):
#
transport.tcp.compress: true

# Set a custom port to listen for HTTP traffic:
#
#http.port: 9200

# Set a custom allowed content length:
#
#http.max_content_length: 100mb

# Disable HTTP completely:
#
#http.enabled: false
`

Here is the http settings reported back from elasticsearch:

`{
  "cluster_name" : "document",
  "nodes" : {
    "yKesZJ4HQLCj706UuJjTXg" : {
      "name" : "docsearch03",
      "transport_address" : "inet[/10.0.3.3:9300]",
      "host" : "docsearch03",
      "ip" : "127.0.1.1",
      "version" : "1.7.3",
      "build" : "NA",
      "http_address" : "inet[/10.0.3.3:9200]",
      "settings" : {
        "path.logs" : "/var/log/elasticsearch",
        "path.work" : "/tmp/elasticsearch",
        "path.conf" : "/etc/elasticsearch",
        "path.data" : "/var/lib/elasticsearch",
        "path.home" : "/usr/share/elasticsearch",
        "pidfile" : "/var/run/elasticsearch.pid",
        "cluster.name" : "document",
        "network.bind_host" : "10.0.3.3",
        "network.publish_host" : "10.0.3.3",
        "http.cors.enable" : "true",
        "node.name" : "docsearch03",
        "index.number_of_replicas" : "1",
        "index.number_of_shards" : "10",
        "name" : "docsearch03",
        "client.type" : "node",
        "config" : "/etc/elasticsearch/elasticsearch.yml",
        "config.ignore_system_properties" : "true"
      },
      "http" : {
        "bound_address" : "inet[/10.0.3.3:9200]",
        "publish_address" : "inet[/10.0.3.3:9200]",
        "max_content_length_in_bytes" : 104857600
      }
    },
    "EmByT65-Rf27kreYl6Obyw" : {
      "name" : "docsearch02",
      "transport_address" : "inet[/10.0.3.2:9300]",
      "host" : "docsearch02",
      "ip" : "127.0.1.1",
      "version" : "1.7.3",
      "build" : "NA",
      "http_address" : "inet[/10.0.3.2:9200]",
      "settings" : {
        "path.logs" : "/var/log/elasticsearch",
        "path.work" : "/tmp/elasticsearch",
        "path.conf" : "/etc/elasticsearch",
        "path.data" : "/var/lib/elasticsearch",
        "path.home" : "/usr/share/elasticsearch",
        "pidfile" : "/var/run/elasticsearch.pid",
        "cluster.name" : "document",
        "network.bind_host" : "10.0.3.2",
        "network.publish_host" : "10.0.3.2",
        "transport.tcp.compress" : "true",
        "http.cors.enabled" : "true",
        "node.name" : "docsearch02",
        "index.number_of_replicas" : "1",
        "index.number_of_shards" : "10",
        "name" : "docsearch02",
        "client.type" : "node",
        "config" : "/etc/elasticsearch/elasticsearch.yml",
        "config.ignore_system_properties" : "true"
      },
      "http" : {
        "bound_address" : "inet[/10.0.3.2:9200]",
        "publish_address" : "inet[/10.0.3.2:9200]",
        "max_content_length_in_bytes" : 104857600
      }
    },
    "geZrjk21QV-MYE9j7SIbBQ" : {
      "name" : "docsearch01",
      "transport_address" : "inet[/10.0.3.1:9300]",
      "host" : "docsearch01",
      "ip" : "127.0.1.1",
      "version" : "1.7.3",
      "build" : "NA",
      "http_address" : "inet[/10.0.3.1:9200]",
      "settings" : {
        "path.logs" : "/var/log/elasticsearch",
        "path.work" : "/tmp/elasticsearch",
        "path.conf" : "/etc/elasticsearch",
        "path.data" : "/var/lib/elasticsearch",
        "path.home" : "/usr/share/elasticsearch",
        "pidfile" : "/var/run/elasticsearch.pid",
        "cluster.name" : "document",
        "network.bind_host" : "10.0.3.1",
        "network.publish_host" : "10.0.3.1",
        "http.cors.enabled" : "true",
        "node.name" : "docsearch01",
        "index.number_of_replicas" : "1",
        "index.number_of_shards" : "10",
        "name" : "docsearch01",
        "client.type" : "node",
        "config" : "/etc/elasticsearch/elasticsearch.yml",
        "config.ignore_system_properties" : "true"
      },
      "http" : {
        "bound_address" : "inet[/10.0.3.1:9200]",
        "publish_address" : "inet[/10.0.3.1:9200]",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}`

**Comment by gmarz** [comment]
Hey @ahazelwood sorry, I should have been more clear on the cause of the error.  It's not because of the inet address, but because `bound_address` has changed in 5.x to an array.

You're using NEST 5.x which expects an array with ES 1.7.3 which is returning a string, hence the deserialization error.

I'm not familiar with the Ubuntu deb package, so I'm not sure what the issue is there.  All I can say is that based on the responses you pasted, you're not running ES 5.0.
