### ISSUE TITLE
Null reference exception when checking if index exist

### ISSUE THREAD

**Issue by Misterhex** [elastic/elasticsearch-net#2504]
Getting a null reference exception. 

v2.5.0

Stacktrace:
```
2016-12-20 11:48:44.3111|ERROR|   at Elasticsearch.Net.RequestData.get_Uri() in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Pipeline\RequestData.cs:line 15
   at Elasticsearch.Net.ResponseBuilder`1.Initialize(Nullable`1 statusCode, Exception exception) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Pipeline\ResponseBuilder.cs:line 46
   at Elasticsearch.Net.ResponseBuilder`1.ToResponse() in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Pipeline\ResponseBuilder.cs:line 28
   at Elasticsearch.Net.RequestPipeline.BadResponse[TReturn](ElasticsearchResponse`1& response, RequestData data, List`1 pipelineExceptions) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 487
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Transport.cs:line 103
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[T](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\ElasticLowLevelClient.cs:line 58
   at Elasticsearch.Net.ElasticLowLevelClient.IndicesExists[T](String index, Func`2 requestParameters) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 2514
   at Nest.LowLevelDispatch.IndicesExistsDispatch[T](IRequest`1 p) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\_Generated\_LowLevelDispatch.generated.cs:line 1238
   at Nest.ElasticClient.<IndexExists>b__276_0(IIndexExistsRequest p, PostData`1 d) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\Indices\IndexManagement\IndicesExists\ElasticClient-IndexExists.cs:line 43
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\ElasticClient.cs:line 56
   at Nest.ElasticClient.IndexExists(IIndexExistsRequest request) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\Indices\IndexManagement\IndicesExists\ElasticClient-IndexExists.cs:line 40
   at Nest.ElasticClient.IndexExists(Indices indices, Func`2 selector) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\Indices\IndexManagement\IndicesExists\ElasticClient-IndexExists.cs:line 36
```

**Comment by gmarz** [comment]
@Misterhex can you share the actual request?  Also, what version of ES are you running?

**Comment by Misterhex** [comment]
@gmarz 

ES version: 
2.4.1

request:
```
var indexExist = elasticClient.IndexExists(indexName);
```

**Comment by gmarz** [comment]
@Misterhex sorry I still don't have enough info to repro this.

Based on the stack trace though, it looks like this might not be related to just `IndexExists`.  

```
 at Elasticsearch.Net.RequestData.get_Uri()
```

Indicates `RequestData.Node` is null.  

Are you using a connection pool?  Can you also share your `ConnectionSettings`? Also, Is `DebugInformation` or is it not available because of the exception?

**Comment by Misterhex** [comment]
@gmarz 

```DebugInformation``` is not available because of the exception.

This is how i am setting up the ```ConnectionSettings```
```
var hosts = "http://node1:9200/,http://node2:9200/,http://node3:9200/,http://node4:9200/"
var uris = hosts.Split(',').Select(i => new Uri(i)).ToArray();
var nodes = uris.Select(uri => new Node(uri)).ToArray();
var pool = new SniffingConnectionPool(nodes);
var connectionSetting = new ConnectionSettings(pool);

connectionSetting.OnRequestCompleted(resp =>
{
	if (!resp.Success)
	Tracer.TraceInformation(resp.DebugInformation);
});

return new ElasticClient(connectionSetting);
```

**Comment by Mpdreamz** [comment]
@Misterhex can you tell me what `http://node1:9200/_nodes/_all/settings?flat_settings&timeout=2s` returns in the browser? 

If it contains public ip's make sure to scrub these before pasting them here :)

**Comment by Mpdreamz** [comment]
Closing this due to inactivity and failure to reproduce, @Misterhex happy to reopen when you have some time again to let me know what the reponse to `http://node1:9200/_nodes/_all/settings?flat_settings&timeout=2s` for you us 👍

**Comment by kirilyuro** [comment]
I am trying to debug a similar error, and I seem to be able to reproduce this by configuring the `ElasticClient` with a very small `RequestTimeout`:
```
var settings = new ConnectionSettings(...);
settings.RequestTimeout(new TimeSpan(0, 0, 0, 0, 1));
... 
var client = new ElasticClient(settings);
```
Could this be due to an incorrect handling of request timeout?  @Mpdreamz
