### ISSUE TITLE
illegal_state_exception

### ISSUE THREAD

**Issue by gwired2015** [elastic/elasticsearch-net#2526]
**NEST/Elasticsearch.Net version**: 5.0
**Elasticsearch version**: 5.0

**Description of the problem including expected versus actual behavior**:
Attempting to run:
ElasticsearchResponse<DynamicResponse> searchResponse = ElasticSearchClient.Search<DynamicResponse>(elasticSearchIndex, (object)search, null);

returns:
{"error":{"root_cause":[{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:36"}],"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:36"},"status":500}

**Steps to reproduce**:
 1.   Execute the following Query:

```json
{
   "query":{
      "multi_match":{
         "fields":[
            {
               "field":"Field1^5"
            },
            {
               "field":"Field2^20"
            },
            {
               "field":"*Field1^5"
            },
            {
               "field":"Field3^5"
            },
            {
               "field":"Field4^5"
            },
            {
               "field":"Field5^5"
            },
            {
               "field":"Field6^8"
            },
            {
               "field":"Field7^5"
            },
            {
               "field":"Field8^10"
            },
            {
               "field":"_all"
            }
         ],
         "query":"test",
         "type":"phrase",
         "use_dis_max":"true"
      }
   },
   "from":0,
   "size":0,
   "aggs":{
      "top_types":{
         "terms":{
            "field":"_type"
         },
         "aggs":{
            "top_type_hits":{
               "top_hits":{
                  "size":25,
                  "fields":[]
               }
            }
         }
      }
   }
}
```

 2.  Result
{"error":{"root_cause":[{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:36"}],"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:36"},"status":500}

 3.  Standard result set with 1 entry per type and list of all fields.

Functions in 2.4.1  - Query Runs in Sense either Post or Get.

**Comment by Mpdreamz** [comment]
This jumps out of example code:

```csharp
, (object)search,
```

What is `search` in this case?

**Comment by gwired2015** [comment]
The query

**Comment by Mpdreamz** [comment]
Is it a ` string` or an anonymous object?

`ElasticSearchClient.Search` what does it dispatch into the highlevel client or the lowlevel client?

**Comment by gwired2015** [comment]
Anonymous object.  

var search = new
            {

                query = new
                {
                    multi_match = new
                    {
                        fields = myfields,
                        query = keyword,
                        type = multi_match_type,
                        use_dis_max = "true"
                    }
                },
                from = 0,
                size = limitAllTypes,
                aggs = new
                {
                    count_by_type = new
                    {
                        terms = new
                        {
                            field = "_type"
                        }
                    }
                }
            };

This is what it looks like before it's populated.

It was working on 2.7.1 - I can see in fiddler that it is sending the appropriate query but the response coming back isn't the same as the response in Sense.  Sense is Gzipping the query so I cannot see what Sense is sending but the response is good.  Eg I copy paste the query into Sense and it just runs fine.

**Comment by gwired2015** [comment]
This is the fiddler trace.
POST http://127.0.0.1:9200/asylvius/_search HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: 127.0.0.1:9200
Content-Length: 379

{"query":{"multi_match":{"fields":[{"field":"Field1^5"},{"field":"Field2^20"},{"field":"*Field1^5"},{"field":"Field3^5"},{"field":"Field4^5"},{"field":"Field5^5"},{"field":"Field6^8"},{"field":"Field7^5"},{"field":"Field8^10"},"field":"_all"}],"query":"20","type":"phrase","use_dis_max":"true"}},"from":0,"size":0,"aggs":{"count_by_type":{"terms":{"field":"_type"}}}}
HTTP/1.1 500 Internal Server Error
content-type: application/json; charset=UTF-8
content-length: 211

{"error":{"root_cause":[{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:36"}],"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:36"},"status":500}

-------------------------------------------------------------------------------
I can copy and paste the query above adding into Sense and it just works.

**Comment by gmarz** [comment]
It's not valid JSON.  The last field object `,"field":"_all"}` is missing the starting `{`, hence the error message.

Can you share the `myfields` object?

**Comment by gwired2015** [comment]
Found this in the ElasticSearch Logs:

[2017-01-04T15:07:23,718][WARN ][r.suppressed             ] path: /asylvius/_search, params: {index=asylvius}
java.lang.IllegalStateException: Can't get text on a START_OBJECT at 1:36
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.text(JsonXContentParser.java:85) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.index.query.MultiMatchQueryBuilder.parseFieldAndBoost(MultiMatchQueryBuilder.java:697) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.index.query.MultiMatchQueryBuilder.fromXContent(MultiMatchQueryBuilder.java:590) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQueryBuilder(QueryParseContext.java:127) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:982) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.rest.action.search.RestSearchAction.parseSearchRequest(RestSearchAction.java:105) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.rest.action.search.RestSearchAction.prepareRequest(RestSearchAction.java:81) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:66) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:243) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:200) [elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.http.HttpServer.dispatchRequest(HttpServer.java:116) [elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:509) [transport-netty4-5.0.0.jar:5.0.0]
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:68) [transport-netty4-5.0.0.jar:5.0.0]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at org.elasticsearch.http.netty4.pipelining.HttpPipeliningHandler.channelRead(HttpPipeliningHandler.java:66) [transport-netty4-5.0.0.jar:5.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at org.elasticsearch.http.netty4.cors.Netty4CorsHandler.channelRead(Netty4CorsHandler.java:76) [transport-netty4-5.0.0.jar:5.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:513) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:467) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.1.5.Final.jar:4.1.5.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[2017-01-04T15:53:31,331][WARN ][r.suppressed             ] path: /asylvius/_search, params: {index=asylvius}
java.lang.IllegalStateException: Can't get text on a START_OBJECT at 1:36
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.text(JsonXContentParser.java:85) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.index.query.MultiMatchQueryBuilder.parseFieldAndBoost(MultiMatchQueryBuilder.java:697) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.index.query.MultiMatchQueryBuilder.fromXContent(MultiMatchQueryBuilder.java:590) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQueryBuilder(QueryParseContext.java:127) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:982) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.rest.action.search.RestSearchAction.parseSearchRequest(RestSearchAction.java:105) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.rest.action.search.RestSearchAction.prepareRequest(RestSearchAction.java:81) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:66) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:243) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:200) [elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.http.HttpServer.dispatchRequest(HttpServer.java:116) [elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:509) [transport-netty4-5.0.0.jar:5.0.0]
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:68) [transport-netty4-5.0.0.jar:5.0.0]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at org.elasticsearch.http.netty4.pipelining.HttpPipeliningHandler.channelRead(HttpPipeliningHandler.java:66) [transport-netty4-5.0.0.jar:5.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at org.elasticsearch.http.netty4.cors.Netty4CorsHandler.channelRead(Netty4CorsHandler.java:76) [transport-netty4-5.0.0.jar:5.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:513) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:467) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.1.5.Final.jar:4.1.5.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]

**Comment by gmarz** [comment]
@gwired2015 see my previous comment.

**Comment by gwired2015** [comment]
That last query post was a typo on my part editing the field names here to protect the innocent.
There is a { before the last fields as you can see in the original post.

I am using the LowLevelClient.

The myfields object gets populated like so:

            var field1 = new { field = "Field1^5" };
            var field2 = new { field = "Field2^20" };
            var field3 = new { field = "*Field1^5" };
            var field5 = new { field = "Field3^5" };
            var field6 = new { field = "Field4^5" };
            var field7 = new { field = "Field5^5" };
            var field8 = new { field = "Field6^8" };
            var field9 = new { field = "Field7^5" };
            var field10 = new { field = "Field8^10" };
            var field11 = new { field = "_all" };
            var myfields = new[] { field1, field2, field3, field5, field6, field7, field8, field9, field10, field11 };

**Comment by gwired2015** [comment]
I'm trying to refactor to the fluent syntax.  But it's not working:

ElasticsearchResponse<DynamicResponse> searchResponse =
                ElasticSearchClient.Search<DynamicResponse>(s => s.Query(q = q.MultiMatch(mm =>
                    mm.Fields("Field1^5",             Field2^20").Query("sreeni").Type(TextQueryType.Phrase).UseDisMax(true)))
                    .From(0)
                    .Size(0)
                    .Index("myindexname"));

Says:  Cannot convert lambda expression to type PostData<object> because it is not a delegate type.

**Comment by gwired2015** [comment]
The problem was the myfields object.  It was an array of fields as seen in the first post.  When I made it an object of listed fields like sp:

fields = new [] {"Field1^5","Field2^20","*Field1^5", "Field3^5", "Field4^5", "Field5^5", "Field6^8", "Field7^5", "Field8^10","_all" },
It passed through.

However I am getting a different error in the Top Hits section.

{"query":{"multi_match":{"fields":["Field1^5","Field2^20","*Field1^5","Field3^5","Field4^5","Field5^5","Field6^8","Field7^5","Field8^10","_all"],"query":"sreeni","type":"phrase","use_dis_max":"true"}},"from":0,"size":0,"aggs":{"top_types":{"terms":{"field":"_type"},"aggs":{"top_type_hits":{"top_hits":{"size":25,"fields":["Field1","Field2","Field17","Field18","Field19"]}}}}}}

Gives me this:

{"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a START_ARRAY in [fields].","line":1,"col":334}],"type":"parsing_exception","reason":"Unknown key for a START_ARRAY in [fields].","line":1,"col":334},"status":400}

Is this the reverse?  Now I need an array?

**Comment by gwired2015** [comment]
Ok so the problem is that fields isn't part of Top_Hits any longer.  I looked back at the documentation for ES on top hits and it all looks the same over time no where does it say fields is part of it but no where does it say it is no longer part of it that I can find.  

I had to change the query and add source instead of fields... as below:

"size": 25,
"_source":
{
includes:["Field1","Field2","Field17","Field18","Field19"]
}

Any one know where I could figure out information like that out.  Geesh what a chore.

Oh and btw my repsonse is different too... woo hoo have to rewrite all the code to extract the info I need.
:-(

**Comment by gmarz** [comment]
@gwired2015 great, glad you've got this sorted.  Going to close this for now.

> Oh and btw my repsonse is different too... woo hoo have to rewrite all the code to extract the info I need.

Any reason you're not using the high level client?

**Comment by gwired2015** [comment]
We are using Dynamic Anonymous Types for all entities.  From the NEST documentation, it seems you need classes.  We don't have any they are derived from metadata.  So our documents are mutable by end users and their capabilities such as calculations, actions etc are all done as metadata as well.
