### ISSUE TITLE
Exception: QueryContainer can only hold a single query already contains a MultiMatchQueryDescriptor`1

### ISSUE THREAD

**Issue by zubanova** [elastic/elasticsearch-net#2631]
**NEST/Elasticsearch.Net version**: 2.5.2

**Elasticsearch version**: 2.3.3

**Description of the problem including expected versus actual behavior**:
I update NEST package from 2.4.6 to 2.5.2 and exception occurred

**Code**:
```
	public class StaticPage
	{
		public string Id { get; set; }
		[String(Analyzer = "general_analyzer", SearchAnalyzer = "general_analyzer")]
		public string AnalyzedTitle { get; set; }
		[String(Analyzer = "general_analyzer", SearchAnalyzer = "general_analyzer")]
		public string Content { get; set; }
		public DateTime? PublishDate { get; set; }
	}
```
```
var query = CreateSearchQuery("text");
var descriptor = new SearchDescriptor<StaticPage>().Query(q => q.Bool(b => b.Must(query)));
client.Search<StaticPage>(d => descriptor);
```
		private static QueryContainer CreateSearchQuery(string query)
		{
			var qDescriptor = new QueryContainerDescriptor<StaticPage>();
				return qDescriptor.FunctionScore(fsq => fsq.Query(q => q.Bool(bq => bq.Should(
						qDescriptor.MultiMatch(ms => ms.Operator(Operator.And)
							.Query(query)
							.Boost(100)
							.Type(TextQueryType.CrossFields)
							.Fields(f => f
								.Field(obj => obj.AnalyzedTitle, 10)
								.Field(obj => obj.Content, 5)
							)),
						qDescriptor.MultiMatch(ms => ms.Operator(Operator.Or)
							.Query(query)
							.Boost(50)
							.Type(TextQueryType.PhrasePrefix)
							.Fields(f => f
								.Field(obj => obj.AnalyzedTitle, 10)
								.Field(obj => obj.Content, 5)
							))
						)))
						.Functions(f => f.LinearDate(s => s.Field(o => o.PublishDate).Origin("now/1h").Decay(0.5).Scale("12w")).Weight(0.001))
						.ScoreMode(FunctionScoreMode.Sum));
		}

**Provide `DebugInformation`**:
QueryContainer can only hold a single query already contains a MultiMatchQueryDescriptor`1

   at Nest.QueryContainer.Set[T](T value) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\QueryDsl\Abstractions\Container\QueryContainer-Assignments.cs:line 70
   at Nest.QueryContainer.Nest.IQueryContainer.set_FunctionScore(IFunctionScoreQuery value) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\QueryDsl\Abstractions\Container\QueryContainer-Assignments.cs:line 118
   at Nest.QueryContainerDescriptor`1.<>c.<FunctionScore>b__69_0(IFunctionScoreQuery query, IQueryContainer container) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\QueryDsl\Abstractions\Container\QueryContainerDescriptor.cs:line 521
   at Nest.QueryContainerDescriptor`1.WrapInContainer[TQuery,TQueryInterface](Func`2 create, Action`2 assign) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\QueryDsl\Abstractions\Container\QueryContainerDescriptor.cs:line 33
   at Nest.QueryContainerDescriptor`1.FunctionScore(Func`2 selector) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\QueryDsl\Abstractions\Container\QueryContainerDescriptor.cs:line 521
   at ConsoleApplication1.Program.CreateSearchQuery(String query) in c:\users\azubanov\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs:line 28
   at ConsoleApplication1.Program.Main(String[] args) in c:\users\azubanov\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs:line 55
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by gmarz** [comment]
Hi @zubanova thanks for reporting this.  I'm on the fence on whether or not it's a bug though.  While the behavior has changed, it changed for a good reason.

Reusing the query descriptor like you are doesn't quite make sense, and I'm not sure it was ever serializing as you were expecting in 2.4.2.  Instead, you should use the lambda notation and pass in a new query descriptor for each should clause, like so

```
.Should(qc => qc
	.MultiMatch(ms => ms
		.Operator(Operator.And)
		.Query("foo")
		.Boost(100)
		.Type(TextQueryType.CrossFields)
		.Fields(f => f
			.Field("foo", 10)
			.Field("bar", 5)
		)
	), qc => qc
	.MultiMatch(ms => ms
		.Operator(Operator.Or)
		.Query("foo")
		.Boost(50)
		.Type(TextQueryType.PhrasePrefix)
		.Fields(f => f
			.Field("foo", 10)
			.Field("bar", 5)
		)
	)
)
```

Let me know if that helps.

/cc @Mpdreamz @russcam

**Comment by zubanova** [comment]
Thank you!
your approach works nicely
