### ISSUE TITLE
Unable to search in indices with attachments (mapper-attachment plugin) NEST v5.2.0

### ISSUE THREAD

**Issue by thammadi** [elastic/elasticsearch-net#2670]
**NEST/Elasticsearch.Net version**: v5.2.0

**Elasticsearch version**: v5.2.2

**Description of the problem including expected versus actual behavior**:
We have our node hosted on Elastic Cloud and have many indices with PDF attachments stored (using mapper-attachment plugin)
Searching in these indexes, now returns error: **Attachment fields are not searchable**

**Steps to reproduce**:
 1. Create index with attachments using mapper-attachment
 2. Index PDF file(s)
 3. Search for text within PDF file

We were able to do this with NEST v2.4.4
This issue started appearing since we upgraded to NEST v5.2.0 and ElasticCloud v5.2.2

Searching in non attachment indices works fine

Debug Information:
Invalid NEST response built from a unsuccessful low level call on POST: /au_tcg/_search?ignore_unavailable=true
# Audit trail of this API call:
 - [1] BadResponse: Node: https://excluded.us-west-2.aws.found.io:9243/ Took: 00:00:01.0400595
# ServerError: ServerError: 400Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: query_shard_exception Reason: "Attachment fields are not searchable: [content]""
# OriginalException: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Elasticsearch.Net.HttpConnection.<RequestAsync>d__9`1.MoveNext() in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 204
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>

Cheers,

**Comment by russcam** [comment]
Could you provide an example of the kind of search you are performing?

**Comment by thammadi** [comment]
Hi @russcam ,

I'm doing a simple keyword search (e.g: 'exemption') from a PDF file ([DCR - A4 Copy paper.pdf](https://github.com/elastic/elasticsearch-net/files/850110/DCR.-.A4.Copy.paper.pdf))

PDF files like above, are indexed using the below code:

````
var result = await elasticClient.CreateIndexAsync(indexName, index => index
                .Mappings(mappings => mappings
                    .Map<IndexModel>("book_content", map => map
                       .Properties(properties => properties
                            .Attachment(att => att
                                .Name(name => name.content)
                                .FileField(fileField => fileField
                                    .Name("content")
                                    .TermVector(TermVectorOption.WithPositionsOffsets)
                                    .Store()
                                )
                           )
                        )
                    )
                )
                .Settings(settings => settings
                    .NumberOfReplicas(0)
                    .NumberOfShards(noOfShards)
                )
            );
````
```
var result = await elasticClient.IndexAsync(indexModel, i => i
                        .Index(indexName)
                        .Type("book_content")
                        .Id(Guid.NewGuid().ToString())
                        .Refresh(Elasticsearch.Net.Refresh.True)
                        //.Refresh()
                        .Ttl("1m")
                    );
```
Type:

```
public class IndexModel
    {
        public string id { get; set; }
        public string name { get; set; }
        public string content { get; set; }
    }
```

Below is the mapping:
```
{
  "book_content": {
    "properties": {
      "next": {
        "type": "text",
        "fields": {
          "keyword": {
            "ignore_above": 256,
            "type": "keyword"
          }
        }
      },
      "id": {
        "type": "text",
        "fields": {
          "keyword": {
            "ignore_above": 256,
            "type": "keyword"
          }
        }
      },
      "name": {
        "type": "text",
        "fields": {
          "keyword": {
            "ignore_above": 256,
            "type": "keyword"
          }
        }
      },
      "content": {
        "type": "attachment",
        "fields": {
          "date": {
            "type": "date"
          },
          "keywords": {
            "type": "text"
          },
          "content_type": {
            "type": "text"
          },
          "author": {
            "type": "text"
          },
          "name": {
            "type": "text"
          },
          "language": {
            "type": "text"
          },
          "title": {
            "type": "text"
          },
          "content": {
            "term_vector": "with_positions_offsets",
            "store": true,
            "type": "text"
          },
          "content_length": {
            "type": "integer"
          }
        }
      }
    }
  }
}
````

I don't have issues with indexing. Its just the search in attachment indices that stopped working. 
Surprisingly, I managed to get search hits from attachment related indices using Postman client.

**Comment by russcam** [comment]
@thammadi can you also provide the search that you're doing?
