### ISSUE TITLE
Forward port of #2659 causes failures 

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#2736]
I forward ported #2659 over to `5.x` and `master` but it causes integration tests failures (atleast on `5.3.0`)

This should be fixed before we release a new 5.x version.

```
[FAIL] Tests.Aggregations.Metric.TopHits.TopHitsAggregationUsageTests.ReturnsExpectedIsValid: Expected boolean to be True because Invalid NEST response built from a unsuccessful low level call on POST: /project/project/_search?pretty=true
# Audit trail of this API call:
 - [1] BadResponse: Node: http://ipv4.fiddler:9200/ Took: 00:00:00.3238589
# ServerError: ServerError: 400Type: parsing_exception Reason: "Unknown key for a START_ARRAY in [fields]."
# OriginalException: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData)
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
, but found False.
```

**Comment by V1tOr** [comment]
hi @Mpdreamz ,

in elasticsearch 5, the field is called "stored_fields". changing this should fix the issue.
