### ISSUE TITLE
Exception from the loop insert 290 thousand data !!!

### ISSUE THREAD

**Issue by inernoro** [elastic/elasticsearch-net#2750]
in asp.net core 1.1
[environment]: visual studio 2017 asp.net core 1.1
[action]:Loop insert 290 thousand data
[locahost]:192.168.9.9
[targethost(elasticsearch)]:192.168.9.112:9200
[innerexception]:null
[randomness]: not the first time
[description]
[stack]:  
 at tran.Controllers.ValuesController.Get() in D:\research\myself\tran\tran\Controllers\ValuesController.cs:line 40
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()

[message]:
Elasticsearch.Net.UnexpectedElasticsearchClientException: A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\Projects\elastic\net-5\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 70
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData) in C:\Projects\elastic\net-5\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 431
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Projects\elastic\net-5\src\Elasticsearch.Net\Transport\Transport.cs:line 69
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Projects\elastic\net-5\src\Elasticsearch.Net\Transport\Transport.cs:line 89
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[T](String index, PostData`1 body, Func`2 requestParameters) in C:\Projects\elastic\net-5\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 63
   at Nest.LowLevelDispatch.BulkDispatch[T](IRequest`1 p, PostData`1 body) in C:\Projects\elastic\net-5\src\Nest\_Generated\_LowLevelDispatch.generated.cs:line 0
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch) in C:\Projects\elastic\net-5\src\Nest\ElasticClient.cs:line 57
   at tran.Module.ElasticSearchRepository`2.InsertMany(IEnumerable`1 list) in D:\research\myself\tran\tran\Module\ElasticSearchRepository.cs:line 104
   at tran.Controllers.ValuesController.Get() in D:\research\myself\tran\tran\Controllers\ValuesController.cs:line 34

**Comment by Mpdreamz** [comment]
Can you explain a bit more what you are trying to do?

Are you doing a bulk with many loops inside an MVC action? What are your timeout settings?

**Comment by inernoro** [comment]
elasticsearch.net(v5.3.1/.net core)
1. I want to insert 290,000 pieces of data into linux elasticsearch (v5.1.1/ubuntu 16.04)
2. Insert 5000 data at a time, a total of 290,000 data, into the linux elasticsearch (v5.1.1/ubuntu 16.04)
3. No timeout is set

**Comment by Mpdreamz** [comment]
Can you confirm you are not hitting any of your webservers (nginx/kestrel) or web frameworks (mvc/nancy) request limits?

Assuming you are running this inside an MVC action based on the strack trace.

**Comment by Mpdreamz** [comment]
The `TaskCancelledException` should not have bubbled out like that on .NET core as per #2751. I've addressed this with #2753.

When doing many bulk indexation its very possible that you fill Elasticsearch's thread pool and that you start seeing 427 rejections and requests taking upwards of seconds. Our `BulkAll()` helper can help here.

When #2753 lands and we release a new `5.x` version please try again and reopen this ticket with a new `DebugInformation` dump of what went on.
