### ISSUE TITLE
Elasticsearch.Net on .Net Core does not return ElasticsearchResponse when RequestTimeout reached

### ISSUE THREAD

**Issue by rzontar** [elastic/elasticsearch-net#2751]
**NEST/Elasticsearch.Net version**:
5.3.1

**Elasticsearch version**:
5.3.1

**Description of the problem including expected versus actual behavior**:
Targeting .Net Core no `ElasticsearchResponse<T>` is returned when a RequestTimeout is reached, but rather an `UnexpectedElasticsearchClientException` is thrown. Targeting the .Net full Framework the `ElasticsearchResponse<T>` is returned normally.

**Steps to reproduce**:
 1. Set a minimal RequestTimeout
 2. target `net46`
 3. Execute a Query to cause a Timeout
 4. target `netcoreapp`
 5. Execute same Query

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

.Net Core (netcoreapp1.1) Exception:
`Elasticsearch.Net.UnexpectedElasticsearchClientException: A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\Projects\elastic\net-5\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 70
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData) in C:\Projects\elastic\net-5\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 431
   at Elasticsearch.Net.Transport1.Request[TReturn](HttpMethod method, String path, PostData1 data, IRequestParameters requestParameters) in C:\Projects\elastic\net-5\src\Elasticsearch.Net\Transport\Transport.cs:line 69
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport1.Request[TReturn](HttpMethod method, String path, PostData1 data, IRequestParameters requestParameters) in C:\Projects\elastic\net-5\src\Elasticsearch.Net\Transport\Transport.cs:line 89
   at Elasticsearch.Net.ElasticLowLevelClient.ClusterHealth[T](Func2 requestParameters) in C:\Projects\elastic\net-5\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 1149
   at Lyoness.CloudServices.CustomerBenefits.WebAPI.Contollers.Internal.ElasticController.ClusterHealth() in C:\Dev\Lyoness\trunk\LyoERP\Lyoness.CloudServices\CustomerBenefits\CloudServices.CustomerBenefits.WebAPI\Contollers\Internal\ElasticController.cs:line 28
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()`

.Net 4.6.2 Response:
`Unsuccessful low level call on GET: /_cluster/health
Audit trail of this API call:
 [1] BadResponse: Node: http://redacted:9200/ Took: 00:00:05.1034868
 [2] MaxTimeoutReached: Took: -736451.09:46:56.7423798
OriginalException: System.Net.WebException: Die Anfrage wurde abgebrochen: Die Anfrage wurde abgebrochen..
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Elasticsearch.Net.HttpConnection.<RequestAsync>d__141.MoveNext()
Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>`

**Comment by Mpdreamz** [comment]
Thank you for reporting this @rzontar 👍 you are absolutely correct that they should behave the same!

I've opened https://github.com/elastic/elasticsearch-net/pull/2753 to address this and by testing this found a small cancellation bug in the full framework too.

This should be fixed with the next release which should go out soon.

**Comment by Mpdreamz** [comment]
fixed as per #2753
