### ISSUE TITLE
Nest on centos7 error

### ISSUE THREAD

**Issue by CBDlkl** [elastic/elasticsearch-net#2758]
**dotnet core version**
`1.1`

**NEST/Elasticsearch.Net version**:
`5.3.1`

**Elasticsearch version**:
use docker : https://store.docker.com/community/images/sebp/elk 
elk version: `5.4.0`

**Description of the problem including expected versus actual behavior**:
in windows , it's ok.
but，publish to centos7 is error
elasticsearch and asp.net core site on the same server，I use domain name access

error info：
```
Error Message:
 Elasticsearch.Net.UnexpectedElasticsearchClientException : Unknown option
---- System.PlatformNotSupportedException : Unknown option
Stack Trace:
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters)
   at Nest.LowLevelDispatch.IndicesExistsDispatch[T](IRequest`1 p)
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch)
   at HdfCommon.ElasticSearch.ESClientProvider.EnsureIndexWithMapping[T](String indexName, Func`2 customMapping) in /home/gitlab-runner/builds/812034a8/0/likeli/HdfServerApi_Core/HdfCommon/ElasticSearch/ESClientProvider.cs:line 42
   at HdfCommon.ElasticSearch.ESClientProvider..ctor(IOptions`1 options) in /home/gitlab-runner/builds/812034a8/0/likeli/HdfServerApi_Core/HdfCommon/ElasticSearch/ESClientProvider.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at HdfCommon.Logger.ESLoggerProvider..ctor(IServiceProvider serviceProvider, String indexName, FilterLoggerSettings filter) in /home/gitlab-runner/builds/812034a8/0/likeli/HdfServerApi_Core/HdfCommon/Logger/ESLoggerProvider.cs:line 21
   at HdfCommon.Logger.LoggerExtensions.AddESLogger(ILoggerFactory factory, IServiceProvider serviceProvider, String indexName, FilterLoggerSettings filter) in /home/gitlab-runner/builds/812034a8/0/likeli/HdfServerApi_Core/HdfCommon/Logger/LoggerExtensions.cs:line 10
   at HdfApi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in /home/gitlab-runner/builds/812034a8/0/likeli/HdfServerApi_Core/HdfApi/Startup.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder)
   at HdfApiTest.WebTest..ctor() in /home/gitlab-runner/builds/812034a8/0/likeli/HdfServerApi_Core/HdfApiTest/WebTest.cs:line 27
----- Inner Stack Trace -----
   at System.Net.Http.CurlHandler.set_MaxConnectionsPerServer(Int32 value)
   at Elasticsearch.Net.HttpConnection.CreateHttpClientHandler(RequestData requestData)
   at Elasticsearch.Net.HttpConnection.<>c__DisplayClass2_0.<GetClient>b__0(Int32 h)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Elasticsearch.Net.HttpConnection.GetClient(RequestData requestData)
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters)
```

C# core:
```
public class ESClientProvider
    {
        public ESClientProvider(IOptions<ESOptions> options)
        {
            var settings = new ConnectionSettings(new Uri(options.Value.Uri))
                .DefaultIndex("hdf-house")
                .ThrowExceptions();

            if (!String.IsNullOrEmpty(options.Value.UserName) && !String.IsNullOrEmpty(options.Value.Password))
            {
                settings.BasicAuthentication(options.Value.UserName, options.Value.Password);
            }

            Client = new ElasticClient(settings);
            DefaultIndex = options.Value.DefaultIndex;
            EnsureIndexWithMapping<Product>(DefaultIndex);
        }

        public ElasticClient Client { get; private set; }
        public string DefaultIndex { get; private set; }

        public void EnsureIndexWithMapping<T>(string indexName = null, Func<PutMappingDescriptor<T>, PutMappingDescriptor<T>> customMapping = null) where T : class
        {
            if (String.IsNullOrEmpty(indexName)) indexName = DefaultIndex;

            // Map type T to that index
            Client.ConnectionSettings.DefaultIndices.Add(typeof(T), indexName);

            // Does the index exists?
            // Wrong here !!!!!!!!!
            var indexExistsResponse = Client.IndexExists(new IndexExistsRequest(indexName));
            if (!indexExistsResponse.IsValid) throw new InvalidOperationException(indexExistsResponse.DebugInformation);

            // If exists, return
            if (indexExistsResponse.Exists) return;

            // Otherwise create the index and the type mapping
            var createIndexRes = Client.CreateIndex(indexName);
            if (!createIndexRes.IsValid) throw new InvalidOperationException(createIndexRes.DebugInformation);

            var res = Client.Map<T>(m =>
            {
                m.AutoMap().Index(indexName);
                if (customMapping != null) m = customMapping(m);
                return m;
            });

            if (!res.IsValid) throw new InvalidOperationException(res.DebugInformation);
        }
    }
```

**Comment by CBDlkl** [comment]
#2500
this can Solve

**Comment by russcam** [comment]
It looks like the `MaxConnectionsPerServer` property is not supported on centos7; [the client tries to set it and catches a `MissingMethodException`](https://github.com/elastic/elasticsearch-net/blob/5.x/src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs#L134-L144) but it looks like we also need to catch `PlatformNotSupportedException` as well.

You should be able to work around this for the moment by setting `ConnectionLimit(-1)` on `ConnectionSettings`

```c#
 var settings = new ConnectionSettings(new Uri(options.Value.Uri))
                .ConnectionLimit(-1)
                .DefaultIndex("hdf-house")
                .ThrowExceptions();
```

**Comment by CBDlkl** [comment]
@russcam Thank you very much for your help！！

**Comment by russcam** [comment]
No problem @CBDlkl 😄  I've added #2759 to also catch `PlatformNotSupportedException`
