### ISSUE TITLE
Error on successful call to elasticsearch while websockets connection is open

### ISSUE THREAD

**Issue by risogolo** [elastic/elasticsearch-net#2787]
I'm getting error in case of successful http call to elasticsearch while websockets connection is open,
this closes my websockets connection for some reason.

NEST/Elasticsearch.Net 5.4.0
Elasticsearch version 5.4.0

**Steps to reproduce**:
 1. Execute http call to elasticsearch while websockets connection is open

System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Error -4077 ECONNRESET connection reset by peer ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4077 ECONNRESET connection reset by peer

**Comment by Mpdreamz** [comment]
Can you post a bit more in what context you are calling the client methods? Whats the stacktrace from that exception?

**Comment by risogolo** [comment]
This is my call:
` var response = await _client.SearchAsync<Contracts.Configuration>(x => x.Index(_configuration.Index)
                        .Aggregations(q => q.Max(nameof(Contracts.Configuration.VersionId), m => m.Field(f => f.VersionId)))
                        .Query(q => q.QueryString(qs => qs.Query(identifier).Name(nameof(Contracts.Configuration.Identifier)))))
                        .ConfigureAwait(false);`

response = isValid, but I'm getting this error:
`System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Error -4077 ECONNRESET connection reset by peer ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4077 ECONNRESET connection reset by peer
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__60.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TrafficDataProcessor.Middleware.ConfigurationSocketMiddleware.<Receive>d__5.MoveNext() in C:\Projects\Repos\wim-tda-tdp\src\TrafficDataProcessor\Middleware\ConfigurationSocketMiddleware.cs:line 65`

It looks like the HTTP request closing existing TCP connection, it also maybe the bug in aspnetcore library

**Comment by risogolo** [comment]
I have reported this issue to websockets library, I tried a couple of things and seems to be and issue there, sorry for wasting your time

**Comment by Mpdreamz** [comment]
@risogolo can you link me to the ticket??

**Comment by risogolo** [comment]
[https://github.com/aspnet/WebSockets/issues/187](https://github.com/aspnet/WebSockets/issues/187)

**Comment by Mpdreamz** [comment]
Thanks! Happy to hear you have it sorted out :)
