### ISSUE TITLE
NEST Failed to create a new Client

### ISSUE THREAD

**Issue by YannikG** [elastic/elasticsearch-net#2803]
**NEST/Elasticsearch.Net version**:
**Elasticsearch version**: 2.1.0 but also not working on 5.5.0
**NEST version**: Tried with the latest version and also with the 2.5.5 version. But both aren't working.

**Description of the problem including expected versus actual behavior**:
When I try to create a new ElasticsearchClient I always get an Exception. I am not sure why and how to reproduce.
**Exception**: `Could not create an instance of type Nest.IStringFielddata. Type is an interface or abstract class and cannot be instantiated. Path 'fielddata.format', line 1, position 724.`
**Steps to reproduce**:
I am not sure how to reproduce the error. In two of tree projects its working fine with the same Elasticsearch and the same code.
**Code**:
```csharp
 settings = new ConnectionSettings(new Uri(url))
				.MaximumRetries(10)
				.MaximumRetries(10)
				.BasicAuthentication(username, password)
				.RequestTimeout(TimeSpan.FromMinutes(2))
				.OnRequestCompleted(r => logger.LogInformation("Request ok"))
				.ThrowExceptions();
/* Exception -->*/ var Client = new ElasticClient(settings);
```

**Provide `ConnectionSettings`**:
```csharp
settings = new ConnectionSettings(new Uri(url))
				.MaximumRetries(10)
				.MaximumRetries(10)
				.BasicAuthentication(username, password)
				.RequestTimeout(TimeSpan.FromMinutes(2))
				.OnRequestCompleted(r => logger.LogInformation("Request ok"))
				.ThrowExceptions();
```
(But also not working with only the Uri)
**Provide `DebugInformation`**:

```
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT ElasticSearch: create Client: Exception: Elasticsearch.Net.UnexpectedElasticsearchClientException: Could not create an instance of type Nest.IStringFielddata. Type is an interface or abstract class and cannot be instantiated. Path 'fielddata.format', line 1, position 724. ---> Newtonsoft.Json.JsonSerializationException: Could not create an instance of type Nest.IStringFielddata. Type is an interface or abstract class and cannot be instantiated. Path 'fielddata.format', line 1, position 724.
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Linq.JToken.ToObject[T]()
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Nest.PropertyJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in c:\Projects\elastic\net-2\src\Nest\Mapping\Types\PropertyJsonConverter.cs:line 33
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Nest.FromJson.ReadAs[T](JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in c:\Projects\elastic\net-2\src\Nest\CommonAbstractions\SerializationBehavior\GenericJsonConverters\FromJson.cs:line 15
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Nest.ReadAsTypeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in c:\Projects\elastic\net-2\src\Nest\CommonAbstractions\SerializationBehavior\GenericJsonConverters\ReadAsTypeJsonConverter.cs:line 19
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Nest.DynamicTemplatesJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in c:\Projects\elastic\net-2\src\Nest\Mapping\DynamicTemplate\DynamicTemplatesJsonConverter.cs:line 43
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Nest.FromJson.ReadAs[T](JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in c:\Projects\elastic\net-2\src\Nest\CommonAbstractions\SerializationBehavior\GenericJsonConverters\FromJson.cs:line 15
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Nest.ReadAsTypeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in c:\Projects\elastic\net-2\src\Nest\CommonAbstractions\SerializationBehavior\GenericJsonConverters\ReadAsTypeJsonConverter.cs:line 19
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Nest.VerbatimDictionaryKeysJsonConverter`3.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in c:\Projects\elastic\net-2\src\Nest\CommonAbstractions\SerializationBehavior\GenericJsonConverters\VerbatimDictionaryKeysConverter.cs:line 90
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Nest.JsonNetSerializer.Deserialize[T](Stream stream) in c:\Projects\elastic\net-2\src\Nest\CommonAbstractions\SerializationBehavior\JsonNetSerializer.cs:line 125
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Elasticsearch.Net.ResponseBuilder`1.SetBody(ElasticsearchResponse`1 response, Stream stream) in c:\Projects\elastic\net-2\src\Elasticsearch.Net\Transport\Pipeline\ResponseBuilder.cs:line 76
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Elasticsearch.Net.ResponseBuilder`1.ToResponse() in c:\Projects\elastic\net-2\src\Elasticsearch.Net\Transport\Pipeline\ResponseBuilder.cs:line 33
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in c:\Projects\elastic\net-2\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 83
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData) in c:\Projects\elastic\net-2\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 418
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in c:\Projects\elastic\net-2\src\Elasticsearch.Net\Transport\Transport.cs:line 69
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT --- End of inner exception stack trace ---
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in c:\Projects\elastic\net-2\src\Elasticsearch.Net\Transport\Transport.cs:line 89
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Nest.LowLevelDispatch.ClusterStateDispatch[T](IRequest`1 p) in c:\Projects\elastic\net-2\src\Nest\_Generated\_LowLevelDispatch.generated.cs:line 613
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch) in c:\Projects\elastic\net-2\src\Nest\ElasticClient.cs:line 56
2017-07-12 14:34:30 [APP/PROC/WEB/0] OUT at App.Source.Connection.Elastic.ElsCore.getClient(String url, String username, String password) in D:\Git\SomeApp\SomeApp\App\Source\Connection\Elastic\ElsCore.cs:line 54
´´´

**Comment by Mpdreamz** [comment]
Thanks for reporting this, is any of your projects using the `SniffingConnectionPool` ?

**Comment by Mpdreamz** [comment]
What in `App.Source.Connection.Elastic.ElsCore.getClient` calls the ClusterState?

Can you show us the complete source for that method?

**Comment by Mpdreamz** [comment]
2Closing this as can not reproduce, feel free to reply with the source for `App.Source.Connection.Elastic.ElsCore.getClient` @YannikG and we'll reopen this gladly :smile:

**Comment by YannikG** [comment]
I'm sorry ... I had Vacation and was not able to reply to you.

```csharp
public ElasticClient getClient(string url = "", string username = "", string password = "")  // Default = Localhsot
        {
            //logger.LogInformation("Url: " + url + " Username: " + username + " Password: " + password);
            try
            {
                if (_Client == null)
                {
                    ConnectionSettings settings = null;
                    if (string.IsNullOrEmpty(url))
                    {
                        logger.LogInformation("ElasticSearch: using local installed node");
                        url = "http://localhost:9200";
                    }
                    else
                    {
                        logger.LogInformation("ElasticSearch: Single node mode");
                        settings = new ConnectionSettings(new Uri(url)); 
                    }

                    if (settings != null)
                    {
                        settings.MaximumRetries(10)
                                .MaximumRetries(10)
                                .BasicAuthentication(username, password)
                                .RequestTimeout(TimeSpan.FromMinutes(2))
                                .OnRequestCompleted(r => logger.LogInformation("Request ok"))
                                .ThrowExceptions();
                    }

                    _Client = new ElasticClient(settings);
                    if (_Client.ClusterState() == null)
                    {
                        throw new Exception("Cannot connect to the Cluster!");
                    }
                    try
                    {
                        _Client.Ping();
                    }
                    catch (Exception ex)
                    {
                        logger.LogError("ElasticSearch: ping Client Exception: " + ex);
                        return null;
                    }
                    logger.LogInformation("ElasticSearch: create Client OK");
                    return _Client;
                }
                else
                    return _Client;
            }
            catch (Exception e)
            {
                logger.LogError("ElasticSearch: create Client: Exception: " + e);
                return null;
            }
        }
```
