### ISSUE TITLE
Sporadic timeouts while sending queries to ElasticSearch Cluster.

### ISSUE THREAD

**Issue by tobs1701** [elastic/elasticsearch-net#2808]
**NEST/Elasticsearch.Net version**:'
1.4.3 NEST

**Elasticsearch version**:
1.6.2

**Description of the problem including expected versus actual behavior**:
On rare occasions, NEST will randomly report a timeout with searches sent to the ElasticSearch cluster. These are simple searches (e.g. 'bob').

We have three nodes in the target cluster. There are no significant CPU (about 16%, tops) or memory spikes when the timeouts occur. Connection settings and stack trace are below.

**Steps to reproduce**:
 These occur sporadically and I haven't found anything that reproduces them consistently. We're using `ElasticClient.Raw.Search<T>` to query the cluster.

I know these are old versions of ES and the ES client; however, we're not likely to want to upgrade significantly at this time. I've googled and searched the issues but found nothing similar enough to point me to a clear cause. If you have any insight, it would be appreciated.

**Provide `ConnectionSettings` (if relevant)**:
`For<IElasticClient>().Singleton().Use(() => new ElasticClient(new ConnectionSettings(new Uri(Settings.Default.ElasticSearchBaseUri))
					.SetDefaultIndex(Settings.Default.ElasticSearchIndexName)
					.SetTimeout(10000)));`
(We're using StructureMap for an IOC container.)

**Provide `DebugInformation` (if relevant)**:
Here's the stack trace:

`System.Net.WebException: The operation has timed out
at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.ReturnStreamOrVoidResponse[T](TransportRequestState`1 requestState, ElasticsearchResponse`1 streamResponse) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\RequestHandlers\RequestHandler.cs:line 76
at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.CoordinateRequest[T](TransportRequestState`1 requestState, Int32 maxRetries, Int32 retried, Boolean& aliveResponse) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\RequestHandlers\RequestHandler.cs:line 131
at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.DoRequest[T](TransportRequestState`1 requestState) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\RequestHandlers\RequestHandler.cs:line 177
at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.Request[T](TransportRequestState`1 requestState, Object data) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\RequestHandlers\RequestHandler.cs:line 34
at Elasticsearch.Net.Connection.Transport.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:line 343 at ... %our calling code%`

**Comment by russcam** [comment]
Hey @tobs1701 

[NEST 1.x is no longer actively supported](https://github.com/elastic/elasticsearch-net#compatibility-matrix) since Elasticsearch 1.x is no longer supported. I appreciate that this isn't what you'd like to hear, but we are focusing our efforts on continuing to improve 2.x, 5.x and the next major release.
