### ISSUE TITLE
GetRepository returning error when using Azure Repositories

### ISSUE THREAD

**Issue by yatiac** [elastic/elasticsearch-net#2816]
**NEST/Elasticsearch.Net version**: 5.5.0

**Elasticsearch version**: 5.5.0

**Description of the problem including expected versus actual behavior**:

Elasticsearch server using Azure Repositories.

**Expected**: Executing client.GetRepository() should return all repositories on the server.
**Actual**: clientGetRepository() is returning:

`Cannot create an instance of Nest.AzureRepository because it has no constructor taking 1 arguments`

**Steps to reproduce**:
 1. Create an azure repository
 2. Create a `GetRepositoryRequest ` with the repository name as parameter
 3. Execute `client.GetRepository()` 

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

StackTrace:
```
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[T](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.SnapshotGetRepository[T](String repository, Func`2 requestParameters)
   at Nest.LowLevelDispatch.SnapshotGetRepositoryDispatch[T](IRequest`1 p)
   at Nest.ElasticClient.<GetRepository>b__446_0(IGetRepositoryRequest p, PostData`1 d)
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch)
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 dispatch)
   at Nest.ElasticClient.GetRepository(IGetRepositoryRequest request)
```

**Describe the feature**:

**Comment by Mpdreamz** [comment]
This looks like a bug, we'll look into fixing this for the next release. Thanks for letting us know @yatiac 👍

**Comment by Mpdreamz** [comment]
Thanks again for reporting @yatiac, this should be fixed with out next `2.x` `5.x` and `6.x` releases. 

Apologies for leaving this ticket linger for so long.

**Comment by yatiac** [comment]
no worries, thank you anyways, do you have any ETA for that release? @Mpdreamz
