### ISSUE TITLE
Sniffing Doesn't Works, Error: Maximum timeout reached while retrying request

### ISSUE THREAD

**Issue by dmalchinsky** [elastic/elasticsearch-net#2824]
Hello i'm migratting to Elastic 5.4.3  & Elastic.Net 5.x
I have an error when i try to connecto with sniffing i got next error

```
Unsuccessful low level call on GET: /my_index/mi_type/1
# Audit trail of this API call:
 - [1] SniffOnStartup: Took: 00:00:01.7810000
 - [2] SniffSuccess: Node: http://ordx-XXXX:XXXX/ Took: 00:00:01.7760000
 - [3] PingFailure: Node: http://10.XX.1XX.XXX:9200/ Exception: PipelineException Took: 00:00:21.0030000
 - [4] SniffOnFail: Took: 00:03:09.0120000
 - [5] SniffFailure: Node: http://10.XX.1XX.XXX:18246/ Exception: PipelineException Took: 00:00:21.0070000
 - [6] SniffFailure: Node: http://10.XX.XXX.4:18246/ Exception: PipelineException Took: 00:00:21
 - [7] SniffFailure: Node: http://10.XX.XXX.16:18246/ Exception: PipelineException Took: 00:00:21.0060000
 - [8] SniffFailure: Node: http://10.XX.XXX.28:9200/ Exception: PipelineException Took: 00:00:20.9950000
 - [9] SniffFailure: Node: http://10.XX.XXX.1:18246/ Exception: PipelineException Took: 00:00:20.9990000
 - [10] SniffFailure: Node: http://10.XX.XXX.7:9200/ Exception: PipelineException Took: 00:00:21.0050000
 - [11] SniffFailure: Node: http://10.XX.XXX.19:9200/ Exception: PipelineException Took: 00:00:20.9950000
 - [12] SniffFailure: Node: http://10.XX.XXX.25:18246/ Exception: PipelineException Took: 00:00:20.9970000
 - [13] SniffFailure: Node: http://10.XX.1XX.XXX:9200/ Exception: PipelineException Took: 00:00:21.0070000
 - [14] MaxTimeoutReached: Took: -736548.14:17:52.2344510
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: Maximum timeout reached while retrying request ---> System.AggregateException: One or more errors occurred. ---> Elasticsearch.Net.PipelineException: Failed sniffing cluster state. ---> System.AggregateException: One or more errors occurred. ---> Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   at Elasticsearch.Net.RequestPipeline.Sniff()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.RequestPipeline.Sniff()
   at Elasticsearch.Net.RequestPipeline.SniffOnConnectionFailure()
   at Elasticsearch.Net.Transport`1.Ping(IRequestPipeline pipeline, Node node)
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
# Audit exception in step 3 PingFailure:
Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   at Elasticsearch.Net.RequestPipeline.Ping(Node node)
# Audit exception in step 5 SniffFailure:
Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   at Elasticsearch.Net.RequestPipeline.Sniff()
# Audit exception in step 6 SniffFailure:
Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   at Elasticsearch.Net.RequestPipeline.Sniff()
# Audit exception in step 7 SniffFailure:
Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   at Elasticsearch.Net.RequestPipeline.Sniff()
# Audit exception in step 8 SniffFailure:
Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   at Elasticsearch.Net.RequestPipeline.Sniff()
# Audit exception in step 9 SniffFailure:
Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   at Elasticsearch.Net.RequestPipeline.Sniff()
# Audit exception in step 10 SniffFailure:
Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   at Elasticsearch.Net.RequestPipeline.Sniff()
# Audit exception in step 11 SniffFailure:
Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   at Elasticsearch.Net.RequestPipeline.Sniff()
# Audit exception in step 12 SniffFailure:
Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   at Elasticsearch.Net.RequestPipeline.Sniff()
# Audit exception in step 13 SniffFailure:
Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   at Elasticsearch.Net.RequestPipeline.Sniff()
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>

```

My setting is: /_nodes/_all/settings?flat_settings

```
{
    "_nodes": {
        "total": 9,
        "successful": 9,
        "failed": 0
    },
    "cluster_name": "CLUSTERNAMEXXXX",
    "nodes": {
        "WdPXNMIYXXXXXX_m2bJvYw": {
            "name": "NAME",
            "transport_address": "10.XXX.XXX.XX:XXXX",
            "host": "10.XXX.XXX.XX",
            "ip": "10.XXX.XXX.XX",
            "version": "5.4.3",
            "build_hash": "XXX",
            "roles": [
                "master"
            ],
            "attributes": {
                "phy_host": "XXXX"
            },
            "settings": {
                "action.destructive_requires_name": "true",
                "bootstrap.memory_lock": "true",
                "bootstrap.system_call_filter": "false",
                "client.type": "node",
                "cloud.aws.protocol": "https",
                "cloud.aws.proxy.host": "10.XX.XX.XX",
                "cloud.aws.proxy.port": "8080",
                "cluster.name": "XXXXXX",
                "cluster.routing.allocation.awareness.attributes": "phy_host",
                "default.path.conf": "/etc/elasticsearch",
                "default.path.data": "/data0/elasticsearch/XXXXXX",
                "default.path.logs": "/var/log/elasticsearch",
                "discovery.zen.minimum_master_nodes": "2",
                "discovery.zen.ping.unicast.hosts.0": "NAME.XXXXX.com:XXXXX",
                "discovery.zen.ping.unicast.hosts.1": "NAME.XXXXX.com:XXXXX",
                "discovery.zen.ping.unicast.hosts.2": "NAME.XXXXX.com:XXXXX",
                "discovery.zen.ping_timeout": "5s",
                "http.cors.allow-credentials": "false",
                "http.cors.allow-headers": "X-Requested-With, Content-Type, Content-Length",
                "http.cors.allow-methods": "OPTIONS, HEAD, GET, POST, PUT, DELETE",
                "http.cors.allow-origin": "/https?:\\/\\/.+(:[0-9]+)?/",
                "http.cors.enabled": "true",
                "http.cors.max-age": "1728000",
                "http.port": "18246",
                "http.type.default": "netty4",
                "network.host": "0.0.0.0",
                "node.attr.phy_host": "NAME",
                "node.data": "false",
                "node.ingest": "false",
                "node.master": "true",
                "node.max_local_storage_nodes": "1",
                "node.name": "NAME",
                "path.data.0": "/data0/elasticsearch/DATA",
                "path.home": "/opt/elasticsearch",
                "path.logs": "/var/log/elasticsearch",
                "path.repo": "/backups",
                "script.engine.expression.inline": "true",
                "script.engine.mustache.inline": "true",
                "script.engine.painless.inline": "true",
                "script.file": "true",
                "script.inline": "false",
                "script.stored": "false",
                "transport.tcp.port": "38246",
                "transport.type.default": "netty4"
            }
        },
		{.......}
    }
}
```

**Comment by dmalchinsky** [comment]
Hello, @Mpdreamz please, Can you help me ? Thanks!

**Comment by Mpdreamz** [comment]
Your sniff to an external DNS yields private IP numbers `10.x.x.x` which the client might not be able to reach.

In the past you could set `http.publish_host` on each node to advertise a public IP/DNS but this currently has an open bug in elasticsearch itself:

https://github.com/elastic/elasticsearch/issues/22029#issuecomment-299440518

**Comment by dmalchinsky** [comment]
Thanks for your answer. I'll follow that issue, thanks!
