### ISSUE TITLE
Unexpected exception using GetWatch()

### ISSUE THREAD

**Issue by CiprianPintilie** [elastic/elasticsearch-net#2836]
Hello,

When I try to get a watch using NEST (5.5.0), I get an exception with a "must" object array in the watcher input query like `"query": {"bool": {"must": [{}, {}...]}} ` :

> Elasticsearch.Net.UnexpectedElasticsearchClientException : 'Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path 'watch.input.search.request.body.query.bool.must[0].match.Type', line 1, position 500.'

Same kind of exception with a single "must" object like `"query": {"bool": {"must": {}}} ` :  

> Elasticsearch.Net.UnexpectedElasticsearchClientException : 'Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Nest.QueryContainer]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'watch.input.search.request.body.query.bool.must.match', line 1, position 477.'

If I try to get the same watch using a `"match_all": {}` query in the input, there is no error and I can get it.

I'm using a minimal code for testing, inside a .Net Standard 1.6 project (NEST referenced with NuGet):

```
private readonly ElasticClient _client;

        public WatchesRepository()
        {
            var settings = new ConnectionSettings(new Uri("https://xxx"));
            settings.BasicAuthentication("xxx", "xxx");
            _client = new ElasticClient(settings);
        }

        public Watch GetWatch(string watchName)
        {
            var watchResponse = _client.GetWatch(watchName);
            return watchResponse.Watch;
        }
```
Is there a documantation for the xPack (especially for Watcher) part of the NEST package ?

**Comment by russcam** [comment]
Hey @CiprianPintilie 

there isn't any specific documentation for Watcher/Alerting with NEST, but there is the [Watcher API documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/watcher-api.html), [Alerting documentation](https://www.elastic.co/guide/en/x-pack/current/xpack-alerting.html) as part of the X-Pack documentation, as well as [integration tests for the Watcher APIs in NEST](https://github.com/elastic/elasticsearch-net/tree/5.x/src/Tests/XPack/Watcher). We plan to include some documentation for it in future, probably generated from the integration tests.

Would you be able to provide the complete JSON for a watch that is failing to be deserialized? From the example and exception thrown, there is an error attempting to deserialize the match query in the bool query must clause. This may be because the Watch was created outside of NEST, using a shorthand query form that is valid for Elasticsearch, but that NEST does not know how to deserialize, as NEST always sends the long form of queries. If you could provide the full JSON for the watch, I can investigate.

**Comment by CiprianPintilie** [comment]
Thank you @russcam  for the links,

I will create the same watch using NEST, and see the difference.

Here's the complete JSON of the watch (created outside NEST): 

```
{
    "trigger": {
        "schedule": {
            "interval": "5m"
        }
    },
    "input": {
        "search": {
            "request": {
                "search_type": "query_then_fetch",
                "indices": [
                    "ComponentStatus"
                ],
                "types": [],
                "body": {
                    "size": 0,
                    "query": {
                        "bool": {
                            "must": [
                                {
                                    "match": {
                                        "Type": "Subscription"
                                    }
                                },
                                {
                                    "range": {
                                        "DateTime": {
                                            "from": "now-1d",
                                            "to": "now"
                                        }
                                    }
                                },
                                {
                                    "range": {
                                        "Metrics.ActiveMessageCount": {
                                            "from": 100
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "aggs": {
                        "GroupByComponentName": {
                            "terms": {
                                "field": "ComponentName",
                                "size": 1000
                            },
                            "aggs": {
                                "avg_grade": {
                                    "avg": {
                                        "field": "Metrics.ActiveMessageCount"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "condition": {
        "always": {}
    },
    "throttle_period_in_millis": 900000,
    "actions": {
        "email_notification": {
            "email": {
                "account": "account",
                "profile": "standard",
                "to": [
                    "cptesting@outlook.fr"
                ],
                "subject": "Subscription message exceeded !",
                "body": {
                    "text": "Subscriptions have too much message :  {{#ctx.payload.aggregations.GroupByComponentName.buckets}} * {{key}} : {{avg_grade.value}} {{/ctx.payload.aggregations.GroupByComponentName.buckets}}"
                }
            }
        }
    }
}
```

**Comment by tishion** [comment]
I think there are more bugs in Watcher related methods. For example:
this is a watcher returned by a new installed Elasticsearch+X-pack:

`    
"took": 16,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "failed": 0
    },
    "hits": {
        "total": 4,
        "max_score": 1.0,
        "hits": [
            {
                "_index": ".watches",
                "_type": "watch",
                "_id": "6UUtieAvRWSsDi2uyyZD_w_logstash_version_mismatch",
                "_score": 1.0,
                "_source": {
                    "trigger": {
                        "schedule": {
                            "interval": "1m"
                        }
                    },
                    "input": {
                        "chain": {
                            "inputs": [
                                {
                                    "check": {
                                        "search": {
                                            "request": {
                                                "search_type": "query_then_fetch",
                                                "indices": [
                                                    ".monitoring-logstash-*"
                                                ],
                                                "types": [],
                                                "body": {
                                                    "size": 0,
                                                    "query": {
                                                        "bool": {
                                                            "filter": [
                                                                {
                                                                    "term": {
                                                                        "cluster_uuid": "{{ctx.metadata.xpack.cluster_uuid}}"
                                                                    }
                                                                },
                                                                {
                                                                    "range": {
                                                                        "timestamp": {
                                                                            "gte": "now-2m"
                                                                        }
                                                                    }
                                                                },
                                                                {
                                                                    "bool": {
                                                                        "should": [
                                                                            {
                                                                                "term": {
                                                                                    "_type": "logstash_stats"
                                                                                }
                                                                            },
                                                                            {
                                                                                "term": {
                                                                                    "type": "logstash_stats"
`

when i use search API to retrieve this i got this error:
Elasticsearch.Net.UnexpectedElasticsearchClientException occurred
  HResult=0x80131500
  Message=Unexpected state: ObjectStart. Path 'hits.hits[0]._source.input.chain.inputs[0]', line 1, position 304.
  Source=Elasticsearch.Net
  StackTrace:
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Transport\Transport.cs:line 89
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[T](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\ElasticLowLevelClient.cs:line 61
   at Elasticsearch.Net.ElasticLowLevelClient.Search[T](String index, PostData`1 body, Func`2 requestParameters) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 7295
   at Nest.LowLevelDispatch.SearchDispatch[T](IRequest`1 p, PostData`1 body) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\_Generated\_LowLevelDispatch.generated.cs:line 2848
   at Nest.ElasticClient.<>c__DisplayClass568_0`2.<Search>b__0(ISearchRequest p, PostData`1 d) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 74
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\ElasticClient.cs:line 57
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 dispatch) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\ElasticClient.cs:line 47
   at Nest.ElasticClient.Search[T,TResult](ISearchRequest request) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 72
   at Nest.ElasticClient.Search[T](ISearchRequest request) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 66
   at Nest.ElasticClient.Search[T,TResult](Func`2 selector) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 62
   at Nest.ElasticClient.Search[T](Func`2 selector) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 56
   at WatcherManagement.WatcherClient.ExportWatchers() in C:\Users\STian\Documents\Visual Studio 2017\Projects\WatcherManagement\WatcherManagement\WatcherClient.cs:line 39
   at WatcherManagementTest.Program.Main(String[] args) in C:\Users\STian\Documents\Visual Studio 2017\Projects\WatcherManagement\WatcherManagementTest\Program.cs:line 16

Inner Exception 1:
JsonReaderException: Unexpected state: ObjectStart. Path 'hits.hits[0]._source.input.chain.inputs[0]', line 1, position 304.

**Comment by tishion** [comment]
And one more example:
````
Elasticsearch.Net.UnexpectedElasticsearchClientException occurred
  HResult=0x80131500
  Message=Unexpected initial token 'Integer' when populating object. Expected JSON object or array. Path 'hits.hits[0]._source.input.search.request.body.query.bool.must[0].term.sc-status', line 1, position 408.
  Source=Elasticsearch.Net
  StackTrace:
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Transport\Transport.cs:line 89
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[T](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\ElasticLowLevelClient.cs:line 61
   at Elasticsearch.Net.ElasticLowLevelClient.Search[T](String index, PostData`1 body, Func`2 requestParameters) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 7295
   at Nest.LowLevelDispatch.SearchDispatch[T](IRequest`1 p, PostData`1 body) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\_Generated\_LowLevelDispatch.generated.cs:line 2848
   at Nest.ElasticClient.<>c__DisplayClass568_0`2.<Search>b__0(ISearchRequest p, PostData`1 d) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 74
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\ElasticClient.cs:line 57
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 dispatch) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\ElasticClient.cs:line 47
   at Nest.ElasticClient.Search[T,TResult](ISearchRequest request) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 72
   at Nest.ElasticClient.Search[T](ISearchRequest request) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 66
   at Nest.ElasticClient.Search[T,TResult](Func`2 selector) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 62
   at Nest.ElasticClient.Search[T](Func`2 selector) in C:\Dev\BitTitanVSTS\DevOps\bittitan-elasticsearch-net\src\Nest\Search\Search\ElasticClient-Search.cs:line 56
   at WatcherManagement.WatcherClient.ExportWatchers() in C:\Users\STian\Documents\Visual Studio 2017\Projects\WatcherManagement\WatcherManagement\WatcherClient.cs:line 40
   at WatcherManagementTest.Program.Main(String[] args) in C:\Users\STian\Documents\Visual Studio 2017\Projects\WatcherManagement\WatcherManagementTest\Program.cs:line 16

Inner Exception 1:
JsonSerializationException: Unexpected initial token 'Integer' when populating object. Expected JSON object or array. Path 'hits.hits[0]._source.input.search.request.body.query.bool.must[0].term.sc-status', line 1, position 408.
````

The watch:
```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 1,
    "hits": [
      {
        "_index": ".watches",
        "_type": "watch",
        "_id": "iis_503_detection",
        "_score": 1,
        "_source": {
          "trigger": {
            "schedule": {
              "interval": "10m"
            }
          },
          "input": {
            "search": {
              "request": {
                "search_type": "query_then_fetch",
                "indices": [
                  "iis-*"
                ],
                "types": [],
                "body": {
                  "size": 10,
                  "query": {
                    "bool": {
                      "must": [
                        {
                          "term": {
                            "sc-status": 503
                          }
                        },
```

**Comment by russcam** [comment]
@tishion Could you post the full examples? From the pieces you have posted, the short form of `term` queries is not currently supported by NEST. For example,

```
"term": {
    "cluster_uuid": "{{ctx.metadata.xpack.cluster_uuid}}"
}
```

will throw an exception upon deserialization. But 

```
"term": {
    "cluster_uuid": {
        "value": "{{ctx.metadata.xpack.cluster_uuid}}"
    }
}
```

will be fine - A watch created with NEST should always be deserializable by NEST, but one created outside of NEST may not be.

@elastic/microsoft I think we should consider supporting deserialization of the short form of queries.

**Comment by tishion** [comment]
@russcam  i think your explanation makes sense. No wonder I got this exception. All the watches I queried are not from NEST. 

````
    "term": {
        "sc-status": 503
    }
````
So this one will throw exception as well.  this is the second exception i post above.
so we need to find some workarounds.

**Comment by russcam** [comment]
@CiprianPintilie @tishion I'm closing this in favour of #2855 as this also relates to percolated queries and other scenarios where query JSON may be deserialized into a C# Query type.

> so we need to find some workarounds.

@tishion the workaround for the moment is to use the long form of queries, which will deserialize correctly.

**Comment by tishion** [comment]
@russcam   Thanks!  this is not big deal for us. we just choose Lowlevel client to read and write the watches now. we defined a  new watcher class as a replacement
````
    /// <summary>
    /// 
    /// </summary>
    [JsonObject]
    public class Watcher
    {
        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("trigger")]
        public JToken Trigger { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("input")]
        public JToken Input { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("condition")]
        public JToken Condition { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("transform")]
        public JToken Transform { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("actions")]
        public JToken Actions { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("metadata")]
        public IReadOnlyDictionary<string, object> Metadata { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("throttle_period")]
        public string ThrottlePeriod { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("_status")]
        public WatchStatus Status { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string Id;
    }
````

And us it like this:
```
client.LowLevel.SearchGetAsync<SearchResponse<Watcher>>(WatcherClient.INDEX_NAME,
                    x => x.AddQueryString("size", 0))
```

So far it works well, but hope you can fix this ASAP and publish a new release. :)

**Comment by russcam** [comment]
Glad you have another way to resolve for the time being, @tishion 👍 Will look to fix for the next release.
