### ISSUE TITLE
Call to GetIndicesPointingToAlias causes UnexpectedElasticsearchClientException

### ISSUE THREAD

**Issue by rosrosros** [elastic/elasticsearch-net#2884]
**NEST/Elasticsearch.Net version**:
5.5.0 
**Elasticsearch version**:
5.6.3 - cloud
**Description of the problem including expected versus actual behavior**:

When calling `Nest.IndicesPointingToAliasExtensions.GetIndicesPointingToAlias` we sometime get this error.

My guess is that it's the ES cluster that returns a `error.root_cause` instead of a `Dictionary<AliasDefinition>`  - and that this is not handled by NEST

Stack trace

```
Elasticsearch.Net.UnexpectedElasticsearchClientException
Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.Dictionary`2[System.String,Nest.AliasDefinition]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'error.root_cause', line 1, position 24.

at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Nest.GetAliasResponseConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Nest.JsonNetSerializer.Deserialize[T](Stream stream)
   at Elasticsearch.Net.ResponseBuilder`1.SetBody(ElasticsearchResponse`1 response, Stream stream)
   at Elasticsearch.Net.ResponseBuilder`1.ToResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[T](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliasForAll[T](String name, Func`2 requestParameters)
   at Nest.LowLevelDispatch.IndicesGetAliasDispatch[T](IRequest`1 p)
   at Nest.ElasticClient.<GetAlias>b__278_1(IGetAliasRequest p, PostData`1 d)
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch)
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 dispatch)
   at Nest.ElasticClient.GetAlias(IGetAliasRequest request)
   at Nest.ElasticClient.GetAlias(Func`2 selector)
   at Nest.IndicesPointingToAliasExtensions.GetIndicesPointingToAlias(IElasticClient client, Names alias)
   at [CUSTOM CODE]

```

**Comment by russcam** [comment]
@rosrosros do you have the JSON response that is returned from Elasticsearch when you get this error?

**Comment by rosrosros** [comment]
@russcam 
No unfortunately not - I would expect et to be in the ES log, but we use cloud.elastic.co and the log access there is quite limited (to say the least)

Is there a way that I can capture the actual JSON response when I get the exception?

**Comment by russcam** [comment]
Yes, probably the easiest way would be to [execute the request with Fiddler running](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/logging-with-fiddler.html)

**Comment by rosrosros** [comment]
@russcam 
Been trying all day - but cannot provoke the error in development environment. 

Any other tips?

**Comment by rosrosros** [comment]
@russcam 
Finally I managed to reproduce the error with Fiddler attached

This is what I see in Fiddler

Call to `/_alias/cars`  - this is expected to return a list of car-indexes 
But instead I get this response:

```
{
   "error":{
      "root_cause":[
         {
            "type":"index_not_found_exception",
            "reason":"no such index",
            "resource.type":"index_or_alias",
            "resource.id":"bikes_2017-11-02_15-17-08",
            "index_uuid":"_na_",
            "index":"bikes_2017-11-02_15-17-08"
         }
      ],
      "type":"index_not_found_exception",
      "reason":"no such index",
      "resource.type":"index_or_alias",
      "resource.id":"bikes_2017-11-02_15-17-08",
      "index_uuid":"_na_",
      "index":"bikes_2017-11-02_15-17-08"
   },
   "status":404
}
```

Please note that the index not found has is named "bike..." and **has nothing to do with the cars alias**.

**Comment by russcam** [comment]
Thanks @rosrosros for the detailed information. It looks like [`IGetAliasResponse` expects `error` to be a string](https://github.com/elastic/elasticsearch-net/blob/b8eee167d203a88465efd91c6e4cc6dd74f3828e/src/Nest/Indices/AliasManagement/GetAlias/GetAliasResponse.cs#L19-L19).

Will dig into and fix for the next version

**Comment by rosrosros** [comment]
That sounds great @russcam 

Is there a timeframe for the next release?

Thanks

**Comment by russcam** [comment]
We're concentrated on getting the client ready for a 6.0 GA release right now, but this will need to be addressed as part of that. A 5.x release will be soon (weeks) though.

In the meantime, once a fix has been merged into 5.x, [you can use a CI build (MyGet nuget package) until the nuget package goes out](https://www.myget.org/feed/elasticsearch-net/package/nuget/NEST), if that works for you.

**Comment by Mpdreamz** [comment]
The fact that `error` can be an object as well as a string is handled in the `master` branch targeting `6.x` this still needs a backport.
