### ISSUE TITLE
If you use a custom contract resolver be sure to subclass from ElasticContractResolver

### ISSUE THREAD

**Issue by DavidRouyer** [elastic/elasticsearch-net#2889]
**NEST/Elasticsearch.Net version**: 5.5.0

**Elasticsearch version**: 5.6.3

**.NET Core version**: 2.0.0

**Description of the problem including expected versus actual behavior**:
I'm new to Elasticsearch.NET, and I followed the tutorial. I have something like that:
```
var connectionPool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
var connection = new HttpConnection();
var settings = new ConnectionSettings(connectionPool, connection)
    .DefaultIndex("creators")
    .InferMappingFor<Creator>(i => i
        .TypeName("creator")
        .IndexName("creators")
    );

var elasticClient = new ElasticClient(settings);

var searchRequest = new SearchRequest
{
    From = skip,
    Size = take
};

var response = elasticClient.Search<Creator>(searchRequest);
```

I just have a simple model:
```
public class Creator
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public string HumanName { get; set; }
}
```

And I can't get rid of the Error: System.Exception: If you use a custom contract resolver be sure to subclass from ElasticContractResolver

**Steps to reproduce**:
 1. Copy/paste the code
 2. Execute it
 3. It should throw the Exception

**Provide `DebugInformation` (if relevant)**:
```
System.Exception: If you use a custom contract resolver be sure to subclass from ElasticContractResolver
   at Nest.JsonExtensions.GetConnectionSettings(JsonSerializer serializer) in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\CommonAbstractions\Extensions\JsonExtensions.cs:line 17
   at Nest.VerbatimDictionaryKeysJsonConverter`2.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer) in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\CommonAbstractions\SerializationBehavior\GenericJsonConverters\VerbatimDictionaryKeysConverter.cs:line 186
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.<WriteResponseBodyAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

**Comment by russcam** [comment]
This is happening because one of the types that you are attempting to serialize with the ASP,NET Core MVC JsonFormatter has a `JsonConverter` attribute applied to use a specialized JsonConverter, `VerbatimDictionaryKeysJsonConverter<TKey,TValue>` in this case. This converter needs access to `ConnectionSettings` from NEST as it performs special handling for certain types based on settings therein.

You should be able to 

- pass an instance of `ElasticContractResolver` (I'd recommend creating a singleton and reusing as it makes heavy use of caching) to the JSON.NET serializer used by the MVC framework 

or 
- write a formatter that uses the NEST serializer for JSON serialization.

**Comment by DavidRouyer** [comment]
Thank you for your help!

**Comment by DavidRouyer** [comment]
Could you please explain why I have to configure it globally (intead of using the ElasticClient configuration)? I have my own ContractResolver and I don't want to mess up my configuration.

Could you please write a formatter example or point me to one?

**Comment by russcam** [comment]
> I have my own ContractResolver and I don't want to mess up my configuration.

What you may need is to have a composite ContractResolver; for types in the `Nest` assembly, use `ElasticContractResolver`, for anything else use your own ContractResolver. The composite ContractResolver encapsulates this logic.

**Comment by DavidRouyer** [comment]
Okay, it looks like the ContractResolver can be configured per controller and per method, so I did something like:
`return Ok(JsonConvert.SerializeObject(results, new JsonSerializerSettings() {
                ContractResolver = new ElasticContractResolver(connectionSettings, new List<Func<Type, JsonConverter>>())
}));`

Thanks!
