### ISSUE TITLE
MatchPhraseQuery generates incorrect DSL using 'type'

### ISSUE THREAD

**Issue by afederici75** [elastic/elasticsearch-net#3007]
**NEST/Elasticsearch.Net version**: 5 and 5.6

**Elasticsearch version**: 6

**Description of the problem including expected versus actual behavior**:
When I try to execute a MatchPhraseQuery the DSL that gets generated incorrectly tries to set the 'type' value and ES reports that as non supported.

**Steps to reproduce**:
 1.Create a MatchPhraseQuery and only provide a value for 'Query'
 2.Execute the search

**Provide `DebugInformation` (if relevant)**:

# FailureReason: BadResponse while attempting POST on http://localhost:9400/r6_clean_2012/PersonDocument/_search
# Audit trail of this API call:
 - [1] BadResponse: Node: http://localhost:9400/ Took: 00:00:00.1714700
# ServerError: ServerError: 400Type: parsing_exception Reason: "[match] query does not support [type]"
# Request:
{"from":0,"size":10,"sort":[{"_doc":{"order":"asc"}}],"_source":{"includes":["*"],"excludes":[]},"query":{"bool":{"must":[{"nested":{"query":{"match":{"Aliases.Name.Last":{"query":"xxx","type":"phrase"}}},"path":"Aliases"}}]}}}
# Response:
{"error":{"root_cause":[{"type":"parsing_exception","reason":"[match] query does not support [type]","line":1,"col":194}],"type":"parsing_exception","reason":"[match] query does not support [type]","line":1,"col":194},"status":400}
# Exception:
Elasticsearch.Net.ElasticsearchClientException: Could not complete the request to Elasticsearch.
   at Elasticsearch.Net.RequestPipeline.BadResponse[TReturn](ElasticsearchResponse`1& response, RequestData data, List`1 pipelineExceptions) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 501
   at Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext() in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Transport\Transport.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nest.ElasticClient.<Nest-IHighLevelToLowLevelDispatcher-DispatchAsync>d__261`4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CODY.Elasticsearch.Repositories.ElasticsearchSearchableRepository`1.<Search>d__1.MoveNext() in C:\CODYDev\Libs\CODY.Elasticsearch\CODY.Elasticsearch\Repositories\Base\ElasticsearchSearchableRepository.cs:line 29

**Comment by Mpdreamz** [comment]
Hi you need to use `NEST 6.0.0-rc1` to talk to `Elasticsearch 6.x`.
