### ISSUE TITLE
UnexpectedElasticsearchClientException: The request was canceled

### ISSUE THREAD

**Issue by w-bonelli** [elastic/elasticsearch-net#3087]
**NEST/Elasticsearch.Net version**: 6.0.0

**Elasticsearch version**: 6.1.3

**Description of the problem including expected versus actual behavior**:
When using NEST from a `System.Threading.Tasks.Dataflow` pipeline to pull records from a database, convert them to a type marked with the `ElasticsearchType` attribute, and (synchronously) index them in bulk, we are seeing an `UnexpectedElasticsearchClientException` wrapping a `System.Net.WebException` with message: `"The request was aborted: The request was canceled."` Full trace:

```
Type: Elasticsearch.Net.UnexpectedElasticsearchClientException
Message: The request was aborted: The request was canceled.
Source: Elasticsearch.Net
TargetSite: TResponse Request[TResponse](Elasticsearch.Net.HttpMethod, System.String, Elasticsearch.Net.PostData, Elasticsearch.Net.IRequestParameters)
DataflowMessageValue: Document[]
StackTrace:    at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[TResponse](PostData body, BulkRequestParameters requestParameters)
   at Nest.LowLevelDispatch.BulkDispatch[TResponse](IRequest`1 p, SerializableData`1 body)
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch)
   at ElasticDocumentFacade`1.BulkWrite(IBulkDocumentWriteRequest`1 request) in <our build server>
   at IndexService.<>c__DisplayClass5_0.<Build>b__0(IEnumerable`1 batch) in <our build server>
   at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass5.<.ctor>b__0(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
Type: System.Net.WebException
Message: The request was aborted: The request was canceled.
Source: System
TargetSite: Int32 Read(Byte[], Int32, Int32)
StackTrace:    at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.StreamReader.ReadBuffer(Char[] userBuffer, Int32 userOffset, Int32 desiredChars, Boolean& readToUserBuffer)
   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at Nest.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
   at Nest.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Nest.Json.JsonTextReader.ParseProperty()
   at Nest.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Nest.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Nest.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Nest.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Nest.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Nest.BulkResponseItemJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Nest.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Nest.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Nest.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Nest.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Nest.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Nest.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Nest.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Nest.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Nest.InternalSerializer.Deserialize(Type type, Stream stream)
   at Nest.InternalSerializer.Deserialize[T](Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
```

We are using an `IElasticClient` registered with our DI container as a singleton, with no custom `ConnectionSettings` save for the node `Uri`. This is occurring in a development environment with a single ES node running on the same machine. Oddly, it only seems to happen intermittently, and only after the pipeline runs for a while (>5-10 minutes, usually >5 million documents).

**Steps to reproduce**:
Run bulk index operations long enough...? Happy to provide more details to help with reproducing this if you need.

**Comment by Mpdreamz** [comment]
Hi @w-bonelli are you running on .NET core? Are you using Windows/Linux?

**Comment by w-bonelli** [comment]
Thanks @Mpdreamz for your response. We are on Windows, .NET framework 4.5.1.

**Comment by Mpdreamz** [comment]
Thanks that opens up the possibility to diagnose with network tracing:

e.g as described in this blogpost: http://mikehadlow.blogspot.nl/2012/07/tracing-systemnet-to-debug-http-clients.html

`Informational` might yield too much though lets set it to `Error` only for now: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-configure-network-tracing

Before doing that though , with what kind of concurrency are you hitting your local `elasticsearch` instance. If you start seeing requests taking longer and longer you might be overloading your single node with too many requests at once.

Another point of interest would be the output of: 

```GET /_nodes/stats/http```

After an import run.

You'll have to restart ES before doing the import though to reset the counters.

**Comment by w-bonelli** [comment]
We've tried the `Dataflow` block calling `IElasticClient.Bulk()` with max concurrency between 2-8.  `GET /_nodes/stats/http : current_open` never tops 9 (thinking the 9th could be Kibana?). The ES node is configured with 16gb heap size, with request times climbing a bit at first then leveling off. ES logs look ok too, so I don't see an indication of overloading. I should also note we've tried bulk sizes between 1,000-100,000 and continue to see this.

If I can get to it later today I will try network tracing. Thanks for the suggestion.

**Comment by Mpdreamz** [comment]
Hey @w-bonelli i'd also be interested in `total_opened` from the `http` stats. This should also be a low number if the only thing happening on the cluster is the bulk import (given a freshly started node).

**Comment by w-bonelli** [comment]
@Mpdreamz Sorry for the silence. `total_opened` increases at what seems like a constant rate as bulk indexing keeps running. E.g. single digits per minute. Should it be staying constant instead? Yes, bulk import is the only thing happening.

I'm hoping to reproduce the error with network tracing later today and will update if/when I can.

**Comment by w-bonelli** [comment]
Hey @Mpdreamz I managed to reproduce this. Network tracing gives `Exception in HttpWebRequest#<>:: - The operation has timed out.` Immediately prior to seeing the exception we saw response times jump from ~0.5 seconds to 20-40 seconds. It seems like overloading as you suggested.

**Comment by Mpdreamz** [comment]
It does appear so. Are you seeing any 427's from elasticsearch?

**Comment by w-bonelli** [comment]
What does 427 indicate? Not seeing any of those in ES logs or in the network trace. Do you mean HTTP 429's?

**Comment by DenisP01** [comment]
I fixed it with Elasticsearch config elasticsearch.yml
[https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html](url)
```
http.max_header_size: 1mb
http.max_initial_line_length: 1mb

http.max_content_length: 500mb
```

**Comment by Mpdreamz** [comment]
@w-bonelli closing this due to its age. I dropped the ball on this completely as the ticket flew off my radar for which I apologize.

Be keen to hear back on whether you were able to stabilize your bulk import!

**Comment by w-bonelli** [comment]
No worries. Throttling things a bit and using a resilience policy made everything well. Thanks again
