### ISSUE TITLE
NSSM .Net core deployment service for  nest , but iis or (cmd  dotnet xx.dll) is ok

### ISSUE THREAD

**Issue by stuyun** [elastic/elasticsearch-net#3385]
var strs = str.Split('|');
            var nodes = strs.Select(s => new Uri(s)).ToList();
            var connectionPool = new SniffingConnectionPool(nodes);
            var connectionString = new ConnectionSettings(connectionPool);
            connectionString.BasicAuthentication(_elasticSearchConfigration.AuthUserName, 
        _elasticSearchConfigration.AuthPassWord);
      return new ElasticClient(connectionString);

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:?]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:?]
	at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343) ~[netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.16.Final.jar:4.1.16.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[2018-08-28T13:40:03,417][WARN ][o.e.x.s.t.n.SecurityNetty4HttpServerTransport] [-5fAlTz] caught exception while handling client http traffic, closing connection [id: 0xc2b43acd, L:/192.168.0.101:9200 - R:/192.168.0.103:60937]

**Comment by russcam** [comment]
It's not clear how the Java stacktrace relates to NEST itself. Can you please provide more details by following the details requested in the issue template:

```
<!--
GitHub is reserved for bug reports and feature requests. The best place
to ask a general question is at the Elastic Discourse forums at
https://discuss.elastic.co. If you are in fact posting a bug report or
a feature request, please include one and only one of the below blocks
in your new issue.
-->

<!--
If you are filing a bug report, please remove the below feature
request block and provide responses for all of the below items.
-->

**NEST/Elasticsearch.Net version**:

**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

<!--
If you are filing a feature request, please remove the above bug
report block and provide responses for all of the below items.
-->

**Describe the feature**:
```

**Comment by stuyun** [comment]
**NEST/Elasticsearch.Net version  6.1.0

**Elasticsearch version 6.3.0:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `ConnectionSettings` (if relevant)**:
            var str = _elasticSearchConfigration.ConnectionString;// http://192.168.0.102:9200
            var strs = str.Split('|');
            var nodes = strs.Select(s => new Uri(s)).ToList();
            var connectionPool = new SniffingConnectionPool(nodes);
            var connectionString = new ConnectionSettings(connectionPool);
            connectionString.BasicAuthentication(_elasticSearchConfigration.AuthUserName, 
          _elasticSearchConfigration.AuthPassWord);//default  es user and pwd

            return new ElasticClient(connectionString);
  


**Provide `DebugInformation` (if relevant)**:



**Describe the feature**:

**Comment by russcam** [comment]
Based on the limited details, it sounds to me like it's an issue related to running Elasticsearch with NSSM and IIS, and not an issue with NEST.

I would suggest opening a question at https://discuss.elastic.co/c/elasticsearch with more details first. Running Elasticsearch as a service with NSSM isn't something that is officially supported; it may work OK but it's not something that is tested. For officially supported Windows Service installations

1. the zip distribution comes with the ability to install as a service using Apache Commons Daemon
2. the MSI Windows installer distribution comes with an executable that can be installed as a service as part of installation.

Since this doesn't appear to an issue with NEST, I'm going to close this issue. If you feel this is incorrect and can provide more detail for the NEST side, we can look at reopening. Thanks!

**Comment by stuyun** [comment]
ok
