### ISSUE TITLE
Authentication to Elastic Cloud on AWS fails from Linux Docker container on Azure Web Apps for Containers

### ISSUE THREAD

**Issue by provanguard** [elastic/elasticsearch-net#3407]
**NEST/Elasticsearch.Net version**:
6.3.0
**Elasticsearch version**:
6.4.0 (6.3.1)
**Description of the problem including expected versus actual behavior**:

Serilog Elasticsearch sink (using Elasticsearch.net) works well when running from Visual Studio but getting error when running the same application in Azure Web Apps for Containers, meaning a Docker Linux container. The serilog sink's author pointed out that it is the elasticsearch.net library that throws the error. The error observed:

```
2018-09-06T17:02:51.600083189Z 2018-09-06T17:02:51.5996368Z Caught exception while preforming bulk operation to Elasticsearch: Elasticsearch.Net.ElasticsearchClientException: One or more errors occurred. (Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration.) ---> System.AggregateException: One or more errors occurred. (Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration.) ---> Elasticsearch.Net.PipelineException: Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration.
2018-09-06T17:02:51.600179389Z    at Elasticsearch.Net.RequestPipeline.ThrowBadAuthPipelineExceptionWhenNeeded(IApiCallDetails details, IElasticsearchResponse response) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 320
2018-09-06T17:02:51.600229789Z    at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 443
2018-09-06T17:02:51.600302790Z    at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Transport.cs:line 68
2018-09-06T17:02:51.600311490Z    --- End of inner exception stack trace ---
2018-09-06T17:02:51.600317990Z    --- End of inner exception stack trace ---
2018-09-06T17:02:51.600370390Z    at Elasticsearch.Net.Transport`1.HandleElasticsearchClientException(RequestData data, Exception clientException, IElasticsearchResponse response) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Transport.cs:line 196
2018-09-06T17:02:51.600434990Z    at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Transport.cs:line 180
2018-09-06T17:02:51.600482090Z    at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Transport.cs:line 97
2018-09-06T17:02:51.600497590Z    at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatchChecked[T](IEnumerable`1 events)
2018-09-06T17:02:51.600511690Z    at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatch(IEnumerable`1 events)
```

Net Core 2.1.4, latest runtime.
Here are our Azure Application settings that the code loads:

```
XXX_Serilog__WriteTo__Elasticsearch__Name
Elasticsearch

XXX_Serilog__WriteTo__Elasticsearch__Args__nodeUris
https://xxx.us-east-1.aws.found.io:9243/

XXX_Serilog__WriteTo__Elasticsearch__Args__indexFormat
xxx-api-dev

XXX_Serilog__WriteTo__Elasticsearch__Args__connectionGlobalHeaders
Authorization=Basic base64encodedcredentials
```

Other apps in the normal Azure Web apps (Windows based IIS) run ok with identical settings.

**Steps to reproduce**:
 1. Try to log into elastic search (hosted on AWS) from an Azure Web application for containers

**Comment by Mpdreamz** [comment]
If you use AWS you  need to integrate with IAM.

You can use this lovely community provided `IConnection` implementation:

https://github.com/bcuff/elasticsearch-net-aws

Its readme has an example how to hook it into serilog.

**Comment by provanguard** [comment]
@Mpdreamz Thanks. One issue less to consider then. But how to proceed further with this error?

**Comment by provanguard** [comment]
@toftware  I am using this base image: microsoft/dotnet:2.1.5-aspnetcore-runtime

Could this be the issue? What other image could I use that should not have any certificate problems?

**Comment by toftware** [comment]
That should be alright then.

**Comment by russcam** [comment]
Is this still an issue @provanguard ?

**Comment by codebrain** [comment]
Closing as no response received.
