### ISSUE TITLE
SimpleJson can't serialize Type. (Method may only be called on a Type for which Type.IsGenericParameter is true.)

### ISSUE THREAD

**Issue by gurustron** [elastic/elasticsearch-net#3503]
**NEST/Elasticsearch.Net version**: master 

**Description of the problem including expected versus actual behavior**:
Exception is thrown(Method may only be called on a Type for which Type.IsGenericParameter is true.) during serialization of instance of `RuntimeType`. Serializer tries to call get on `DeclaringMethod` property.  Expected behavior - type is serialized. 

**Steps to reproduce**:
 
`LowLevelRequestResponseSerializer.Instance.Serialize(typeof(object), new MemoryStream());`

**Stacktrace**:
`at System.RuntimeType.get_DeclaringMethod()
   at lambda_method(Closure , Object )
   at Elasticsearch.Net.ReflectionUtils.<>c__DisplayClass33_0.<GetGetMethodByExpression>b__0(Object source)
   at Elasticsearch.Net.PocoJsonSerializerStrategy.TrySerializeUnknownTypes(Object input, Object& output)
   at Elasticsearch.Net.PocoJsonSerializerStrategy.TrySerializeNonPrimitiveObject(Object input, Object& output)
   at Elasticsearch.Net.ElasticsearchNetJsonStrategy.TrySerializeNonPrimitiveObject(Object input, Object& output)
   at Elasticsearch.Net.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder)
   at Elasticsearch.Net.SimpleJson.SerializeObject(Object json, IJsonSerializerStrategy jsonSerializerStrategy)
   at Elasticsearch.Net.LowLevelRequestResponseSerializer.Serialize[T](T data, Stream writableStream, SerializationFormatting formatting)
   at TestElasticLogSerializer.Program.Main(String[] args)`

**Comment by gurustron** [comment]
I think approach similar to [exceptions](https://github.com/elastic/elasticsearch-net/commit/82c4edd320a0943224bbb4fc6feac32b94799220) can be used.

**Comment by Mpdreamz** [comment]
I am tempted to mark this as won't fix given we are making good progress at eliminating SImpleJson from the low level client. 

Thoughts @elastic/microsoft ?

**Comment by Mpdreamz** [comment]
Thank you for raising this @gurustron since 7.x no longer uses simplejson in the low level client I am marking this as won't fix.
