### ISSUE TITLE
Cannot assign requested address ---> System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by claritycodeweb** [elastic/elasticsearch-net#3541]
**NEST/Elasticsearch.Net version**: 6.4.1

**Elasticsearch version**: 6.4

**Cannot Dispose Resources from ConnectionConfiguration**:
During large number of request to our endpoint we discovered HTTP Error coming from ElasticLowLevelClient.

# Audit trail of this API call:
 - [1] BadRequest: Node: http://tasks.elasticsearch:9200/ Took: 00:00:00.1135940
# OriginalException: System.Net.Http.HttpRequestException: Cannot assign requested address ---> System.Net.Sockets.SocketException: Cannot assign requested address
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)

ElasticLowLevelClient is created per request but how should we dispose it? Unfortunately when at least one error occurs new instance ElasticLowLevelClient is not able to send any request to Elastic. 

Here is example of our solution how to fix it:
```
public void Test()
{
    ConnectionConfiguration settings = new ConnectionConfiguration(new Uri("http://tasks.elasticsearch:9200")).RequestTimeout(TimeSpan.FromSeconds(10));
    try
    {
        ElasticLowLevelClient lowlevelClient = new ElasticLowLevelClient(settings);

        /*Do some requests */
        .....

    }
    finally
    {
        // How to realease resources?
        (this.settings as IDisposable)?.Dispose();
    }
}
```
The question is why in class public abstract class ConnectionConfiguration<T> Dispose methods are not public: 

```
void IDisposable.Dispose() => this.DisposeManagedResources();

protected virtual void DisposeManagedResources()
{
	this._connectionPool?.Dispose();
	this._connection?.Dispose();
	this._semaphore?.Dispose();
}
```

**Comment by Mpdreamz** [comment]
They are not public because we believe it leads people to think they need to dispose `ConnectionSettings`/`ConnectionConfiguration` which should actually be reused as much as possible much like `HttpClient` instances should be shared as much as possible. 

> ElasticLowLevelClient is created per request

This is very much an anti pattern and should be avoided.

See also: https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/lifetimes.html
