### ISSUE TITLE
NEST 7.0 JSON serialization error with interval setting on date histogram aggregation

### ISSUE THREAD

**Issue by ejsmith** [elastic/elasticsearch-net#3695]
**NEST/Elasticsearch.Net version**: 7.0.0-alpha1

**Elasticsearch version**: 7.0.0

**Description of the problem including expected versus actual behavior**:
Getting the following error when trying to do a date histogram aggregation and setting the interval property: `expected:'String Begin Token', actual:']', at offset:755`

**Steps to reproduce**:
```csharp
[Fact]
public void CanDoNestDateHistogram() {
    var client = GetClient();
    var index = CreateRandomIndex(client, i => i.Map<MyType>(d => d.Dynamic()));
    client.IndexMany(new[] { new MyType { Field5 = DateTime.Now } }, index);
    client.Refresh(index);

    var response = client.Search<MyType>(i => i.Index(index).Aggregations(f => f
        .DateHistogram("myagg", d => d.Field(d2 => d2.Field5).Interval("1d"))
    ));

    Assert.True(response.IsValid);
}
```

Here is the full stacktrace:
```
Elasticsearch.Net.UnexpectedElasticsearchClientException : expected:'String Begin Token', actual:']', at offset:755
---- Elasticsearch.Net.JsonParsingException : expected:'String Begin Token', actual:']', at offset:755
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Foundatio.Parsers.Tests.QueryParserTests.CanDoNestDateHistogram() in /Users/ejsmith/Foundatio.Parsers/tests/Foundatio.Parsers.LuceneQueries.Tests/QueryParserTests.cs:line 313
----- Inner Stack Trace -----
   at Elasticsearch.Net.JsonReader.ReadStringSegmentCore(Byte[]& resultBytes, Int32& resultOffset, Int32& resultLength)
   at Elasticsearch.Net.JsonReader.ReadString()
   at Nest.AggregateFormatter.GetDateHistogramBucket(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.AggregateFormatter.ReadBucket(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.AggregateFormatter.GetMultiBucketAggregate(JsonReader& reader, IJsonFormatterResolver formatterResolver, ArraySegment`1& propertyName)
   at Nest.AggregateFormatter.ReadAggregate(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.AggregateDictionaryFormatter.ReadAggregate(JsonReader& reader, IJsonFormatterResolver formatterResolver, String[] tokens, Dictionary`2 dictionary)
   at Nest.AggregateDictionaryFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Nest.InternalSerializer.Deserialize[T](Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
```

**Comment by russcam** [comment]
Thanks for reporting @ejsmith . 

I think this looks like it may be the same issue as #3673. I've opened a PR for this (#3678) and just ran an integration test that specified only field and interval for a date histogram aggregation as you have above, and all passed.

**Comment by ejsmith** [comment]
Thanks! Will you be pushing another alpha soon?

**Comment by russcam** [comment]
No worries! Plan is to release another alpha this week. 

I'll close this now as it's been merged into 7.x. If you wanted to kick the tyres before the next nuget release, you can get a canary release from CI: https://ci.appveyor.com/nuget/elasticsearch-net. It should be in `NEST.7.1.0-ci20190429T032721` and later
