### ISSUE TITLE
Exception thrown when using cat APIs with nonexistent index

### ISSUE THREAD

**Issue by jonyadamit** [elastic/elasticsearch-net#3936]
**NEST/Elasticsearch.Net version**:
7.0.0
**Elasticsearch version**:
7.2.0
**Description of the problem including expected versus actual behavior**:

**Actual:** A `JsonParsingException` is thrown when using any of the cat APIs on a nonexistent index.
**Expected:** Should behave as other APIs and set `IsValid` to `false`, without throwing exceptions, generating correct ServerError information.

**Steps to reproduce**:
 1. client.Cat.Count(c => c.Index("xxx "))

**Provide `DebugInformation` (if relevant)**:
```
# FailureReason: Unrecoverable/Unexpected BadResponse while attempting GET on http://jonynuc:9200/_cat/count/xxx
 - [1] BadResponse: Node: http://jonynuc:9200/ Exception: JsonParsingException Took: 00:00:00.0139982
# Audit exception in step 1 BadResponse:
Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'[', actual:'{', at offset:0
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadIsBeginArrayWithVerify()
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Nest.CatResponseBuilder`1.DeserializeResponse(IElasticsearchSerializer builtInSerializer, IApiCallDetails response, Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
# Inner Exception: expected:'[', actual:'{', at offset:0
Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'[', actual:'{', at offset:0
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadIsBeginArrayWithVerify()
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Nest.CatResponseBuilder`1.DeserializeResponse(IElasticsearchSerializer builtInSerializer, IApiCallDetails response, Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
# Exception:
Elasticsearch.Net.UnexpectedElasticsearchClientException: expected:'[', actual:'{', at offset:0 ---> Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'[', actual:'{', at offset:0
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadIsBeginArrayWithVerify()
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Nest.CatResponseBuilder`1.DeserializeResponse(IElasticsearchSerializer builtInSerializer, IApiCallDetails response, Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Nest.NamespacedClientProxy.DoCat[TRequest,TParams,TCatRecord](TRequest request)
   at Nest.Specification.CatApi.CatNamespace.Count(Func`2 selector)
   at UserQuery.RunUserAuthoredQuery() in C:\Users\jonya\AppData\Local\Temp\LINQPad5\_iuorjidp\query_mljegh.cs:line 35
   at LINQPad.ExecutionModel.ClrQueryRunner.Run()
   at LINQPad.ExecutionModel.Server.RunQuery(QueryRunner runner)
```

**Comment by russcam** [comment]
Thanks for reporting @jonyadamit, this is a bug

**Comment by russcam** [comment]
I've opened #3944 to address
