### ISSUE TITLE
Unexpected bad response crash: 'Number Token', actual:'null', at offset:30

### ISSUE THREAD

**Issue by DAPretorius** [elastic/elasticsearch-net#3973]
Hi there,

NEST/Elasticsearch.Net version: 7.0.1 and 7.1.0
Elasticsearch version:
"version": {
    "number": "5.3.2",
    "build_hash": "f978db6",
    "build_date": "2019-04-05T17:06:18.806Z",
    "build_snapshot": false,
    "lucene_version": "6.4.2"
  }

I'm running a fixed set of queries against our ES every 30 minutes. All of these work without any issue with the exception of one.

The one that fails has everything in common with the others except that it uses a different field than the others. The rest of the query is identical.

I'm loading it into a searchdescriptor first so that I can extract the raw json query. Then I am executing it on the server.

If I however run the raw json query on the server it does not crash and gives me the required data.

raw query: POST data-*/_search
{"query":{"bool":{"filter":[{"range":{"arcs":{"gt":0.0}}},{"range":{"timestamp":{"format":"yyyy-MM-dd'T'HH:mm:ss.SSSSSSS","gte":"2019-7-26T4:24:40.695"}}}]}},"size":10000}

"took": 285,
  "timed_out": false,
  "_shards": {
    "total": 487,
    "successful": 487,
    "failed": 0
  },
  "hits": {
    "total": 74907,
    "max_score": 0,
    "hits": [ SNIP"

The error is 100% reproducible. Let me know if you need more information.

Provide `ConnectionSettings` (if relevant):
ConnectionSettings settings = new ConnectionSettings(node);
            settings.ThrowExceptions(alwaysThrow: true);
            settings.DefaultIndex("data-*");

Provide `DebugInformation` (if relevant):
# FailureReason: Unrecoverable/Unexpected BadResponse while attempting POST on https://aws_server/data-%2A/_search
 - [1] BadResponse: Node: https://aws_server/ Exception: JsonParsingException Took: 00:00:04.8019986
# Audit exception in step 1 BadResponse:
Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'Number Token', actual:'null', at offset:30
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadInt64()
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadInt32()
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Nest.SourceFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
# Inner Exception: expected:'Number Token', actual:'null', at offset:30
Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'Number Token', actual:'null', at offset:30
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadInt64()
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadInt32()
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Nest.SourceFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
# Exception:
Elasticsearch.Net.UnexpectedElasticsearchClientException: expected:'Number Token', actual:'null', at offset:30 ---> Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'Number Token', actual:'null', at offset:30
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadInt64()
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadInt32()
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Nest.SourceFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Nest.ElasticClient.Search[TDocument](ISearchRequest request)
   at ElasticSearchMonitor.Elastic.QueryElastic(String alertName, SearchDescriptor`1 query, Boolean& valid, String& debugQuery)
   at ElasticSearchMonitor.Elastic.ArcsCheckWatchList(String alertName)

**Comment by russcam** [comment]
[NEST 7.x is not supported with Elasticsearch 5.x.](https://github.com/elastic/elasticsearch-net#compatibility-matrix) You should use the latest NEST 5.x version with Elasticsearch 5.3.2.

Closing this as not supported. If the issue persists with NEST 5.x, please reopen :+1:
