### ISSUE TITLE
NEST 7.1.0: Elasticsearch.Net.UnexpectedElasticsearchClientException: Cannot access a disposed object

### ISSUE THREAD

**Issue by UkrZilla** [elastic/elasticsearch-net#3974]
**NEST/Elasticsearch.Net version**: 7.1.0

**Elasticsearch version**: 7.2.0

`Elasticsearch.Net.UnexpectedElasticsearchClientException: Cannot access a disposed object.
Object name: 'The stream with Id 257d890a-4ea3-4062-988f-746dcf1cf4e7 and Tag  is disposed.'. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The stream with Id 257d890a-4ea3-4062-988f-746dcf1cf4e7 and Tag  is disposed.'.
   at Elasticsearch.Net.RecyclableMemoryStream.CheckDisposed()
   at Elasticsearch.Net.RecyclableMemoryStream.ToArray()
   at Nest.SourceFormatter`1.Serialize(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)
   at Nest.SourceWriteFormatter`1.Serialize(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Nest_ITermQueryFormatter8.Serialize(JsonWriter& , ITermQuery , IJsonFormatterResolver )
   at Nest.FieldNameQueryFormatter`2.Serialize(JsonWriter& writer, TInterface value, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Nest_IQueryContainerFormatter2.Serialize(JsonWriter& , IQueryContainer , IJsonFormatterResolver )
   at Elasticsearch.Net.Nest_ISearchRequestFormatter1.Serialize(JsonWriter& , ISearchRequest , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.JsonSerializer.<SerializeAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Elasticsearch.Net.SerializableData`1.<WriteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Elasticsearch.Net.HttpWebRequestConnection.<RequestAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Elasticsearch.Net.RequestPipeline.<CallElasticsearchAsync>d__57`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()`

**Comment by russcam** [comment]
Thanks for opening @UkrZilla. Do you have a small reproducible example that would help diagnose under what conditions this is thrown?

**Comment by UkrZilla** [comment]
Hi @russcam We setted only one simple field to filter query. Can't send raw query since exception is occurred on client

**Comment by UkrZilla** [comment]
Just realized that it is our bug. We use interface IElasticsearchSerializer in order to set JsonSerializerSettings and used this code:

`public void Serialize<T>(T data, Stream stream, SerializationFormatting formatting = SerializationFormatting.Indented)
    {
      using (var writer = new StreamWriter(stream))
      {
        _serializer.Serialize(writer, data, typeof(T));
      }
    }`

have to set leaveOpen to true in StreamWriter constructor
