### ISSUE TITLE
[tests] compositeaggregation 6.x

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#4008]
`build.bat seed:33573 integrate 6.2.4 "readonly" "compositeaggregation"`

```
Tests.Aggregations.Bucket.Composite.CompositeAggregationUsageTests.ReturnsExpectedStatusCode
Tests.Framework.ResponseAssertionException : Expected dictionary not to be <null>.
Response Under Test:
Valid NEST response built from a successful low level call on POST: /projects-only/doc/_search?pretty=true&error_trace=true&typed_keys=true
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://localhost:9200/ Took: 00:00:00.0788245
# Request:
```

```
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.NotBeNull(String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\ReferenceTypeAssertions.cs:line 58
   at Tests.Aggregations.Bucket.Composite.CompositeAggregationUsageTests.ExpectResponse(ISearchResponse`1 response) in D:\a\1\s\src\Tests\Tests\Aggregations\Bucket\Composite\CompositeAggregationUsageTests.cs:line 165
   at Tests.Framework.ApiIntegrationTestBase`5.<>c__DisplayClass17_0.<AssertOnAllResponses>b__0(TResponse r) in D:\a\1\s\src\Tests\Tests\Framework\EndpointTests\ApiIntegrationTestBase.cs:line 66
```

See: https://github.com/elastic/elasticsearch-net/pull/3997/checks?check_run_id=187183849

**Comment by russcam** [comment]
I think this is fixed already in https://github.com/elastic/elasticsearch-net/pull/3999/commits/e7bcd3040866cbe9e58300d5103dec3b492eb2cc

**Comment by russcam** [comment]
Closing as already fixed
