### ISSUE TITLE
[tests] Get Task Api setup 7.x

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#4009]
`build.bat seed:61398 integrate 7.0.0 "writable" "gettask"`

From: https://github.com/elastic/elasticsearch-net/pull/3983

```
[xUnit.net 00:05:27.0570598]     Tests.Cluster.TaskManagement.GetTask.GetTaskApiTests.ReturnsExpectedResponse [FAIL]
Failed   Tests.Cluster.TaskManagement.GetTask.GetTaskApiTests.ReturnsExpectedResponse
Error Message:
 System.Exception : failure in setting up integration
Stack Trace:
   at Tests.Cluster.TaskManagement.GetTask.GetTaskApiTests.IntegrationSetup(IElasticClient client, CallUniqueValues values) 
   at Tests.Framework.EndpointTests.RequestResponseApiTestBase`5.<>c__DisplayClass37_0.<<Calls>b__0>d.MoveNext() in /home/vsts/work/1/s/src/Tests/Tests/Framework/EndpointTests/RequestResponseApiTestBase.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at Tests.Framework.EndpointTests.RequestResponseApiTestBase`5.AssertOnAllResponses(Action`1 assert) in /home/vsts/work/1/s/src/Tests/Tests/Framework/EndpointTests/RequestResponseApiTestBase.cs:line 130
   at Tests.Framework.EndpointTests.ApiIntegrationTestBase`5.ReturnsExpectedResponse() in /home/vsts/work/1/s/src/Tests/Tests/Framework/EndpointTests/ApiIntegrationTestBase.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:05:27.0829260]     Tests.Cluster.TaskManagement.GetTask.GetTaskApiTests.ReturnsExpectedStatusCode [FAIL]
[xUnit.net 00:05:27.0842424]     Tests.Cluster.TaskManagement.GetTask.GetTaskApiTests.ReturnsExpectedIsValid [FAIL]
[2019-08-09T05:05:18,380][INFO ][o.e.c.m.MetaDataMappingService] [writable-node-e0ad519200] [nest-fluent-6055930f/DW-nyIGwRYOOBQYo0-G3HA] create_mapping [_doc]
[2019-08-09T05:05:18,488][INFO ][o.e.c.m.MetaDataCreateIndexService] [writable-node-e0ad519200] [nest-fluent-bada3aef] creating index, cause [api], templates [nest_tests], shards [2]/[0], mappings []
Failed   Tests.Cluster.TaskManagement.GetTask.GetTaskApiTests.ReturnsExpectedStatusCode
Error Message:
 System.Exception : failure in setting up integration
Stack Trace:
   at Tests.Cluster.TaskManagement.GetTask.GetTaskApiTests.IntegrationSetup(IElasticClient client, CallUniqueValues values) 
   at Tests.Framework.EndpointTests.RequestResponseApiTestBase`5.<>c__DisplayClass37_0.<<Calls>b__0>d.MoveNext() in /home/vsts/work/1/s/src/Tests/Tests/Framework/EndpointTests/RequestResponseApiTestBase.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at Tests.Framework.EndpointTests.RequestResponseApiTestBase`5.AssertOnAllResponses(Action`1 assert) in /home/vsts/work/1/s/src/Tests/Tests/Framework/EndpointTests/RequestResponseApiTestBase.cs:line 130
   at Tests.Framework.EndpointTests.ApiIntegrationTestBase`5.ReturnsExpectedStatusCode() in /home/vsts/work/1/s/src/Tests/Tests/Framework/EndpointTests/ApiIntegrationTestBase.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
Failed   Tests.Cluster.TaskManagement.GetTask.GetTaskApiTests.ReturnsExpectedIsValid
Error Message:
 System.Exception : failure in setting up integration
Stack Trace:
   at Tests.Cluster.TaskManagement.GetTask.GetTaskApiTests.IntegrationSetup(IElasticClient client, CallUniqueValues values) 
   at Tests.Framework.EndpointTests.RequestResponseApiTestBase`5.<>c__DisplayClass37_0.<<Calls>b__0>d.MoveNext() in /home/vsts/work/1/s/src/Tests/Tests/Framework/EndpointTests/RequestResponseApiTestBase.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at Tests.Framework.EndpointTests.RequestResponseApiTestBase`5.AssertOnAllResponses(Action`1 assert) in /home/vsts/work/1/s/src/Tests/Tests/Framework/EndpointTests/RequestResponseApiTestBase.cs:line 130
   at Tests.Framework.EndpointTests.ApiIntegrationTestBase`5.ReturnsExpectedIsValid() in /home/vsts/work/1/s/src/Tests/Tests/Framework/EndpointTests/ApiIntegrationTestBase.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by stevejgordon** [comment]
Closing due to age/inactivity.
