### ISSUE TITLE
Unable to get server side mappings due to unexpected boolean type (string)

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#4124]
Elastic 7.4.0 and NEST 7.3.0 are failing when I try to get the index mapping:

```
Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'true | false', actual:'"false"', at offset:77
  at at Elasticsearch.Net.Utf8Json.JsonReader.ReadBoolean()
  at at Elasticsearch.Net.Utf8Json.Formatters.BooleanFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
  at at Nest.UnionFormatter`2.TryRead[T](ArraySegment`1& segment, IJsonFormatterResolver formatterResolver, T& v)
````

```
{
  "daily-logevents-v1-2019.10.08" : {
    "mappings" : {
      "dynamic" : "false",
      "properties" : {
        "companyId" : {
          "type" : "keyword"
        },
        "created" : {
          "type" : "alias",
          "path" : "createdUtc"
        },
        "createdUtc" : {
          "type" : "date"
        },
        "id" : {
          "type" : "keyword"
        },
        "message" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "value" : {
          "type" : "integer"
        }
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/1020579/66514339-87798380-eaa2-11e9-9a16-edc99c3cb9c0.png)

As you can see I defined dynamic through the nest fluent api and this is breaking.

**Comment by niemyjski** [comment]
Looks like elasticsearch dynamic is treating it as string directly..

**Comment by russcam** [comment]
This is a consequence of the strictness of the Utf8Json deserializer; a custom formatter needs to be used here to deserialize a boolean string to `bool`. I'll open a PR for it now

**Comment by russcam** [comment]
I've opened https://github.com/elastic/elasticsearch-net/pull/4127

**Comment by niemyjski** [comment]
Thank you!
