### ISSUE TITLE
Doesn't handle Maps

### ISSUE THREAD

**Issue by haf-afa** [elastic/elasticsearch-net#4195]
**NEST/Elasticsearch.Net version**: 7.4

**Elasticsearch version**: doesn't matter

**Description of the problem including expected versus actual behavior**:

You can't pass `Map<'k, 'v>` into the client. It crashes.

**Steps to reproduce**:
 1. `client.IndexDocument({| thing = Map.empty |> Map.add "a" "b" |})`
 2. boom! 🔥 
 3.

Stacktrace:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (GenericArguments[2], 'Microsoft.FSharp.Collections.FSharpMap`2[System.String,System.String]', on 'Elasticsearch.Net.Utf8Json.Formatters.GenericDictionaryFormatter`3[TKey,TValue,TDictionary]' violates the constraint of type parameter 'TDictionary'.)
 ---> Elasticsearch.Net.UnexpectedElasticsearchClientException: GenericArguments[2], 'Microsoft.FSharp.Collections.FSharpMap`2[System.String,System.String]', on 'Elasticsearch.Net.Utf8Json.Formatters.GenericDictionaryFormatter`3[TKey,TValue,TDictionary]' violates the constraint of type parameter 'TDictionary'.
 ---> System.TypeLoadException: GenericArguments[2], 'Microsoft.FSharp.Collections.FSharpMap`2[System.String,System.String]', on 'Elasticsearch.Net.Utf8Json.Formatters.GenericDictionaryFormatter`3[TKey,TValue,TDictionary]' violates the constraint of type parameter 'TDictionary'.
   at Elasticsearch.Net.Utf8Json.JsonFormatterResolverExtensions.GetFormatterWithVerify[T](IJsonFormatterResolver resolver)
   at Serialize(Byte[][] , Object[] , JsonWriter& , Honey , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Serialize(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.SerializeUnsafe[T](T value, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Serialize[T](Stream stream, T value, IJsonFormatterResolver resolver)
   at Nest.DefaultHighLevelSerializer.Serialize[T](T data, Stream writableStream, SerializationFormatting formatting)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Serialize[T](T data, Stream stream, SerializationFormatting formatting)
   at Nest.IndexDescriptor`1.Nest.IProxyRequest.WriteJson(IElasticsearchSerializer sourceSerializer, Stream stream, SerializationFormatting formatting)
   at Nest.ProxyRequestFormatterBase`2.Serialize(JsonWriter& writer, TRequestInterface value, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.SerializeAsync[T](Stream stream, T value, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.SerializableData`1.WriteAsync(Stream writableStream, IConnectionConfigurationValues settings, CancellationToken cancellationToken)
   at Elasticsearch.Net.HttpConnection.SetContentAsync(HttpRequestMessage message, RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
```

Example record:

```fsharp

type Honey =
  { apiVersion: string
    kind: string
    name: string
    ns: string option
    labels: Map<string, string>
  }
```

**Comment by codebrain** [comment]
Hi @haf-afa,

The serialiser for dictionaries is using the `GenericDictionaryFormatter<TKey, TValue, TDictionary>` class which has type constraints for `TDictionary ` where `TDictionary : class, IDictionary<TKey, TValue>, new()`

By the looks of the error it appears as though the `.map` call results in a `Microsoft.FSharp.Collections.FSharpMap<System.String,System.String>` which does not meet the generic type constraint.

I know its kind of anti-F#, but if you could use `System.Collections.Generic` and the `Dictionary<>` or `IDictionary<>` interfaces you will have a better experience with the built-in serialisers.

We are collecting a list of improvements for 8.0. The topic of F# was added to that list, so I have included this ticket as a reference point there.

I hope this clarifies things, I have labelled this ticket for discussion.

Thanks

**Comment by russcam** [comment]
We might want to consider special casing ```FSharpMap`2```, similar to how JSON.NET handles map and other frequently used F# types: https://github.com/JamesNK/Newtonsoft.Json/blob/cdf10151d507d497a3f9a71d36d544b199f73435/Src/Newtonsoft.Json/Utilities/FSharpUtils.cs

**Comment by haf-afa** [comment]
I understand that, but `Map<'a,'b>` implements `IDictionary<'a, 'b>` so you could create a generic dictionary formatter, if you remove some of those constraints and just read from it. Newtonsoft is special in that it needs to both create and read, but you only need to read.

**Comment by stevejgordon** [comment]
We will re-evaluate F# compatibility with v8+.
