### ISSUE TITLE
Canary builds fail on windows CI (7.x)

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#4203]
Canary builds fail on windows CI (7.x)

https://dev.azure.com/azure3/elasticsearch-net/_build/results?buildId=2340

>D:\a\1\s\build\output\_packages\tmp\lib\netstandard2.0\Elasticsearch.Net7.dll was signed with official key token 96c599bbe3e70f5d
Assembly: 7.0.0.0 File: 7.5.0.0 Product: 7.5.0-ci20191111T104334 => D:\a\1\s\build\output\_packages\tmp\lib\net461\Elasticsearch.Net.VirtualizedCluster.dll
[90mscripts:[0m [34mvalidate-artifacts[90m:[0m [31mSystem.Collections.Generic.KeyNotFoundException: An index satisfying the predicate was not found in the collection.
   at Microsoft.FSharp.Collections.SeqModule.loop@911-22[T](FSharpFunc`2 predicate, IEnumerator`1 ie, Int32 i) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 917
   at Microsoft.FSharp.Collections.SeqModule.FindIndex[T](FSharpFunc`2 predicate, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 918
   at Scripts.Versioning.validate(String dll, String name) in D:\a\1\s\build\scripts\Versioning.fs:line 114
   at Scripts.Versioning.validateDllStrongName(String dll, String name) in D:\a\1\s\build\scripts\Versioning.fs:line 134
   at Scripts.Versioning.ValidateArtifacts@144-1.Invoke(String f) in D:\a\1\s\build\scripts\Versioning.fs:line 152
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 495
   at Scripts.Versioning.ValidateArtifacts@141.Invoke(String f) in D:\a\1\s\build\scripts\Versioning.fs:line 143
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 495
   at Scripts.Versioning.ValidateArtifacts(ArtifactsVersion _arg1) in D:\a\1\s\build\scripts\Versioning.fs:line 140
   at Scripts.Main.main@80-14.Invoke(Unit _arg12) in D:\a\1\s\build\scripts\Targets.fs:line 80
   at Scripts.Main.target@14.Invoke() in D:\a\1\s\build\scripts\Targets.fs:line 14
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Bullseye.Internal.ActionTarget.RunAsync(Boolean dryRun, Boolean parallel, Logger log, Func`2 messageOnly)[0m

**Comment by russcam** [comment]
@Mpdreamz I think this one can be closed now?
