### ISSUE TITLE
VerifyRepositoryResponse uses incorrect JsonFormatter

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#4382]
Relates: https://stackoverflow.com/questions/60062480/elasticsearch-fails-verifyrepositoryrequest-in-c-sharp-nest-client

The `Nodes` member on `VerifyRepositoryResponse` uses the incorrect `IJsonFormatter<T>` in JsonFormatterAttribute, causing an `EntryPointNotFoundException`.

**Comment by najamsaqib** [comment]
Hi Rus,
I know you have closed this issue, but I am having similar issue where I am getting JsonFormatter error when calling GetRepository API. I was not sure if I should open new issue for this or you can handle it here. Let me know.

I am getting "**Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'true | false', actual:'"true"'**" when I call GetRepository API through NEST, but when i used LowLevel API to get repository it work but I am not sure how to parse the response.

Here is the stack trace of the error i am getting, seems like issue related to JsonFormatter same as above case. 

# FailureReason: Unrecoverable/Unexpected BadResponse while attempting GET on http://localdev:9200/_snapshot/repo_aligncare_v7?pretty=true
 - [1] BadResponse: Node: http://localdev:9200/ Exception: JsonParsingException Took: 00:00:00.3099999
# Audit exception in step 1 BadResponse:
Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'true | false', actual:'"true"', at offset:216
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadBoolean() in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\JsonReader.cs:line 853
   at Elasticsearch.Net.Utf8Json.Formatters.NullableBooleanFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\Formatters\PrimitiveFormatter.cs:line 1330
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\Resolvers\DynamicObjectResolver.cs:line 1714
   at Nest.GetRepositoryResponseFormatter.GetRepository[TRepository,TSettings](ArraySegment`1 settings, IJsonFormatterResolver formatterResolver) in C:\Source\elasticsearch-net-7.x\src\Nest\Modules\SnapshotAndRestore\Repositories\GetRepository\GetRepositoryResponseFormatter.cs:line 120
   at Nest.GetRepositoryResponseFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver) in C:\Source\elasticsearch-net-7.x\src\Nest\Modules\SnapshotAndRestore\Repositories\GetRepository\GetRepositoryResponseFormatter.cs:line 79
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\JsonSerializer.cs:line 262
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, IJsonFormatterResolver resolver) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\JsonSerializer.cs:line 244
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\JsonSerializer.cs:line 323
   at Nest.DefaultHighLevelSerializer.Deserialize[T](Stream stream) in C:\Source\elasticsearch-net-7.x\src\Nest\CommonAbstractions\SerializationBehavior\DefaultHighLevelSerializer.cs:line 24
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Serialization\DiagnosticsSerializerProxy.cs:line 78
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Transport\Pipeline\ResponseBuilder.cs:line 113
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Transport\Pipeline\ResponseBuilder.cs:line 31
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Connection\HttpWebRequestConnection.cs:line 73
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 168
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Transport\Transport.cs:line 73
# Inner Exception: expected:'true | false', actual:'"true"', at offset:216
Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'true | false', actual:'"true"', at offset:216
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadBoolean() in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\JsonReader.cs:line 853
   at Elasticsearch.Net.Utf8Json.Formatters.NullableBooleanFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\Formatters\PrimitiveFormatter.cs:line 1330
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\Resolvers\DynamicObjectResolver.cs:line 1714
   at Nest.GetRepositoryResponseFormatter.GetRepository[TRepository,TSettings](ArraySegment`1 settings, IJsonFormatterResolver formatterResolver) in C:\Source\elasticsearch-net-7.x\src\Nest\Modules\SnapshotAndRestore\Repositories\GetRepository\GetRepositoryResponseFormatter.cs:line 120
   at Nest.GetRepositoryResponseFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver) in C:\Source\elasticsearch-net-7.x\src\Nest\Modules\SnapshotAndRestore\Repositories\GetRepository\GetRepositoryResponseFormatter.cs:line 79
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\JsonSerializer.cs:line 262
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, IJsonFormatterResolver resolver) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\JsonSerializer.cs:line 244
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\JsonSerializer.cs:line 323
   at Nest.DefaultHighLevelSerializer.Deserialize[T](Stream stream) in C:\Source\elasticsearch-net-7.x\src\Nest\CommonAbstractions\SerializationBehavior\DefaultHighLevelSerializer.cs:line 24
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Serialization\DiagnosticsSerializerProxy.cs:line 78
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Transport\Pipeline\ResponseBuilder.cs:line 113
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Transport\Pipeline\ResponseBuilder.cs:line 31
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Connection\HttpWebRequestConnection.cs:line 73
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 168
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Transport\Transport.cs:line 73
# Exception:
Elasticsearch.Net.UnexpectedElasticsearchClientException: expected:'true | false', actual:'"true"', at offset:216 ---> Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'true | false', actual:'"true"', at offset:216
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadBoolean() in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\JsonReader.cs:line 853
   at Elasticsearch.Net.Utf8Json.Formatters.NullableBooleanFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver) in C:\Source\elasticsearch-net-7.x\src\Elasticsearch.Net\Utf8Json\Formatters\PrimitiveFormatter.cs:line 1330
   at Deserialize(Object[] , JsonReader& , IJsonFormatterRes...

**Comment by russcam** [comment]
@najamsaqib would you mind opening a new issue for this please? If you also have the JSON response, please also post it in the new issue too. I think I can see what the problem is, but the JSON will help. Thanks!

**Comment by najamsaqib** [comment]
@russcam , thanks for a quick response. I have created this new [issue](https://github.com/elastic/elasticsearch-net/issues/4467) for this issue, please take a look and let me know if there is any workaround until it get fixed.

Thanks again.
Saqib
