### ISSUE TITLE
Type Load Exception when SCOM Agent Running on Windows Server

### ISSUE THREAD

**Issue by thollowell** [elastic/elasticsearch-net#4480]
After upgrading NEST and Elasticsearch.Net packages to 6.8.3 we are seeing the following error in app init. A few other threads have mentioned this can be traced to some type of conflict with the SCOM (System Center Operations Manger) agent which is deployed on our APP servers where we communicate with ES.

Log entry from our API servers below.

2020-03-04 11:23:04,496 [175] ERROR GetAllClustersHealthApi - Executing method <removed> resulted in unhandled exception: 
'System.TypeInitializationException: 
**The type initializer for 'Elasticsearch.Net.ConnectionConfiguration' threw an exception. ---> 
System.Reflection.AmbiguousMatchException: Multiple custom attributes of the same type found.
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)**
   at Elasticsearch.Net.RuntimeInformation.get_FrameworkDescription()
   at Elasticsearch.Net.ConnectionConfiguration..cctor()
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.ConnectionConfiguration`1..ctor(IConnectionPool connectionPool, IConnection connection, IElasticsearchSerializer requestResponseSerializer)
   at Nest.ConnectionSettingsBase`1..ctor(IConnectionPool connectionPool, IConnection connection, SourceSerializerFactory sourceSerializerFactory, IPropertyMappingProvider propertyMappingProvider)
   at removed.ES.ElasticClientBuilder.BuildClientCore(ClusterClientConfig clientConfig, IConnectionPool pool)
   at removed.ES.ClientFactory.<>c__DisplayClass7_1.<LoadClients>b__3(ClusterClientConfig cc)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at removed.ES.ClientFactory.LoadClients()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at removed.ES.ClientFactory.ResolveTargetCluster(ClientRequestContext context)
   at removed.ES.ClientFactory.GetClient(ClientRequestContext context)
   at removed.ES.ClusterSettingsClient.<GetClusterSettingsAsync>d__3.MoveNext() in D:\Agent02\_work\14\s\Src\removed\ES\ClusterSettingsClient.cs:line 0

Running on Windows Server 2012 R2. .Net Framework 4.7.2. 
SCOM Agent version is SCOM 2012 R2.
NEST version 6.8.3. 
ES.Net version 6.8.3
ES version 6.5

to repro, try to initialize a connection settings on a machine running the SCOM Agent.
Link below to another report of a similar issue which lead us to believe the SCOM agent is a potential cause for this. This does not occur on machines not running SCOM agents, however we cannot remove SCOM from our production servers.

[https://github.com/okta/okta-sdk-dotnet/issues/296](url)

**Comment by Mpdreamz** [comment]
A fix for this went out in: https://github.com/elastic/elasticsearch-net/releases/tag/6.8.4

Please update and try again! Please let us know if this is still an issue.

**Comment by thollowell** [comment]
Thanks. Will give it a shot.
