### ISSUE TITLE
Unable to get the records using POST

### ISSUE THREAD

**Issue by anaparthi-k** [elastic/elasticsearch-net#4483]
**NEST/Elasticsearch.Net version  : 6.0.0**:

**Elasticsearch version : 6.0.0**:

**Description of the problem including expected versus actual behavior**:

I am able to get the values using GET call but unable to get the same values using post call using below code.

string elasticsearchUrl = "";
string indexName = "";
Uri node = new System.Uri(elasticsearchUrl);
ConnectionSettings settings = new ConnectionSettings(node);
settings.DefaultIndex(indexName)
.PrettyJson()
.DisableDirectStreaming();
IElasticClient esClient = new ElasticClient(settings);
var response = esClient.Search<Providers>(s => s.Size(2).Query(q => q.MatchAll()));
var count= response.Documents.Count;

**Provide `ConnectionSettings` (if relevant)**:

Debug Information:

Invalid NEST response built from a unsuccessful low level call on POST: /<index_name>/providers/_search?pretty=true&typed_keys=true
# Audit trail of this API call:
 - [1] BadRequest: Node: http://<server_url>/ Took: 00:00:01.2758549
# OriginalException: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 73
# Request:
{"query":{"match_all":{}},"size":2}
# Response:

**Comment by codebrain** [comment]
Hi @anaparthi-k 

The issue appears to be in the code on lines;

```
string elasticsearchUrl = "";
string indexName = "";
```

Usually I would expect there to be values in these two variable assignments, for example;

```
string elasticsearchUrl = "http://localhost:9200";
string indexName = "my_index";
```

Can you please try again with the correct values in your environment?

**Comment by anaparthi-k** [comment]
I have placed the valid values but for security reasons I removed from there. Imagine the above code with valid URL and Index is provided in respective values. By the way I can able to the results for get call method but not for POST call.

**Comment by codebrain** [comment]
OK, thank you for clarifying.

I can see that you are using version `6.0.0` of the client, would you be able to try using the latest (at time of writing `6.8.4`) and see if the problem still persists? https://www.nuget.org/packages/NEST/6.8.4

I have a few additional questions:

1. Presumably you are able to access Elasticsearch through the web browser (using a GET to "/")?
2. Have you tried an alternate `POST` operation? Perhaps a bulk request?
3. Are you using a proxy, or are you in an environment, where HTTP `POST` is blocked?
4. Are you able to `POST` using curl, as opposed to the client? Please try: 

```
curl -X GET "localhost:9200/_search?pretty" -H 'Content-Type: application/json' -d'
{
    "query": {
        "match_all": {}
    }
}
```
'

**Comment by russcam** [comment]
We’re closing this issue due to inactivity; if you’re still in need of resolution, feel free to re-open with the additional details and we'd be glad to help you out 👍
