### ISSUE TITLE
AzureFunction build Pipeline

### ISSUE THREAD

**Issue by MaxThom** [elastic/elasticsearch-net#4524]
**NEST/Elasticsearch.Net version**:
7.6.1
Also using **NEST.JsonNetSerializier**
**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:
I'm using the packages in an AzureFunction that push incoming logs to ES. Everything works fine locally, the build with AzurePipeline work aswell.
But when the function execute, I get this error message : 

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: MessageProcessingLogs ---> System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load the specified file.
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   --- End of inner exception stack trace ---
   at SenseAI.CloudFunction.Services.Database.ElasticSearchLogRepository..ctor(String connectionString, String username, String password)
   at CloudFunction.DataPump.MessageProcessingLogs.Run(Message message, ExecutionContext exContext, ILogger logger) in /home/vsts/work/1/s/SenseAI.CloudFunction/MessageProcessingLogs.cs:line 31
   at lambda_method(Closure , MessageProcessingLogs , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidMethodInvoker.cs:line 21
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 587
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 532
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 470
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 278
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.ServiceBus.MessageProcessor.CompleteProcessingMessageAsync(Message message, FunctionResult result, CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.ProcessMessageAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.ServiceBus.MessageReceivePump.MessageDispatchTask(Message message)
```

Seems there is a file that can't be built in the projects ? I'm using .netcore 3.1 for the functions and for the pipeline build aswell.

Here is the code, line 31 in the exception refer to the constructor of this class:
```c#
public class ElasticSearchLogRepository : ILogRepository
    {
        private ElasticClient _elasticClient;
        private readonly string ModuleLogsIndex = "logs-devices-modules";
        private readonly string EdgeLogsIndex = "logs-devices-edges";

        public ILogEntity<Log> ModuleLogs { get; private set; }
        public ILogEntity<Log> EdgeLogs { get; private set; }

        public ElasticSearchLogRepository(string connectionString, string username, string password)
        {
            var pool = new SingleNodeConnectionPool(new Uri(connectionString));
            var settings =
                new ConnectionSettings(pool, (builtin, serializerSettings) =>
                    new JsonNetSerializer(builtin,
                        serializerSettings,
                        contractJsonConverters: new JsonConverter[] { new StringEnumConverter() }
                    )
                ).ThrowExceptions().BasicAuthentication(username, password);

            _elasticClient = new ElasticClient(settings);

            ModuleLogs = new ElasticSearchEntity<Log>(_elasticClient, ModuleLogsIndex);
            EdgeLogs = new ElasticSearchEntity<Log>(_elasticClient, EdgeLogsIndex);
        }

        public void Dispose()
        {
            _elasticClient = null;
        }
    }
```

Upon testing with elastic-search.net low level package, I find out that the function app wasnt working with .netstandard 2.1, so targeting the package to 7.5.1 instead of 7.6.1 solved the issue.
i'm not exactly sure why the function app isnt working with 2.1 since it's targeting .netcore 3.1, v3 and function sdk 3.0.5.

**Comment by MaxThom** [comment]
Found the problem, our function app wasnt correctly upgraded to runtime 3
