### ISSUE TITLE
expected:'"', actual:' ', at offset:61: UnexpectedElasticsearchClientException

### ISSUE THREAD

**Issue by kabzit13** [elastic/elasticsearch-net#4689]
**NEST/Elasticsearch.Net version**:
7.6.1

**Elasticsearch version**:
7.1

**Description of the problem including expected versus actual behavior**:
Getting UnexpectedElasticsearchClientException on sequantial requests match_all rests. 

expected:'"', actual:'
', at offset:61: UnexpectedElasticsearchClientException
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   at Nest.ElasticClient.SearchAsync[TDocument](ISearchRequest request, CancellationToken ct)
   at Nest.ElasticClient.SearchAsync[TDocument](Func`2 selector, CancellationToken ct)
   at GlobalSearch.Infrastructure.Helpers.DefaultNestSearchExecutor.Search[T](ValueTuple`8 searchParams) in C:\_agents\r\r001\_work\7\s\src\globalsearch\Infrastructure\Helpers\DefaultNestSearchExecutor.cs:line 49
   at GlobalSearch.Services.SearchProcessor.SearchObjectDetails(SearchRequestDto request) in C:\_agents\r\r001\_work\7\s\src\globalsearch\Services\SearchProcessor.cs:line 46
   at GlobalSearch.Handlers.SearchProxyHandler(SearchRequestDto request, ILambdaContext context) in C:\_agents\r\r001\_work\7\s\src\globalsearch\Handlers.cs:line 26
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

   at Elasticsearch.Net.Utf8Json.JsonReader.ReadStringSegmentRaw()
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.DeserializeAsync[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.ResponseBuilder.SetBodyAsync[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType, CancellationToken cancellationToken)
   at Elasticsearch.Net.ResponseBuilder.ToResponseAsync[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType, CancellationToken cancellationToken)
   at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)

on match_all request after a sequential set of same requests. 

**Steps to reproduce**:
 1. Start to execute the same heavy requests.
 2. After some time app starts to fire UnexpectedElasticsearchClientException. 

**Expected behavior**
Expected not to receive UnexpectedElasticsearchClientException. 

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by russcam** [comment]
@kabzit13 can you [capture the response JSON when this exception is thrown](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/logging.html), and add here too please?

**Comment by kabzit13** [comment]
@russcam , we are trying to reproduce with debug information. Is that what you need?

**Comment by russcam** [comment]
Yes please, would like to see the response JSON

**Comment by Mpdreamz** [comment]
@kabzit13 in addition to @russcam's request if you run with: 

```csharp
new ConnectionSettings(...)
	.MemoryStreamFactory(new MemoryStreamFactory())
	...
```

Can you still reproduce this behaviour?

**Comment by kabzit13** [comment]
I have finally was able to reproduce it. 
I have to start indexing all lot of data in same time firing request to old indexes. 
There is only small set of additional info. 
Debug info: # FailureReason: Unrecoverable/Unexpected BadResponse while attempting POST on https://vpc-*****.us-east-1.es.amazonaws.com/lot-index/_search?pretty=true&typed_keys=true

I also noticed that master node not available sometime. 
![image](https://user-images.githubusercontent.com/8246484/81919591-50d78e80-95d8-11ea-8ad4-7b3c4821355d.png)

I have 2 nodes in setup and not a dedicated master node. 
All this is running on AWS Elasticsearch service, maybe It was worth mentioning from the beginning.

**Comment by russcam** [comment]
Thanks for the update, @kabzit13.  Do you have the captured response bytes/text/json too?

**Comment by kabzit13** [comment]
@russcam 
I am getting exception at this moment. 
 try
            {
                return await client.SearchAsync(func);
            }
            catch (UnexpectedElasticsearchClientException e)
            {
                Console.WriteLine($"[ERROR]. Unexpected error: {e}");
                Console.WriteLine($"[ERROR]. Debug info: {e.DebugInformation}");
                throw;
            }
And from this I have only this log.
[ERROR]. Unexpected error: Elasticsearch.Net.UnexpectedElasticsearchClientException: expected:'"', actual:'
', at offset:61
---> Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'"', actual:'
', at offset:61
at Elasticsearch.Net.Utf8Json.JsonReader.ReadStringSegmentRaw()
at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
at Elasticsearch.Net.Utf8Json.JsonSerializer.DeserializeAsync[T](Stream stream, IJsonFormatterResolver resolver)
at Elasticsearch.Net.ResponseBuilder.SetBodyAsync[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType, CancellationToken cancellationToken)
at Elasticsearch.Net.ResponseBuilder.ToResponseAsync[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType, CancellationToken cancellationToken)
at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
--- End of inner exception stack trace ---
at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
at Nest.ElasticClient.SearchAsync[TDocument](ISearchRequest request, CancellationToken ct)
at Nest.ElasticClient.SearchAsync[TDocument](Func`2 selector, CancellationToken ct)
at GlobalSearch.Infrastructure.Helpers.DefaultNestSearchExecutor.Search[T](ValueTuple`8 searchParams) in C:\_agents\r\r001\_work\7\s\src\globalsearch\Infrastructure\Helpers\DefaultNestSearchExecutor.cs:line 52
[ERROR]. Debug info: # FailureReason: Unrecoverable/Unexpected BadResponse while attempting POST on https://vpc-****.us-east-1.es.amazonaws.com/lot-index/_search?pretty=true&typed_keys=true
- [1] BadResponse: Node: https://vpc-****.us-east-1.es.amazonaws.com/ Exception: JsonParsingException Took: 00:00:04.0384831
# Audit exception in step 1 BadResponse:
Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'"', actual:'
', at offset:61
at Elasticsearch.Net.Utf8Json.JsonReader.ReadStringSegmentRaw()
at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
at Elasticsearch.Net.Utf8Json.JsonSerializer.DeserializeAsync[T](Stream stream, IJsonFormatterResolver resolver)
at Elasticsearch.Net.ResponseBuilder.SetBodyAsync[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType, CancellationToken cancellationToken)
at Elasticsearch.Net.ResponseBuilder.ToResponseAsync[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType, CancellationToken cancellationToken)
at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
# Inner Exception: expected:'"', actual:'
', at offset:61
Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'"', actual:'
', at offset:61
at Elasticsearch.Net.Utf8Json.JsonReader.ReadStringSegmentRaw()
at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
at Elasticsearch.Net.Utf8Json.JsonSerializer.DeserializeAsync[T](Stream stream, IJsonFormatterResolver resolver)
at Elasticsearch.Net.ResponseBuilder.SetBodyAsync[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType, CancellationToken cancellationToken)
at Elasticsearch.Net.ResponseBuilder.ToResponseAsync[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType, CancellationToken cancellationToken)
at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
# Exception:
Elasticsearch.Net.UnexpectedElasticsearchClientException: expected:'"', actual:'
', at offset:61
---> Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'"', actual:'
', at offset:61
at Elasticsearch.Net.Utf8Json.JsonReader.ReadStringSegmentRaw()
at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
at Elasticsearch.Net.Utf8Json.JsonSerializer.DeserializeAsync[T](Stream stream, IJsonFormatterResolver resolver)
at Elasticsearch.Net.ResponseBuilder.SetBodyAsync[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType, CancellationToken cancellationToken)
at Elasticsearch.Net.ResponseBuilder.ToResponseAsync[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType, CancellationToken cancellationToken)
at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
--- End of inner exception stack trace ---
at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
at Nest.ElasticClient.SearchAsync[TDocument](ISearchRequest request, CancellationToken ct)
at Nest.ElasticClient.SearchAsync[TDocument](Func`2 selector, CancellationToken ct)
at GlobalSearch.Infrastructure.Helpers.DefaultNestSearchExecutor.Search[T](ValueTuple`8 searchParams) in C:\_agents\r\r001\_work\7\s\src\globalsearch\Infrastructure\Helpers\DefaultNestSearchExecutor.cs:line 52
expected:'"', actual:'
', at offset:61: UnexpectedElasticsearchClientException
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   at Nest.ElasticClient.SearchAsync[TDocument](ISearchRequest request, CancellationToken ct)
   at Nest.ElasticClient.SearchAsync[TDocument](Func`2 selector, CancellationToken ct)
   at GlobalSearch.Infrastructure.Helpers.DefaultNestSearchExecutor.Search[T](ValueTuple`8 searchParams) in C:\_agents\r\r001\_work\7\s\src\globalsearch\Infrastructure\Helpers\DefaultNestSearchExecutor.cs:line 52
   at GlobalSearch.Services.SearchProcessor.SearchLots(LotSearchRequestDto request) in C:\_agents\r\r001\_work\7\s\src\globalsearch\Services\SearchProcessor.cs:line 75
   at GlobalSearch.Handlers.LotSearchProxyHandler(LotSearchRequestDto request, ILambdaContext context) in C:\_agents\r\r001\_work\7\s\src\globalsearch\Handlers.cs:line 35
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

   at Elasticsearch.Net.Utf8Json.JsonReader.ReadStringSegmentRaw()
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.DeserializeAsync[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.ResponseBuilder.SetBodyAsync[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType, CancellationToken cancellationToken)
   at Elasticsearch.Net.ResponseBuilder.ToResponseAsync[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType, CancellationToken cancellationToken)
   at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)

END RequestId: b41630f6-1196-48d6-b9ba-eb65c4d8852c

is there any exact property of exception that you would like to see? 
Or maybe you can point me to someplace where I can find how to get this info when I am getting an exception?

**Comment by russcam** [comment]
> is there any exact property of exception that you would like to see?

We really need to be able to see the response bytes/JSON, to understand whether the deserialization is failing due to invalid JSON returned or if it is a legitimate bug in `DynamicMethodAnonymousFormatter<T>.Deserialize()`. 

The response bytes/JSON can be captured with a proxy in between the client and Elasticsearch e.g. [using something like Fiddler](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/logging-with-fiddler.html), or should be able to capture them by [setting `DisableDirectStreaming()`, which should then include them in `.DebugInformation`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/debug-information.html).

**Comment by kabzit13** [comment]
@russcam I have disabled direct streaming,  and all debug info was included in my message before. Unfortunately I am not able to use Fidler, as my code executes on AWS Lambda. But I have found that after I have switched from SearchAsync to sync call this issue stop appearing. And also timeouts starting to appear less often. I will try to get more data, but for now, that is all I got.

**Comment by iam-black** [comment]
> All this is running on AWS Elasticsearch service, maybe It was worth mentioning from the beginning.

You are probably getting Elasticsearch engine exception in response body. You should check AWS ES "Error logs" to see what's going on.
![Annotation 2020-07-17 230458](https://user-images.githubusercontent.com/8601553/87828445-9e48d400-c885-11ea-83b8-c0e146a6e7fd.png)


I have encountered the same error with NEST and AWS Elasticsearch in application logs.
`expected:'"', actual:' ', at offset:61: UnexpectedElasticsearchClientException`

Error logs in my case 
`org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:314) [elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:139) [elasticsearch-7.4.2.jar:7.4.2]`
.......   
`Caused by: org.elasticsearch.ElasticsearchException: Trying to create too many scroll contexts. Must be less than or equal to: [500]. This limit can be set by changing the [search.max_open_scroll_context] setting.`

**Comment by russcam** [comment]
@kabzit13 is this issue happening with AWS Elasticsearch?

**Comment by kabzit13** [comment]
Yes, It is.

**Comment by russcam** [comment]
We have seen issues with AWS Elasticsearch with other official clients (https://github.com/elastic/elasticsearch-js/issues/1088) whereby it appears, under certain conditions, that the response sent back from AWS Elasticsearch is malformed JSON. 

My current suspicion is that you're seeing the same issue, but with the .NET client. If you are able to capture the response bytes/JSON, it would be possible to confirm this.

**Comment by russcam** [comment]
Hi @kabzit13, I wondered if you have had a chance to look at this further? If you're able to capture the response bytes/JSON and share, we'd be able to investigate further.

**Comment by WarrenFerrell** [comment]
We were having this issue as well when our cluster health was red. I was not able to get the response from registering to OnRequestCompleted (died before getting there) but the cluster was only returning 5XXs based on the AWS logs. Our problem appears our cluster size being too small. I captured a request via postman and this is the 503 with `application/json` body (The problem is extremely likely to be the trailing comma). So it's AWS fault but it might be nice to return a more user friendly exception.

`{
  "message": "No server available to handle the request",
}
`

**Comment by IhnatKlimchuk** [comment]
Hi Everyone,
Faced with the same issue, and unfortunately it's very critical. I'm using client against AWS elastic, so in theory I can collect data you may need for that issue. 

Can you please list what data you need, as I can try to reproduce issue locally?

**Comment by stevejgordon** [comment]
Hi @IhnatKlimchuk. Apologies for the delay. This slipped past me. We need to see a full example of the response bytes being returned from the server so that we can identify the root cause. If you're able to capture that, it would be much appreciated.

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?

**Comment by journey191** [comment]
Exception:
```
Elasticsearch.Net.UnexpectedElasticsearchClientException: expected:',', actual:'"application/pdf; version=1.7"', at offset:369
```

The Response JSON:
```
{
"took": 3,
"timed_out": false,
"_shards": {
"total": 6,
"successful": 6,
"skipped": 0,
"failed": 0
},
"hits": {
"total": {
"value": 1,
"relation": "eq"
},
"max_score": 1,
"hits": [
{
"_index": "ontall_documents",
"_id": "080cf75e-a269-ab98-9d1b-3a027eae3507",
"_score": 1,
"_source": {
"highlight": [ ],
"attachment": {
"date": "2022-03-08T08:00:18Z",
"content_type": "application/pdf",
"author": "u1",
"format": "application/pdf; version=1.7",
"modified": "2022-03-08T08:00:18Z",
"language": "lt",
"creator_tool": "WPS 文字",
"content": "参考已实施项目工作机制： 1. 双方沟通机制 （1）建立微信或 QQ 群，双方所有参与人员加入。日常沟通、文件资料等在群里共享。 双方主要人员不定期以线上会议方式交流问题和解决方案，并在会后编写会议纪要。会议纪 要上传到群文件。",
"content_length": 129
},
"id": "080cf75e-a269-ab98-9d1b-3a027eae3507",
"title": "测试文档",
"content": "JVBERi0x..."
}
}
]
}
}
```

**Comment by andrewreyes** [comment]
We encounter similar issue after we upgrade to ES7, the same request works fine with ES 6

Elasticsearch.Net.UnexpectedElasticsearchClientException: expected:'Number Token', actual:'"-Infinity"', at offset:400
 ---> Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'Number Token', actual:'"-Infinity"', at offset:400
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadDouble()
   at Elasticsearch.Net.Utf8Json.Formatters.NullableDoubleFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
