### ISSUE TITLE
NEST version: 7.6.1 is very very slow

### ISSUE THREAD

**Issue by sadaqatbukhari** [elastic/elasticsearch-net#4739]
Testing Environment Laptop is 4 core CPU, 16GB RAM and 512GB SSD.

Elasticsearch is running single node on windows server 2012 VM. This VM has 16GB RAM and 4 core CPU.

The Elasticsearch have 18 GB data. I am using NEST version: 7.6.1 for indexing and query
Same query with Postman is taking only 1221 ms but with NEST client it is taking about 10-13 seconds for 10000 size.
When I decrease the page size query time is decreased for 3000 it is taking almost 5 seconds.

Benchmarks of same query for REST Client and NEST Client.
Nest client took: 12384 ms
Nest client documents: 10000
Rest client took: 1966 ms

I have build Elasticsearch repository in asp.net core 3.1.

Settings of Client

` var settings = new ConnectionSettings(new Uri(url))
.EnableDebugMode()
        .DefaultIndex(defaultIndex);
        var client = new ElasticClient(settings);
        services.AddSingleton<IElasticClient>(client);`
Get List Method

```
public List GetList(SearchDescriptor descriptor, string index = null) where T : class, 
 ElasticBaseModel
{
descriptor.From(0).Take(scrollPageSize).Scroll("5m");
        index = index ?? _options.DefaultIndex;
        descriptor = descriptor.Index(index);
        var searchResponse = _client.Search<T>(descriptor);
        var results = new List<T>();
        while (true)
        {
            if (!searchResponse.IsValid || string.IsNullOrEmpty(searchResponse.ScrollId))
                throw new Exception($"Search error: {searchResponse.ServerError.Error.Reason}");

            if (!searchResponse.Documents.Any())
                break;
            results.AddRange(searchResponse.Documents);
            searchResponse = _client.Scroll<T>("5m", searchResponse.ScrollId);
        }

        _client.ClearScroll(new ClearScrollRequest(searchResponse.ScrollId));
        return results;
    }
```

This query took 11.5 seconds.
Below is Debug Info from NEST client.

Valid NEST response built from a successful (200) low level call on POST: /position/_search?pretty=true&error_trace=true&typed_keys=true&scroll=5m
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://172.18.3.161:9200/ Took: 00:00:08.9185311
# Request:
{"from":0,"query":{"bool":{"filter":[{"bool":{"must":[{"geo_bounding_box":{"boost":1.1,"validation_method":"coerce","type":"indexed","location":{"bottom_right":{"lat":47.6125,"lon":39.575},"top_left":{"lat":64.8875,"lon":-17.075}}}}],"should":[{"bool":{"filter":[{"bool":{"should":[{"bool":{"must":[{"terms":{"machine":["6F1401","6G1519"]}},{"range":{"time":{"gte":"2019-09-01T00:00:00Z","lte":"2019-09-30T23:59:59.9999999Z"}}}]}}]}}]}}]}}]}},"size":10000}
# Response:
{
  "_scroll_id" : "DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAHY_0WVlFRQlpTazJSUjZKbjJ4OGplQlJ3UQ==",
  "took" : 2876,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 59128374,
      "relation" : "eq"
    },
    "max_score" : 0.0,
    "hits" : [
      {
        "_index" : "position",
        "_type" : "_doc",
        "_id" : "6H1561_1541153618.03",
        "_score" : 0.0,
        "_source" : {
          "id" : "6H1561_1541153618.03",
          "time" : "2018-11-02T10:13:38.0300000Z",
          "machine" : "6H1561",
          "orderid" : 56,
          "bunkerunloading" : false,
          "operatingmode" : 1,
          "depthguidanceon" : true,
          "engineon" : true,
          "istimelygap" : false,
          "identifier" : 6852,
          "location" : {
            "lat" : 50.613713333,
            "lon" : 4.014146667
          }
        }
      },

**Comment by russcam** [comment]
Please can you properly format the code in the issue. It'll make it much more readable and approachable. Thanks!

> Same query with Postman is taking only 1221 ms but with NEST client it is taking about 10-13 seconds for 10000 size.

This is somewhat of an apples to oranges comparison; Postman isn't performing any kind of serialization/deserialization so I'd expect it to be faster when showing the response as text.

> This query took 11.5 seconds.

The example presented is performing multiple requests using the Scroll API. Is 11.5 seconds the total time for all scroll requests? What does the search query look like (the JSON is shown but the NEST code isn't)? How many documents are returned in each scroll response?

> Benchmarks of same query for REST Client and NEST Client.
> Nest client took: 12384 ms
> Nest client documents: 10000
> Rest client took: 1966 ms

An example project that clearly demonstrates these differences would be really helpful. Without knowing how the comparison is being made, it's difficult to comment on the numbers presented.

**Comment by sadaqatbukhari** [comment]
Thanks for reply. 

> This is somewhat of an apples to oranges comparison; Postman isn't performing any kind of serialization/deserialization so I'd expect it to be faster when showing the response as text.
This time is first response not whole scroll, each scroll is taking same time 10-12 seconds.


> How many documents are returned in each scroll response?
Total record were 78282 and each scroll is returning 10000 and each request is taking same time about 10-12 seconds.

Attached is console application which we are using for bench marking.
[ConsoleApp1.zip](https://github.com/elastic/elasticsearch-net/files/4729500/ConsoleApp1.zip)

Please let me know if you need more information

**Comment by russcam** [comment]
I've run the console application and it throws an exception

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ConsoleApp1.Program.GetWithRestClient() in \ConsoleApp1\ConsoleApp1\Program.cs:line 101
   at ConsoleApp1.Program.Main(String[] args) in \ConsoleApp1\ConsoleApp1\Program.cs:line 24
```

There look to be a number of issues with the example

1. The example does not create an index and does not index any data to return
2. Calling three different implementations in `Main()` and comparing them will not provide an accurate reflection because Elasticsearch can and will cache queries and data, so subsequent calls with the same queries will be faster. Each comparison needs to be performed in isolation, against a new instance of Elasticsearch, or at least an instance where index is deleted and recreated before subsequent runs
3. The comparison between the low level client and others is not a fair comparison because it returns a byte array whereas NEST and RestClient are both JSON parsing a response
4. A single run of each is insufficient to draw comparisons because there may be factors that negatively impact a single run of one thing being compared but not others e.g. Windows defender starts scanning local disk and consuming CPU, negatively impacting a run for say RestClient, but not others. To benchmark, many runs of each should be taken and then the mean, percentiles, standard deviation and variance taken. In addition, in the case of NEST, the very first call to the client will be relatively slower than subsequent calls because it dynamically generates type specific serializers on the first call and caches them.
5. RestClient and NEST are performing different queries - the former initiates a scroll whilst the latter doesn't.

If I add some data to search with

```c#
var settings = new ConnectionSettings(new Uri(url))
    .DefaultIndex("position");
var nestClient = new ElasticClient(settings);

if (nestClient.Indices.Exists("position").Exists)
{
    nestClient.Indices.Delete("position");
}

nestClient.Indices.Create("position", c => c
    .Map<ElasticPosition>(m => m.AutoMap())
);

var random = new Random();

IEnumerable<ElasticPosition> documents()
{
    for (int i = 0; i < 10000; i++)
    {
        yield return new ElasticPosition
        {
            id = i.ToString(),
            location = new Location
            {
                lat = random.NextDouble() * (55.146307 - 53.131222) + 53.131222,
                lon = random.NextDouble() * (9.33574 - 6.25421) + 6.25421,
            }
        };
    }
}

nestClient.BulkAll(documents(), b => b
    .Index("position")
    .RefreshOnCompleted()
).Wait(TimeSpan.FromMinutes(5), response => {});
```

and change the query to swap the lon coordinates of `top_left` and `bottom_right`

```c#
static string query = @"{""bool"": {""must"": [ {""geo_bounding_box"" : {""location"" : {""top_left"" : {""lat"" : 55.146307,""lon"" : 6.25421},""bottom_right"" : {""lat"" : 53.131222, ""lon"" : 9.33574  }}}}]}}";
```

Then the results I get are

```
Custom serialization took: 457
Rest client took: 734
Low level client took: 148
Nest client took: 220
```

So it looks like the low level client is fastest, which is unsurprising as it returns a byte array, followed by NEST. As suggested though, this doesn't look to be a fair comparison. Using something like [Benchmark.NET](https://github.com/dotnet/BenchmarkDotNet), a more fair comparison could be achieved.

**Comment by sadaqatbukhari** [comment]
> So it looks like the low level client is fastest, which is unsurprising as it returns a byte array, followed by NEST. As suggested though, this doesn't look to be a fair comparison. Using something like [Benchmark.NET](https://github.com/dotnet/BenchmarkDotNet), a more fair comparison could be achieved.

Thanks a lot with detail reply. I will give you details on this performance issue and with detailed sample code. And I will also share Benchmark using your suggested tool.

**Comment by russcam** [comment]
@sadaqatbukhari There is a [benchmarking project in this solution](https://github.com/elastic/elasticsearch-net/tree/master/tests/Tests.Benchmarking) that could help you get started with this. It has Benchmark.NET plumbing and setup already in place

**Comment by russcam** [comment]
We’re closing this issue due to inactivity; if you’re still in need of resolution, feel free to re-open with the additional details and we'd be glad to help you out 👍
