### ISSUE TITLE
RequestResponseSerializer.Deserialize<SearchRequest> fails with short order syntax

### ISSUE THREAD

**Issue by Hypopheralcus** [elastic/elasticsearch-net#4797]
**NEST/Elasticsearch.Net version**:
7.6.2
**Elasticsearch version**:
7.6.2

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
` var queryData = "{ \"query\": { \"bool\": { \"must\": [ { \"range\": { \"RequestDate\": { \"time_zone\": \"+02:00\", \"gte\": \"2020-06-19T22:00:00.000Z\", \"lte\": \"2020-06-22T21:59:59.999Z\" } } }, { \"match_all\": {} } ] } }, \"sort\": [ { \"ReportDate\": \"desc\" } ], \"from\": 0, \"size\": 50 }";` 
` var elasticClient = new ElasticClient();` 
` elasticClient.RequestResponseSerializer.Deserialize<SearchRequest>(new MemoryStream(Encoding.UTF8.GetBytes(queryData)));`

**Expected behavior**
Same behaviour as with { "ReportDate": {"order": "desc" } }. A working deserialization. Based on the documentation, it is an valid syntax. See: https://www.elastic.co/guide/en/elasticsearch/reference/7.6/search-request-body.html#request-body-search-search-after

**Provide `DebugInformation` (if relevant)**:
{"expected:'{', actual:'\"desc\"', at offset:215"}

   at Elasticsearch.Net.Utf8Json.JsonReader.ReadIsBeginObjectWithVerify() in C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Utf8Json\JsonReader.cs:line 479
   at Nest.SortFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver) in C:\Users\russc\source\elasticsearch-net\src\Nest\CommonOptions\Sorting\SortFormatter.cs:line 65
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver) in C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Utf8Json\Formatters\CollectionFormatters.cs:line 248
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver) in C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Utf8Json\JsonSerializer.cs:line 262
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver) in C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Utf8Json\JsonSerializer.cs:line 323
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream) in C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Serialization\DiagnosticsSerializerProxy.cs:line 78
   at DNMove.Web.DNMoveBaseService.ComElasticsearch(String s1, String s2) in C:\Users\pichlm\Source\Repos\bio.net\backend\DNMove.Web\Elasticsearch\DNMoveElasticsearchService.cs:line 49

**Comment by russcam** [comment]
Thanks for opening, @Hypopheralcus. I've opened https://github.com/elastic/elasticsearch-net/pull/4806 to allow the client to deserialize the short form sort values. Note that the client will always serialize sort values using the long form.
