### ISSUE TITLE
SSL Connection could not be established 

### ISSUE THREAD

**Issue by nidhisht** [elastic/elasticsearch-net#5146]
**NEST/Elasticsearch.Net version**: 7.10

**Elasticsearch version**:

**Description of the problem**:
Facing challenges in establishing connection to secured Elastic API (HTTPS) from NEST. 

Exception details & source code are mentioned below.

**Steps to reproduce**:
 1. Copy below source code to dotnet core console application
 2. Modify the values of variables: url, index, username & password
 3. Ensure that the url is HTTPS

**Source Code**:
```
class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Elastic Console App: (Elastic Api Test Utility)");
            Console.WriteLine("-----------------------------------------------");

            string url = "https://drme***.i**s.***.com:9200/";
            string index = "logstash-app*";
            string userName = "myusername";
            string password = "mypassword";

            try
            {
                var settings = new ConnectionSettings(new Uri(url))
                         .DefaultIndex(index)
                         .BasicAuthentication(userName, password)
                         .ThrowExceptions()
                         .IncludeServerStackTraceOnError()
                         .ServerCertificateValidationCallback((sender, certificate, chain, errors) => true); ;

                var client = new ElasticClient(settings);

                var searchRespons = client.Search<object>(s => s.Size(1));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            Console.Read();
        }
    }
```

**Exception**
Elasticsearch.Net.ElasticsearchClientException: The SSL connection could not be established, see inner exception.. Call: Status code unknown from: POST /logstash-app%2A/_search?error_trace=true&typed_keys=true
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.HandleElasticsearchClientException(RequestData data, Exception clientException, IElasticsearchResponse response)
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Nest.ElasticClient.DoRequest[TRequest,TResponse](TRequest p, IRequestParameters parameters, Action`1 forceConfiguration)
   at Nest.ElasticClient.Search[TDocument](ISearchRequest request)
   at Nest.ElasticClient.Search[TDocument](Func`2 selector)
   at ElasticConsoleApp.Program.Main(String[] args) in C:\Temp\ElasticConsoleApp\Program.cs:line 31

**Comment by stevejgordon** [comment]
@nidhisht From an initial review, this appears to be a server side issue, based on the "Authentication failed because the remote party has closed the transport stream." message. Can you please confirm that you able to successfully reach this server via a browser when using HTTPS?

I tested this locally using 7.10.0 and I was able to communicate and authenticate over HTTPS to Elasticsearch without any issues.

**Comment by stevejgordon** [comment]
Also worth checking that at point of termination it's using a not deprecated TLS version, supported on the client host.

**Comment by nidhisht** [comment]
@stevejgordon your initial review was spot on! I am not able to reach the server through browser or through curl.

Will fix that first and try the utility. Thanks for help!

**Comment by stevejgordon** [comment]
Thanks for updating us @nidhisht. I'll close this issue for the time being since I've tested this works locally.
