### ISSUE TITLE
Can't handle F# lists

### ISSUE THREAD

**Issue by dharmaturtle** [elastic/elasticsearch-net#5256]
The latest version of Nest/ElasticSearch.net (7.10) can't handle F# lists.

The following test fails:

```f#
type SomeNumbers = { Numbers: int list }
[<Fact>]
let ``fails`` () =
    use settings =
        (new ConnectionSettings(Uri("http://localhost:9200/")))
            .DefaultIndex("anyindex")
    
    let client = ElasticClient(settings)

    let _ = client.IndexDocument({Numbers = [1;2] })
    ()
```

Stacktrace:
```
Elasticsearch.Net.UnexpectedElasticsearchClientException: The input list was empty.
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in E:\Projects\Elastic\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 95
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in E:\Projects\Elastic\elasticsearch-net\src\Elasticsearch.Net\ElasticLowLevelClient.cs:line 70
   at Nest.ElasticClient.DoRequest[TRequest,TResponse](TRequest p, IRequestParameters parameters, Action`1 forceConfiguration) in E:\Projects\Elastic\elasticsearch-net\src\Nest\ElasticClient.cs:line 135
   at Nest.ElasticClient.Index[TDocument](IIndexRequest`1 request) in E:\Projects\Elastic\elasticsearch-net\src\Nest\ElasticClient.NoNamespace.cs:line 672
   at Nest.ElasticClient.Index[TDocument](TDocument document, Func`2 selector) in E:\Projects\Elastic\elasticsearch-net\src\Nest\ElasticClient.NoNamespace.cs:line 658
   at Nest.ElasticClient.IndexDocument[TDocument](TDocument document) in E:\Projects\Elastic\elasticsearch-net\src\Nest\Document\Single\Index\ElasticClient-Index.cs:line 38
   at ElseClientTests.fails() in C:\Code\Personal\CardOverflow\CardOverflow.Test\ElseClientTests.fs:line 54
System.InvalidOperationException: The input list was empty.
   at Microsoft.FSharp.Collections.FSharpList`1.get_Head() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 3694
   at Serialize(Byte[][] , Object[] , JsonWriter& , FSharpList`1 , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Serialize(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)
   at Serialize(Byte[][] , Object[] , JsonWriter& , FSharpList`1 , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Serialize(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)
   at Serialize(Byte[][] , Object[] , JsonWriter& , FSharpList`1 , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Serialize(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)
   at Serialize(Byte[][] , Object[] , JsonWriter& , SomeNumbers , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Serialize(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.SerializeUnsafe[T](T value, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Serialize[T](Stream stream, T value, IJsonFormatterResolver resolver)
   at Nest.DefaultHighLevelSerializer.Serialize[T](T data, Stream writableStream, SerializationFormatting formatting)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Serialize[T](T data, Stream stream, SerializationFormatting formatting)
   at Nest.IndexDescriptor`1.Nest.IProxyRequest.WriteJson(IElasticsearchSerializer sourceSerializer, Stream stream, SerializationFormatting formatting)
   at Nest.ProxyRequestFormatterBase`2.Serialize(JsonWriter& writer, TRequestInterface value, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.SerializeUnsafe[T](T value, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Serialize[T](Stream stream, T value, IJsonFormatterResolver resolver)
   at Nest.DefaultHighLevelSerializer.Serialize[T](T data, Stream writableStream, SerializationFormatting formatting)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Serialize[T](T data, Stream stream, SerializationFormatting formatting)
   at Elasticsearch.Net.SerializableData`1.Write(Stream writableStream, IConnectionConfigurationValues settings)
   at Elasticsearch.Net.HttpConnection.SetContent(HttpRequestMessage message, RequestData requestData)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
```

I see from [this issue](https://github.com/elastic/elasticsearch-net/issues/4195) that better F# interop is on your list of things to do for 8.x, so here's something else to add to the pile.

In the meantime, do you have any advice on workarounds? I'm reading up on [custom serialization](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html), and I have an F# friendly serializer in mind, but I'm not sure if that's a possible solution.

Thanks!

**Comment by stevejgordon** [comment]
@dharmaturtle I'm afraid I personally don't do any F# development so I'm not clear on what options there are here at the moment. I need to investigate that further and learn about F# interop of the library. @Mpdreamz - Any thoughts?

**Comment by dharmaturtle** [comment]
I dug a bit and it turns out Newtonsoft can handle F# just fine. Please feel free to close this issue or leave it open to track the the F# interop.

For future googlers or whatever: install [NEST.JsonNetSerializer](https://www.nuget.org/packages/NEST.JsonNetSerializer) and follow the directions [here](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#_jsonnetserializer). Since it was a bit tricky for me to get the syntax working, here's some sample code.

```fsharp
let sourceSerializerFactory =
    ConnectionSettings.SourceSerializerFactory
        (fun x y -> Nest.JsonNetSerializer.JsonNetSerializer.Default (x, y))
let pool = new SingleNodeConnectionPool(Uri "http://localhost:9200/")
new ConnectionSettings(pool, sourceSerializerFactory)
|> ElasticClient
```

**Comment by Mpdreamz** [comment]
Thanks @dharmaturtle! 

We love F# and aware of the interop issues, we are eager to improve this in the next major
! :cat:
