### ISSUE TITLE
.Net Core 3.1 fails unless HttpClient SocketsHttpHandler is disabled

### ISSUE THREAD

**Issue by wandrar** [elastic/elasticsearch-net#5339]
**NEST/Elasticsearch.Net version**:
7.11.1

**Elasticsearch version**:
7.10.0

When I upgrade from .net core 2 to 3.1, connection fails with error further down. This error goes away if I switch back to the old Httphandler by uncommenting (in my sample code)...

AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);

If I upgrade to .net5.0, it doesn't work at all, even if I switch to System.Net.Http.WinHttpHandler as described in https://devblogs.microsoft.com/dotnet/net-5-new-networking-improvements/ 

**Steps to reproduce**:

```

using System;
using System.Threading.Tasks;
using Elasticsearch.Net;
using Nest;

namespace TestElastic
{
    class Program
    {
        static void Main(string[] args)
        {
            MainAsync(args).GetAwaiter().GetResult();
        }

        static async Task MainAsync(string[] args)
        {
            await Test();
        }

        public static async Task Test()
        {
            //AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
            
            var connectionPool = new SingleNodeConnectionPool(new Uri("https://<NODE>:9200"));

            var settings = new ConnectionSettings(connectionPool)
                .DefaultMappingFor<Person>(m => m.IndexName("ssl-person"))
                .BasicAuthentication("My username ", "pwd")
                .EnableDebugMode()
                .ServerCertificateValidationCallback(CertificateValidations.AllowAll);

            var client = new ElasticClient(settings);

            var person = new Person
            {
                Id = 1,
                FirstName = "Martijn",
                LastName = "Laarman"
            };

            var resp = await client.IndexDocumentAsync(person); 

            Console.WriteLine(resp.DebugInformation);
        }

        public class Person
        {
            public int Id { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
        }
    }
}

```

**Provide `DebugInformation` (if relevant)**:
BadRequest: Node: https://node:9200/ Took: 00:00:00.5999414
# OriginalException: System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)

**Comment by stevejgordon** [comment]
@wandrar Based on your stack trace, the message "The response ended prematurely" indicates that the connection was closed by the server before HttpClient could read the expected bytes. 

I've tested the repro code and I'm unable to reproduce the issue which leads me to suspect configuration in the app or on the server. I don't believe this is a client bug based on the information so far, but let's see if we can get you up and running.

- Are you able to share your project (csproj) file used in your repro? I'd like to confirm how that's configured.
- Which OS platform are you running this on?
- It's worth verifying if you can make an SSL HTTP call to a public website, via HttpClient on your system?
- Are you able to reach your server at the same URL using CURL or via the browser from the device where you are running this sample?

**Comment by wandrar** [comment]
Hi, I'll assume it's my environment then. Save wasting your time I'll close for now and investigate network drops etc
Thanks for looking

Project file below. 
OS = windows.
Httpclieint to public website (https) works.
Yes can reach server via website.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="NEST" Version="7.11.1" />
  </ItemGroup>
</Project>
```

**Comment by stevejgordon** [comment]
That all looks standard, thanks @wandrar. It's possible a proxy is perhaps modifying the response in some way and `SocketsHttpHandler` is less forgiving. It might be worth running Fiddler in between to see what the responses look like. Additionally, it's worth running Elasticsearch locally using Docker to validate locally? That may help narrow down where the issue is.

**Comment by wandrar** [comment]
Thanks Steve. Definitely proxy - have recreated with HttpClient outside of Elastic - I think possibly different behaviour auto-discovering proxy in core 3.1 vs 2.2 - just on my machine. Nothing to do with Elastic anyway and I can use the various settings to disable it so all good now thanks.

________________________________
