### ISSUE TITLE
Unable to Deserialization custom date format

### ISSUE THREAD

**Issue by subhashMathuri** [elastic/elasticsearch-net#5713]
**NEST/Elasticsearch.Net version**: 7.13.0

**Elasticsearch version**: 7.13.0

**Description of the problem including expected versus actual behavior**:
We are trying to search the document and it has a property with type date, format:"epoch_millis".  It throws error : invalid datetime format. value:1472427960000. stacktrace: `   at Elasticsearch.Net.Utf8Json.Formatters.ISO8601DateTimeFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.SourceFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.DeserializeAsync[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.ResponseBuilder.SetBodyAsync[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType, CancellationToken cancellationToken)
   at Elasticsearch.Net.ResponseBuilder.ToResponseAsync[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType, CancellationToken cancellationToken)
   at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)`

**Steps to reproduce**:
 1. Create a document with fields type date "format":"epoch_millis"
 2. try to search the document It throws error.

`public class SampleDocument
    {
        public string Id { get; set; }
		public DateTime TimeStamp { get; set; }
	}	
	
`

`var response = await client.SearchAsync<AuditOperationDocument>(s => s
                                        .Query(q => q
                                              .MatchPhrase(m => m
                                                      .Field(f => f.Id)
                                                      .Query("id123")
                                               )
                                            )
                                       );`

**Comment by stevejgordon** [comment]
Hi @subhashMathuri. In this example, the epoch formatted date cannot be deserialized into the `DateTime` type which is expected due to the default behaviour of the serializer. For `DateTime` properties the serializer expects an ISO8601 formatted date. If you change your property to a string or long (depending on how the data is indexed) you should be able to deserialise the document. You can then convert the epoch to a `DateTime` or `DateTimeOffset` accordingly.

For more complete control over deserialization, you may also look at using an [alternative serializer implementation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html) to fully control how data is deserialised into your POCO types.

**Comment by subhashMathuri** [comment]
Thanks @stevejgordon  👍 , but I think Elastic NEST client should support the Deserialization of custom date.

**Comment by stevejgordon** [comment]
@subhashMathuri It's not really a date though, it's a `long` representing a Unix epoch. Other serializers such as `System.Text.Json` will also throw if an epoch value is attempted to be deserialized into a `DateTime` property. In the next major version of the library, we plan to switch to `System.Text.Json` . An advantage of that change is that it should then be easier to add an attribute to the property to control formatting using the features of `System.Text.Json`.

There are various ways to address the issue already, so I don't feel the need to customise the default serialization behaviour here, since such changes affect all consumers and may result in unexpected behaviour. We already support custom serialization by providing various ways to provide your own serializer for your types which may then configure to meet your exact requirements.

A few options are:
- Design the POCO properties to match how the data is stored/formatted. 
- The field could be mapped as a suitable date format. 
- If the format of the field has to be "epoch_millis" for other reasons, you could consider adding a duplicate field with an ISO8601 formatted date that you deserialize to your POCO model.
- Configure and use a custom serializer.
