### ISSUE TITLE
CLR/Elasticsearch.Net.UnexpectedElasticsearchClientException

### ISSUE THREAD

**Issue by antarr** [elastic/elasticsearch-net#6061]
**NEST/Elasticsearch.Net version**:  NEST 7.15.2

**Elasticsearch version**: 7 on AWS 7.15 on OSX

**.NET runtime version**: 6.0.0

**Operating system version**: MacOS 12.0.1

**Description of the problem including expected versus actual behavior**:
I'm getting an unsupported version error starting the server

**Steps to reproduce**:
 1. Start Debugger in VS Code

**Expected behavior**
The server should start fine and launch a window in the browser

**Provide `appsetting.json` (if relevant)**:
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Debug"
    }
  },
  "AllowedHosts": "*",
  "elasticsearch": {
    "url": "http://localhost:9200",
    "index": "search_development"
  }
}
```

**Provide `DebugInformation` (if relevant)**:
```zsh
Exception has occurred: CLR/Elasticsearch.Net.UnexpectedElasticsearchClientException
An unhandled exception of type 'Elasticsearch.Net.UnexpectedElasticsearchClientException' occurred in Elasticsearch.Net.dll: 'Name resolved to null for the given Expression or MemberInfo.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.ArgumentException : Name resolved to null for the given Expression or MemberInfo.
   at Nest.FieldResolver.Resolve(Expression expression, MemberInfo member, Boolean toLastToken)
   at Nest.FieldResolver.Resolve(PropertyName property)
   at Nest.PropertiesFormatter.Serialize(JsonWriter& writer, IProperties value, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Nest_ITypeMappingFormatter2.Serialize(JsonWriter& , ITypeMapping , IJsonFormatterResolver )
   at Nest.ReadAsFormatter`2.SerializeInternal(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)
   at Nest.ReadAsFormatter`2.Serialize(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Nest_ICreateIndexRequestFormatter1.Serialize(JsonWriter& , ICreateIndexRequest , IJsonFormatterResolver )
   at Nest.ReadAsFormatter`2.SerializeInternal(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)
   at Nest.ReadAsFormatter`2.Serialize(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.SerializeUnsafe[T](T value, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Serialize[T](Stream stream, T value, IJsonFormatterResolver resolver)
   at Nest.DefaultHighLevelSerializer.Serialize[T](T data, Stream writableStream, SerializationFormatting formatting)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Serialize[T](T data, Stream stream, SerializationFormatting formatting)
   at Elasticsearch.Net.SerializableData`1.Write(Stream writableStream, IConnectionConfigurationValues settings)
   at Elasticsearch.Net.HttpConnection.SetContent(HttpRequestMessage message, RequestData requestData)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
```

`Extensions.cs`
```CS
public static class Extensions
{
    public static void AddElasticsearch(this WebApplicationBuilder builder, IConfiguration configuration)
    {
        var url = configuration["elasticsearch:url"];
        var defaultIndex = configuration["elasticsearch:index"];

        var settings = new ConnectionSettings(new Uri(url)).DefaultIndex(defaultIndex);

        AddDefaultMappings(settings);

        var client = new ElasticClient(settings);

        builder.Services.AddSingleton<IElasticClient>(client);

        CreateIndex(client, defaultIndex);
    }

    private static void AddDefaultMappings(ConnectionSettings settings)
    {
        settings
            .DefaultMappingFor<LegiscanModelBill>(m => m
                .Ignore(p => p.Id)
                .Ignore(p => p.CreatedAt)
                .Ignore(p => p.UpdatedAt)
            )
            .DefaultMappingFor<User>(m => m
                .Ignore(p => p.CreatedAt)
                .Ignore(p => p.EncryptedPassword)
            );
    }


    private static void CreateIndex(IElasticClient client, string indexName)
    {
        var createIndexResponse = client.Indices.Create(indexName,
            index => index.Map<LegiscanModelBill>(x => x.AutoMap())
        );
    }
}
```
`Program.cs`
```CS
using WeVote.ElasticSearch;

var builder = WebApplication.CreateBuilder(args);
builder.Services
    .AddGraphQLServer()
    .AddQueryType<Query>();


// var es_config = builder.Configuration.GetSection("elasticsearch");
builder.Services.AddElasticsearch(builder.Configuration);


var app = builder.Build();

app.MapGraphQL();

app.Run();
```

The error is being thrown from the` CreateIndex` method

**Comment by stevejgordon** [comment]
@antarr The likely cause is something in your `LegiscanModelBill` model which is causing the property name inference to fail for some reason. Are you able to share that class, please? I'll then see if I can reproduce this.

**Comment by stevejgordon** [comment]
Hi @antarr. Just checking in to see if you are still experiencing this and if so, are you able to provide the additional details requested above so I can attempt to reproduce?

**Comment by stevejgordon** [comment]
Closing due to lack of response.
