### ISSUE TITLE
The semaphore has been disposed exception - introduced between 7.13.2 and 7.14.0, present in latest

### ISSUE THREAD

**Issue by shadowfoxish** [elastic/elasticsearch-net#6508]
**NEST/Elasticsearch.Net version**:
All versions starting at 7.14.0

**Elasticsearch version**:
7.16

**.NET runtime version**:
Core 3.1

**Operating system version**:
Windows 10

**Description of the problem including expected versus actual behavior**:
I attempted to upgrade my project from NEST v 7.9 to 7.17.4, and search feature is now broken. I narrowed the issue down to some change made in the 7.14.0 release. I am able to use 7.13.2 without issue, anything more recent doesn't work, and fails with the same error.

The stack trace is as follows:

```
2022-07-08 11:29:01.2689 WARN [   18] AhAPI.Startup.ConfigureServices System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.WaitAsync(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.SemaphoreSlim.WaitAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Elasticsearch.Net.RequestPipeline.FirstPoolUsageAsync(SemaphoreSlim semaphore, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   at Nest.ElasticClient.SearchAsync[TDocument](ISearchRequest request, CancellationToken ct)
   at Nest.ElasticClient.SearchAsync[TDocument](Func`2 selector, CancellationToken ct)
   at Airline.BusinessLogic.AirlineWeb.CategorySearchBL.PerformChildCategorySearch(CategorySearchRequest search, CategoryModel category) in C:\Code\airline-api\Airline.BusinessLogic\AirlineWeb\CategorySearchBL.cs:line 137
   at Airline.BusinessLogic.AirlineWeb.CategorySearchBL.SearchCategories(CategorySearchRequest searchInput) in C:\Code\airline-api\Airline.BusinessLogic\AirlineWeb\CategorySearchBL.cs:line 57
   at Models.GraphQL.AppQuery.<>c.<<SetupQueryCategorySearch>b__7_0>d.MoveNext() in C:\Code\airline-api\Models.GraphQL\AppQuery.cs:line 273
```

Them code that builds the search query is really complicated and spread out over a lot of method calls, and is probably too much to post here, however the resulting json object isn't too bad and I can put that here.

```json
{
    "aggs": {
        "categoryPaths": {
            "terms": {
                "field": "categoryPaths.keyword",
                "min_doc_count": 1,
                "size": 250
            }
        }
    },
    "query": {
        "script_score": {
            "query": {
                "bool": {
                    "must": [{
                            "bool": {
                                "minimum_should_match": 1,
                                "should": [{
                                        "term": {
                                            "categoryPaths.keyword": {
                                                "value": "/4197/"
                                            }
                                        }
                                    }, {
                                        "prefix": {
                                            "categoryPaths.keyword": {
                                                "value": "/4197/"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    ],
                    "must_not": [{
                            "term": {
                                "isRestricted": {
                                    "value": true
                                }
                            }
                        }
                    ]
                }
            },
            "script": {
                "source": "_score + Math.log10((doc['relevancy'].size() == 0 ? 0 : doc['relevancy'].value) + 1) * 10"
            }
        }
    },
    "size": 0
}
```

The core code that makes this json is:
```C#
        private async Task<ISearchResponse<Dictionary<string, object>>> PerformChildCategorySearch(CategorySearchRequest search, CategoryModel category)
        {
            ElasticClient elasticClient = GetElasticSearchClient();

            var result = await elasticClient.SearchAsync<Dictionary<string, object>>(r =>
            {
                /**
                 * The Search Term component.
                 */
                var query = GetSearchQuery(r, search, category, isDescendantSearch: true);

                /**
                 * The Category Aggregations component.
                 */
                var aggregationTerms = new List<AggregationContainer>();

                //Add the brand_name aggregation
                aggregationTerms.Add(CreateKeywordAggregation(SearchIndexKeys.CategoryPaths, false, 250));

                query = query.Aggregations(aggregationTerms.ToDictionary(a => a.Terms.Name, a => a));

                query.Size(0);

                var queryJSON = elasticClient.RequestResponseSerializer.SerializeToString(query);

                return query;
            });

            return result;
        }
```

**Comment by stevejgordon** [comment]
Hi, @shadowfoxish.

Thanks for raising this issue. The search functionality is heavily tested so my suspicion at this point is it may be something to do with the usage in the application code. Are you reusing a single instance of the `ElasticClient`? Is anything in your code disposing of the `ConnectionSettings`? If the settings get disposed at any point, that would trigger the disposal of the `SemaphoreSlim` we use for bootstrap locking. Any client instance using those settings after disposal could trigger this exception to occur. That would be the first thing I would recommend reviewing.

**Comment by shadowfoxish** [comment]
Thanks @stevejgordon It looks like the settings are indeed being created for each search request and then disposed shortly after. I will look into refactoring this. Is this ConnectionSettings object safe to have as a singleton, or should it be created new each time a search is requested? I think what I'd prefer to do is put both of these as dependencies and let the DI framework provide scoped instances or singletons, based on best practices.

```C#
        protected ElasticClient GetElasticSearchClient()
        {
            using var connectionSettings = new ConnectionSettings(new Uri(_elasticSearchConfig.Uri));

            var elasticClient = new ElasticClient(connectionSettings);

            return elasticClient;
        }
```

**Comment by stevejgordon** [comment]
@shadowfoxish We recommend that the same `ElasticClient` instance be reused and treated as a singleton for the app lifetime. As a result, the same `ConnectionSettings` will be reused.

**Comment by shadowfoxish** [comment]
That was it! Problem solved, thank you Mr Wizard.
