### ISSUE TITLE
GetDataStreamAsync throws JSON value could not be converted to Elastic.Clients.Elasticsearch.HealthStatus

### ISSUE THREAD

**Issue by no1melman** [elastic/elasticsearch-net#7236]
**Elastic.Clients.Elasticsearch version**: 8.0.5

**Elasticsearch version**: 8.6.0

**.NET runtime version**: 6

**Operating system version**: macOS Monetery : 12.6.3

**Description of the problem including expected versus actual behavior**:

After a `CreateDataStreamAsync` and the process has finished, I re-spin up the process and it executes `GetDataStreamAsync` which then throws this exception 

 > The JSON value could not be converted to Elastic.Clients.Elasticsearch.HealthStatus. Path: $.data_streams[0].status | LineNumber: 18 | BytePositionInLine: 24.

of type: `UnexpectedTransportException`

**Steps to reproduce**:

```fsharp

module EsDataStream =
    let dataStreamExists (getClient: unit -> ElasticsearchClient) (logIndex: string) (cancellationToken: CancellationToken) = task {
        let client = getClient ()
        let dsRequest = GetDataStreamRequest(logIndex)
        let! exists = client.Indices.GetDataStreamAsync(dsRequest, cancellationToken)
        
        return if not exists.IsValidResponse || exists.DataStreams.Count <> 0 then false
                   else exists.DataStreams.Count = 1 // = is equiv to ==
    }
    
    let dataStreamCreate (getClient: unit -> ElasticsearchClient) (logIndex: string) (cancellationToken: CancellationToken) = task {
        let client = getClient ()
        let request = CreateDataStreamRequest(logIndex)
        let! response = client.Indices.CreateDataStreamAsync(request, cancellationToken)
        return response.IsValidResponse && response.Acknowledged
    }

```

These are used like so:

```fsharp

let! result =
    EsDataStream.dataStreamExists getClient logIndex cancellationToken
    |> Task.bind (fun result ->
        if not result then EsDataStream.dataStreamCreate getClient logIndex cancellationToken
        else Task.FromResult(true))
    
return result

```

All that function basically does, is if the result from `dataStreamExists` is `false`, then it will fire off `dataStreamCreate`.

The exception gets thrown from the `GetDataStreamAsync`

> Elastic.Transport.UnexpectedTransportException: The JSON value could not be converted to Elastic.Clients.Elasticsearch.HealthStatus. Path: $.data_streams[0].status | LineNumber: 18 | BytePositionInLine: 24.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to Elastic.Clients.Elasticsearch.HealthStatus. Path: $.data_streams[0].status | LineNumber: 18 | BytePositionInLine: 24.
   at Elastic.Clients.Elasticsearch.ThrowHelper.ThrowJsonException(String message) in /_/src/Elastic.Clients.Elasticsearch/Core/Exceptions/ThrowHelper.cs:line 14
   at Elastic.Clients.Elasticsearch.HealthStatusConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /_/src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.NoNamespace.g.cs:line 480
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Elastic.Transport.DefaultResponseBuilder`1.SetBodyAsync[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType, CancellationToken cancellationToken)
   at Elastic.Transport.DefaultResponseBuilder`1.ToResponseAsync[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, Dictionary`2 headers, Stream responseStream, String mimeType, Int64 contentLength, IReadOnlyDictionary`2 threadPoolStats, IReadOnlyDictionary`2 tcpStats, CancellationToken cancellationToken)
   at Elastic.Transport.HttpTransportClient.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elastic.Transport.DefaultRequestPipeline`1.CallProductEndpointAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elastic.Transport.DefaultHttpTransport`1.RequestAsync[TResponse](HttpMethod method, String path, PostData data, RequestParameters requestParameters, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Elastic.Transport.DefaultHttpTransport`1.RequestAsync[TResponse](HttpMethod method, String path, PostData data, RequestParameters requestParameters, CancellationToken cancellationToken)
   at Elastic.Clients.Elasticsearch.ElasticsearchClient.<>c__DisplayClass32_0`3.<<DoRequestAsync>g__SendRequest|0>d.MoveNext() in /_/src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs:line 374
--- End of stack trace from previous location ---
   at EsLogging.EsDataStream.dataStreamExists@36.MoveNext()

**Expected behavior**

What should happen is the response gets serialised properly

**Comment by no1melman** [comment]
The output from the DevTools is:

Executing: `GET _data_stream/logs-dev?pretty=true&error_trace=true`

```json
{
  "data_streams": [
    {
      "name": "logs-dev",
      "timestamp_field": {
        "name": "@timestamp"
      },
      "indices": [
        {
          "index_name": ".ds-logs-crypto-dev-2023.02.16-000001",
          "index_uuid": "xyWXN5T1Rm6_sOCayv7GDA"
        }
      ],
      "generation": 1,
      "_meta": {
        "description": "default logs template installed by x-pack",
        "managed": true
      },
      "status": "GREEN",
      "template": "logs",
      "ilm_policy": "logs",
      "hidden": false,
      "system": false,
      "allow_custom_routing": false,
      "replicated": false
    }
  ]
}
```

**Comment by no1melman** [comment]
The auto gen'd code is:

```csharp
[JsonConverter(typeof(HealthStatusConverter))]
public enum HealthStatus
{
	[EnumMember(Value = "yellow")]
	Yellow,
	[EnumMember(Value = "red")]
	Red,
	[EnumMember(Value = "green")]
	Green
}

internal sealed class HealthStatusConverter : JsonConverter<HealthStatus>
{
	public override HealthStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
	{
		var enumString = reader.GetString();
		switch (enumString)
		{
			case "yellow":
				return HealthStatus.Yellow;
			case "red":
				return HealthStatus.Red;
			case "green":
				return HealthStatus.Green;
		}

		ThrowHelper.ThrowJsonException();
		return default;
	}

	public override void Write(Utf8JsonWriter writer, HealthStatus value, JsonSerializerOptions options)
	{
		switch (value)
		{
			case HealthStatus.Yellow:
				writer.WriteStringValue("yellow");
				return;
			case HealthStatus.Red:
				writer.WriteStringValue("red");
				return;
			case HealthStatus.Green:
				writer.WriteStringValue("green");
				return;
		}

		writer.WriteNullValue();
	}
}
```

**Comment by no1melman** [comment]
The casing shouldn't be a problem... but the code doesn't seem to support `String.Equals(...,..., StringComparison.OrdinalIgnoreCase)`... maybe by design? but then, this probably caused the issue

**Comment by stevejgordon** [comment]
Thanks for raising this, @no1melman, and for the comprehensive analysis. I'll discuss this with the team as this is not something we capture in the specification, which assumes that all uses of `HealthStatus` will return the lowercase value. We'll need to identify a way to address this for code generation.

**Comment by no1melman** [comment]
Also, @stevejgordon , I set `EnableDebugMode()` which I assumed would write out the response serialised to string? Or do I have that confused

**Comment by stevejgordon** [comment]
When enabled, the request/response should appear in the `DebugInformation` property of the response.

**Comment by stevejgordon** [comment]
We do handle this inconsistent casing for `HealthStatus` in the spec, but the .NET generator doesn't apply the aliases. We can hopefully solve this by updating the converter code gen for enums to include the aliases when available. We'll aim to get this fixed in the next release.

**Comment by no1melman** [comment]
> When enabled, the request/response should appear in the `DebugInformation` property of the response.

Yeah this doesn't do this for some reason - let me have a more of an investigation - this is obviously really useful for debugging this kind of thing, rather than going round the houses

**Comment by no1melman** [comment]
Ahh - maybe because of this JSON format exception - maybe you don't back track, and reserialise the stream as a string for the exception.

psuedo

```
try {
   T model = JsonSerializer.Deserialize(stream)
catch JsonEx {
   DebugInformation.Add(stream.ToString()) // get the raw response out.
}
```

**Comment by stevejgordon** [comment]
@no1melman, I see what you mean. Yes, if an exception is thrown this low down, we don't collect and attach the response body anywhere. That's something we can look at in the future if it's practical.

**Comment by no1melman** [comment]
It becomes quite the chore to debug if the JSON fails and we can't see what the original string response was to work out where in could have possibly failed

**Comment by stevejgordon** [comment]
I agree. In this case, this is an exception in deserialising our type, so it shouldn't be up to you to debug it. For source-related exceptions, this would be far more valid for debugging. I've captured this on our roadmap.
