### ISSUE TITLE
System.Text.Json.JsonException: 'Unable to parse typed-key from aggregation name 'unique_thread_id''

### ISSUE THREAD

**Issue by knopa** [elastic/elasticsearch-net#7605]
**Elastic.Clients.Elasticsearch version**:
8.0.10

**Elasticsearch version**:
8.7

**.NET runtime version**:
.net core 7

**Operating system version**:
Windows 11

**Description of the problem including expected versus actual behavior**:
When you are trying get agregation with paged results via **Client.Transport.RequestAsync<SearchResponse<object>>**
with next query 
```
{
  "size": 0,
  "_source": false,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "date": {
              "lte": "2023-04-09T17:00:46.8904423"
            }
          }
        }
      ]
    }
  },
  "fields": [
    {
      "field": "threadId"
    }
  ],
  "sort": [
    {
      "date": {
        "order": "desc"
      }
    }
  ],
  "aggs": {
    "unique_thread_id": {
      "terms": {
        "field": "threadId"
      },
      "aggs": {
        "terms_sort": {
          "bucket_sort": {
            "from": 0,
            "size": 10
          }
        }
      }
    }
  }
}
```

It failed on deserialize with next error 
 ```
at Elastic.Clients.Elasticsearch.Aggregations.AggregateDictionaryConverter.ReadAggregate(Utf8JsonReader& reader, JsonSerializerOptions options, Dictionary`2 dictionary, String name) in /_/src/Elastic.Clients.Elasticsearch/Types/Aggregations/AggregateDictionaryConverter.cs:line 42
   at Elastic.Clients.Elasticsearch.Aggregations.AggregateDictionaryConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /_/src/Elastic.Clients.Elasticsearch/Types/Aggregations/AggregateDictionaryConverter.cs:line 31
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
```
**Expected behavior**
Able to get result in .net

**Comment by knopa** [comment]
Figure out 

should be **terms#unique_thread_id** aggs name, but seems not possible to use native responses with raw queries if it's not possible to get with high level client.

**Comment by stevejgordon** [comment]
@knopa Yes, the serializer requires that `typed_keys` be set to true on the request in order to identify the aggregate type. When using the transport directly, you can do this by including the `SearchRequestParameters`.

```c#
var response = await client.Transport.RequestAsync<SearchResponse<Person>>(
	Elastic.Transport.HttpMethod.POST,
	"my-index/_search",
	PostData.Bytes(searchRequestBytes),
	requestParameters: new SearchRequestParameters { TypedKeys = true }
	);
```

**Comment by knopa** [comment]
@stevejgordon Works like a charm, thanks 
defenetly current documentation miss at least low level client usage.
