### ISSUE TITLE
Potential memory leak after running for several days

### ISSUE THREAD

**Issue by jiatann** [elastic/elasticsearch-net#7751]
**Elastic.Clients.Elasticsearch version**: 8.0.5

**Elasticsearch version**: 8.8.0

**.NET runtime version**: 6.0

**Operating system version**: Ubuntu 22.04

**Description of the problem including expected versus actual behavior**:
We have a singleton `ElasticsearchClient` object in a Kafka consumer job for sending docs to our Elastic cloud cluster. The number of docs sent by each job is pretty high (~100k - 200k per day). `IndexAsync` is the only API we use.

We notice the job is running into index failures after running for several days in production. The error stack trace is 
```
Type: System.OutOfMemoryException
Source: System.Collections.Generic.List`1, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
Message: Exception of type 'System.OutOfMemoryException' was thrown.
Trace:    at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.AddWithResize(T item)
   at System.Diagnostics.SynchronizedList`1.Add(T item)
   at System.Diagnostics.ActivitySource..ctor(String name, String version)
   at Elastic.Transport.DefaultRequestPipeline`1..ctor(TConfiguration configurationValues, DateTimeProvider dateTimeProvider, MemoryStreamFactory memoryStreamFactory, RequestParameters requestParameters)
   at Elastic.Transport.DefaultRequestPipelineFactory`1.Create(TConfiguration configurationValues, DateTimeProvider dateTimeProvider, MemoryStreamFactory memoryStreamFactory, RequestParameters requestParameters)
   at Elastic.Transport.DefaultHttpTransport`1.RequestAsync[TResponse](HttpMethod method, String path, PostData data, RequestParameters requestParameters, CancellationToken cancellationToken)
   at Roblox.EaLogForwarder.Service.Handlers.EALogHandler.ProcessMessageAsync(ConsumeResult`2 msg) in /all/services/ea-log-forwarder/src/Handlers/EaLogHandler.cs:line 102
Location: 
Method: Void set_Capacity(Int32) (0, 0)
```
I suspect there is some memory leak on the client side. Note that the overall memory usage of the .NET app in the container is still very slow (~15%).

**Steps to reproduce**:
 1. run our Kafka consumer job in production for several days
 2. some index operations start to fail with OOM errors
 3.

**Expected behavior**
No OOM errors to occur.

**Provide `ConnectionSettings` (if relevant)**: we're using the default settings, i.e., `new ElasticsearchClient(elasticCloudId, new ApiKey(elasticApiKey))`

**Provide `DebugInformation` (if relevant)**:

**Comment by jiatann** [comment]
Looking at the stack, is it possible that `ActivitySource` objects aren't disposed after use?

**Comment by jiatann** [comment]
Since `ActivitySource` is a static field in `DefaultRequestPipeline`, it's possible that this class is instantiated with different type parameters, because static vars aren't shared between different types: https://stackoverflow.com/questions/14748569/is-a-static-member-variable-common-for-all-c-sharp-generic-instantiations#:~:text=A%20static%20variable%20in%20a,any%20type%20parameters%20or%20not.
