### ISSUE TITLE
UnexpectedElasticsearchClientException while logging with Nlog.Targets.ElasticSearch (reopen of #5702)

### ISSUE THREAD

**Issue by dmitryzarubin** [elastic/elasticsearch-net#7954]
**NEST/Elasticsearch.Net version**: 7.17.5

**Elasticsearch version**: doesn't matter

**.NET runtime version**:  7.0.8

**Operating system version**: Windows 11

**Stack trace:**
```
Exception: Elasticsearch.Net.UnexpectedElasticsearchClientException: Failed to serialize anonymous type: System.RuntimeType.
The type defines the following properties:
'IsCollectible' of type System.Boolean
'DeclaringMethod' of type System.Reflection.MethodBase
'FullName' of type System.String
.....
'IsSerializable' of type System.Boolean
'IsVisible' of type System.Boolean
'CustomAttributes' of type System.Collections.Generic.IEnumerable`1[System.Reflection.CustomAttributeData]
 ---> Elasticsearch.Net.Utf8Json.Resolvers.AnonymousTypeSerializationException: Failed to serialize anonymous type: System.RuntimeType.
The type defines the following properties:
'IsCollectible' of type System.Boolean
'DeclaringMethod' of type System.Reflection.MethodBase
'FullName' of type System.String
'AssemblyQualifiedName' of type System.String
'Namespace' of type System.String
.......
'TypeInitializer' of type System.Reflection.ConstructorInfo
'IsSerializable' of type System.Boolean
'IsVisible' of type System.Boolean
'CustomAttributes' of type System.Collections.Generic.IEnumerable`1[System.Reflection.CustomAttributeData]
 ---> System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
   at System.RuntimeType.get_DeclaringMethod()
   at Serialize(Byte[][], Object[], JsonWriter&, RuntimeType, IJsonFormatterResolver)
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Serialize(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Serialize(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.Formatters.DynamicObjectTypeFallbackFormatter.Serialize(JsonWriter& writer, Object value, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.Formatters.DictionaryFormatterBase`5.Serialize(JsonWriter& writer, TDictionary value, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.Formatters.DynamicObjectTypeFallbackFormatter.Serialize(JsonWriter& writer, Object value, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.SerializeUnsafe[T](T value, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Serialize[T](Stream stream, T value, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Serialize[T](T data, Stream stream, SerializationFormatting formatting)
   at Elasticsearch.Net.PostData`1.Write(Stream writableStream, IConnectionConfigurationValues settings)
   at Elasticsearch.Net.HttpConnection.SetContent(HttpRequestMessage message, RequestData requestData)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[TResponse](PostData body, BulkRequestParameters requestParameters)
   at Common.Log.ElasticSearchTarget.SendBatch(ICollection`1 logEvents)
```

**NLog configuration:**
```
"Nlog": {
"throwConfigExceptions": true,
"variables": {
  "serverAddress": "https://some-elastic-server:9260",
  "indexName": "some-index",
  "serviceName": "SomeService",
  "login": "write",
  "password": "PWD"
},
"targets": {
  "async": true,
  "elastic": {
	"type": "BufferingWrapper",
	"flushTimeout": 5000,
	"bufferSize": 100,
	"target": {
	  "type": "ElasticSearch",
	  "layout": "${message}",
	  "includeAllProperties": true,
	  "uri": "${serverAddress}",
	  "disablePing": true,
	  "index": "${indexName}",
	  "serviceName": "${serviceName}",
	  "requireAuth": true,
	  "username": "${login}",
	  "password": "${password}",
	  "requestTimeout": 1000
	}
  }
},
"rules": [
  {
	"logger": "*",
	"minLevel": "Debug",
	"writeTo": "elastic"
  }
]
}
```

The cause of the exception is that someone is using a complex object in structural logging and that object might throw an exception from one of its properties.

Example from ASP.Net MVC (MvcCoreLoggerExtensions class):
```
[LoggerMessage(45, LogLevel.Debug, "Done attempting to bind parameter '{ParameterName}' of type '{ModelType}'.", EventName = "DoneAttemptingToBindParameterModel", SkipEnabledCheck = true)]
private static partial void DoneAttemptingToBindParameterModel(ILogger logger, string? parameterName, Type modelType);

```

As you can see, the second parameter of structured logging is "modelType" of the Type class. And when Nlog + Elasticsearch.Net tries to send the message and its properties to Elastic, it tries to serialize all properties of the "modelType" parameter, using the reflection (I guess). But the Type class can throw exceptions from some of its properties (for example, GenericParameterAttributes property throws InvalidOperationException if it's not a generic class). So Elasticsearch.Net.Utf8Json throws an UnexpectedElasticsearchClientException and the entire batch of log messages is lost.

**Comment by snakefoot** [comment]
Notice the NLog ElasticSearch Target has the option [maxRecursionLimit](https://github.com/markmcdowell/NLog.Targets.ElasticSearch/wiki) as work-around. Because the default Elastic-Json-Serializer explodes in your face when meeting rogue objects.

**Comment by flobernd** [comment]
Hi, thanks for doing the investigation work, but that does not seem like something that should be fixed on our side 🙂
