### ISSUE TITLE
Mystic MissingMethodException

### ISSUE THREAD

**Issue by tkirill** [elastic/elasticsearch-net#8014]
**NEST/Elasticsearch.Net version**: 7.9

**Elasticsearch version**: 7.16.3

**.NET runtime version**: net6, net48

**Operating system version**: Windows 10.0.17763

**Description of the problem including expected versus actual behavior**:

It is a very strange problem. I suddenly started to get various `MissingMethodException` from elasticsearch-net. It looks very similar to #6144. As in #6144 exceptions came out of nowhere and aren't consistent across replicas of my application. I didn't managed to reproduce the problem. I understand that it is hard to investigate without steps to reproduce. But I thought that it is worth to try to provide a detailed information about this mystic problem to you. Maybe you will have some ideas from your experience that will guide my further investigation.

I have two kinds of the error. 1️⃣ `System.MissingMethodException: Method not found: 'Nest.ceAggregation Nest.IAggregationContainer.get_GeoDistance()'` and 2️⃣ ``System.MissingMethodException: Method not found: 'Void Elasticsearch.Net.Utf8Json.IJsonFormatter`1.IGeoDistanceAggregation(Elasticsearch.Net.Utf8Json.JsonWriter ByRef, !0, Elasticsearch.Net.Utf8Json.IJsonFormatterResolver)'``

Stacktrace for 1️⃣:

```
Elasticsearch.Net.UnexpectedElasticsearchClientException: Method not found: 'Nest.ceAggregation Nest.IAggregationContainer.get_GeoDistance()'.
    at Elasticsearch.Net.Transport`1+<RequestAsync>d__15`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:153:7)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
    at Nest.ElasticClient+<SearchAsync>d__254`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Nest\ElasticClient.NoNamespace.cs:1003:31)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
    at Nest.ElasticClient+<SearchAsync>d__252`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Nest\ElasticClient.NoNamespace.cs:989:31)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
    at
   <... Application code ...>
  Caused by: System.MissingMethodException: Method not found: 'Nest.ceAggregation Nest.IAggregationContainer.get_GeoDistance()'.
      at Elasticsearch.Net.Nest_IAggregationContainerFormatter3.Serialize()
      at Nest.VerbatimDictionaryKeysBaseFormatter`3.Serialize(C:\Users\russc\source\elasticsearch-net\src\Nest\Aggregations\VerbatimDictionaryKeysFormatter.cs:30:4)
      at Elasticsearch.Net.Nest_ISearchRequestFormatter1.Serialize()
      at Elasticsearch.Net.Utf8Json.JsonSerializer+<SerializeAsync>d__11`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Utf8Json\JsonSerializer.cs:145:9)
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
      at Elasticsearch.Net.SerializableData`1+<WriteAsync>d__4.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Transport\SerializableData.cs:47:3)
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
      at Elasticsearch.Net.HttpConnection+<SetContentAsync>d__24.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:374:3)
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
      at Elasticsearch.Net.HttpConnection+<RequestAsync>d__14`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:165:3)
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
      at Elasticsearch.Net.RequestPipeline+<CallElasticsearchAsync>d__57`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:200:3)
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
      at Elasticsearch.Net.Transport`1+<RequestAsync>d__15`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs)
```

Stacktrace for 2️⃣:

```
Elasticsearch.Net.UnexpectedElasticsearchClientException: Method not found: 'Void Elasticsearch.Net.Utf8Json.IJsonFormatter`1.IGeoDistanceAggregation(Elasticsearch.Net.Utf8Json.JsonWriter ByRef, !0, Elasticsearch.Net.Utf8Json.IJsonFormatterResolver)'.
    at Elasticsearch.Net.Transport`1+<RequestAsync>d__15`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:153:7)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
    at Nest.ElasticClient+<SearchAsync>d__254`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Nest\ElasticClient.NoNamespace.cs:1003:31)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
    at Nest.ElasticClient+<SearchAsync>d__252`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Nest\ElasticClient.NoNamespace.cs:989:31)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
    at
    <... Application code ...>
  Caused by: System.MissingMethodException: Method not found: 'Void Elasticsearch.Net.Utf8Json.IJsonFormatter`1.IGeoDistanceAggregation(Elasticsearch.Net.Utf8Json.JsonWriter ByRef, !0, Elasticsearch.Net.Utf8Json.IJsonFormatterResolver)'.
      at Elasticsearch.Net.Nest_IQueryContainerFormatter2.Serialize()
      at Elasticsearch.Net.Nest_ISearchRequestFormatter1.Serialize()
      at Elasticsearch.Net.Utf8Json.JsonSerializer+<SerializeAsync>d__11`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Utf8Json\JsonSerializer.cs:145:9)
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
      at Elasticsearch.Net.SerializableData`1+<WriteAsync>d__4.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Transport\SerializableData.cs:47:3)
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
      at Elasticsearch.Net.HttpConnection+<SetContentAsync>d__24.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:374:3)
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
      at Elasticsearch.Net.HttpConnection+<RequestAsync>d__14`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:165:3)
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
      at Elasticsearch.Net.RequestPipeline+<CallElasticsearchAsync>d__57`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:200:3)
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification()
      at Elasticsearch.Net.Transport`1+<RequestAsync>d__15`1.MoveNext(C:\Users\russc\source\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs)
```

Important observations and facts about problem appearance:

1) I didn't update the client for a few years. It worked perfect (thank you for such great library! 🙂).
2) The problem appears relatively rarely. Sometimes after an another release of my application 1-2 replicas out of many suddenly start to throw MissingMethodException after restart.
3) If replica start to throw MissingMethodException it won't stop. Only restart helps.

Important obsevations and facts that I managed to gather myself:

1) I tried to reproduce the error repeating the request in single thread and in 10 threads for five minutes. The error was not reproduced.
1) I think I found the code which emits the code that throws the exceptions 😵 `get_` call from 1️⃣ is emitted [here](https://github.com/elastic/elasticsearch-net/blob/7.9/src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicObjectResolver.cs#L802) ([EmitLoadValue](https://github.com/elastic/elasticsearch-net/blob/7.9/src/Elasticsearch.Net/Utf8Json/Internal/Emit/MetaMember.cs#L134)). And call of a method with such arguments from 2️⃣ is emitted [here](https://github.com/elastic/elasticsearch-net/blob/7.9/src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicObjectResolver.cs#L804) ([EmitInfo.Serialize](https://github.com/elastic/elasticsearch-net/blob/7.9/src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicObjectResolver.cs#L1241)).
2) Both errors are really strange. I can't understand from the code why it happens. 1️⃣ -- IAggregationContainer [indeed has getter for a GeoDistance](https://github.com/elastic/elasticsearch-net/blob/7.9/src/Nest/Aggregations/AggregationContainer.cs#L160). Why runtime suddenly can't find it? 2️⃣ -- guessing from exception we try to call method `IGeoDistanceAggregation` on `IJsonFormatter<T>` which indeed [doesn't exist](https://github.com/elastic/elasticsearch-net/blob/7.9/src/Elasticsearch.Net/Utf8Json/IJsonFormatter.cs#L34). And `IGeoDistanceAggregation` is an interface and definitely not a method! :) And we emit [a call to IJsonFormatter<T>.Serialize](https://github.com/elastic/elasticsearch-net/blob/7.9/src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicObjectResolver.cs#L1241). So why do we see in exception a call to `IJsonFormatter<T>.IGeoDistanceAggregation` with the same parameters as `IJsonFormatter<T>.Serialize` has?
3) The code looks deterministic. So it should either always work or always fail. I can't understand what introduces instability. Maybe a race condition during initialisation of the client? But the problem was not reproduced in multithreaded test. Maybe it is different version of the Elasticsearch.net.dll? But the same set of binaries works good after the restart on the same host. Maybe the client isn't compatible with Elasticsearch version? But the error appears during request serialisation.

**Steps to reproduce**: ➖

**Comment by asal-hesehus** [comment]
I have also seen this issue. It happen rarely but the application needs to be restarted.

**Comment by niemyjski** [comment]
Why was this closed? We just run into this.

**Comment by niemyjski** [comment]
```
Elasticsearch.Net.UnexpectedElasticsearchClientException: Method not found: 'Void Elasticsearch.Net.Utf8Json.IJsonFormatter`1.�(Elasticsearch.Net.Utf8Json.JsonWriter ByRef, !0, Elasticsearch.Net.Utf8Json.IJsonFormatterResolver)'.
 ---> MissingMethodException: Method not found: 'Void Elasticsearch.Net.Utf8Json.IJsonFormatter`1.�(Elasticsearch.Net.Utf8Json.JsonWriter ByRef, !0, Elasticsearch.Net.Utf8Json.IJsonFormatterResolver)'.
at Elasticsearch.Net.Nest_IAggregationContainerFormatter3.Serialize(Elasticsearch.Net.Utf8Json.JsonWriter&, Nest.IAggregationContainer, Elasticsearch.Net.Utf8Json.IJsonFormatterResolver)
at Nest.VerbatimDictionaryKeysBaseFormatter`3.Serialize(Elasticsearch.Net.Utf8Json.JsonWriter& writer, Nest.TDictionary value, Elasticsearch.Net.Utf8Json.IJsonFormatterResolver formatterResolver)
at Elasticsearch.Net.Nest_ISearchRequestFormatter1.Serialize(Elasticsearch.Net.Utf8Json.JsonWriter&, Nest.ISearchRequest, Elasticsearch.Net.Utf8Json.IJsonFormatterResolver)
at Elasticsearch.Net.Utf8Json.JsonSerializer.<SerializeAsync>d__11`1.MoveNext()
at Elasticsearch.Net.SerializableData`1.<WriteAsync>d__4.MoveNext() at offset 200
at Elasticsearch.Net.HttpConnection.<SetContentAsync>d__25.MoveNext() at offset 429
at Elasticsearch.Net.HttpConnection.<RequestAsync>d__15`1.MoveNext() at offset 291
at Elasticsearch.Net.RequestPipeline.<CallElasticsearchAsync>d__67`1.MoveNext()
at Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext()
--- End of inner exception stack trace ---
at Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext() at offset 1213
at Nest.ElasticClient.<SearchAsync>d__266`1.MoveNext()
```

**Comment by flobernd** [comment]
@niemyjski NEST will be end of life at the end of this year and currently has very low priority in general. There is that much higher priority stuff on the roadmap (related to the new v8 client) so that it is completely unrealistic for me to work on this issue before NEST will be completely abandoned anyways.

Besides that, it seems very like that the issue is introduced by some kind of dependency or changes in the framework, given the fact that it randomly appears for users after years without them changing anything.

**Comment by niemyjski** [comment]
This issue also seems to be a duplicate https://github.com/elastic/elasticsearch-net/issues/6144

@flobernd But it's not end of life yet. It would be awesome if each new client version didn't break the world and was not all internalized and hard to extend we would already be using the new client. Every new major has caused us months of work to upgrade https://github.com/FoundatioFx/Foundatio.Parsers/tree/master/src/Foundatio.Parsers.ElasticQueries . cc @Mpdreamz @stevejgordon 

Do you have any idea where `Nest_IQueryContainerFormatter3` would be coming from, it seems like a generated type perhaps by the runtime. I am only seeing this in one of our five environments, and not under the debugger which makes me feel like this could be some kind of compiler / runtime optimization?? We are running .NET 8.

**Comment by jrlost** [comment]
For me, this looks to be caused by the UTF8Json-based serializer that lazily caches type metadata. In high load scenarios, after the application boots, if you get multiple concurrent requests that trigger `Nest_IAggregationContainerFormatter` resolution, you run into a race condition where this singleton can get corrupted.  Shifting the resolution forward before the application finishes booting may resolve this.

Adding in something like
`_ = app.ApplicationServices.GetRequiredService<IElasticClient>().Ping()` after your DI container has been built but before the application boots (this example would be in your applications startup `Configure` method, but you could also place it into a hostedService or something similar). Obviously this example is super simple, you'd probably want to refactor it to include a try/catch and properly handle your failure states.


EDIT: I know the correct long term solution is to move towards the newer Elastic client libraries, but that's not always feasible for legacy applications. This approach above may get you limping forward with an older NEST install.
