### ISSUE TITLE
NEST does not work with .Net 8

### ISSUE THREAD

**Issue by CasperWSchmidt** [elastic/elasticsearch-net#8021]
**NEST/Elasticsearch.Net version**:
7.17.5

**Elasticsearch version**:
7.17.3

**.NET runtime version**:
8.0

**Operating system version**:
macOS Sonoma 14.2.1

**Description of the problem including expected versus actual behavior**:
Upgrading from .Net 7 to .Net 8 we have 304 Elasticsearch-related unit tests failing. They all fail with `Elasticsearch.Net.UnexpectedElasticsearchClientException: Exception has been thrown by the target of an invocation.`

I believe it all boils down to the following:
```
System.TypeInitializationException
The type initializer for 'FormatterCache`1' threw an exception.
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicGenericResolver.GetFormatter[T]()
   at Nest.NestFormatterResolver.InnerResolver.<GetFormatter>b__5_0[T](Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Nest.NestFormatterResolver.InnerResolver.GetFormatter[T]()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

System.ArgumentException
GenericArguments[1], 'System.Linq.EmptyPartition`1[System.Guid]', on 'Elasticsearch.Net.Utf8Json.Formatters.GenericCollectionFormatter`2[TElement,TCollection]' violates the constraint of type 'TCollection'.
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicGenericResolverGetFormatterHelper.CreateInstance(Type genericType, Type[] genericTypeArguments, Object[] arguments)
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicGenericResolverGetFormatterHelper.GetFormatter(Type t)
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicGenericResolver.FormatterCache`1..cctor()

System.TypeLoadException
GenericArguments[1], 'System.Linq.EmptyPartition`1[System.Guid]', on 'Elasticsearch.Net.Utf8Json.Formatters.GenericCollectionFormatter`2[TElement,TCollection]' violates the constraint of type parameter 'TCollection'.
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
```

**Steps to reproduce**:
 1. Upgrade to .Net 8
 2. Try running some code that interacts with Elasticsearch through NEST

**Expected behavior**
No unit-tests failing

**Comment by CasperWSchmidt** [comment]
@flobernd We're also looking to migrate to the new client library. I just wanted to log it here if anyone else experience the same issue. As stated in another issue upgrading from NEST to the new client is not easy though...
