### ISSUE TITLE
Cannot run knn query using elasticClient.RequestResponseSerializer

### ISSUE THREAD

**Issue by giannik** [elastic/elasticsearch-net#8241]
Im trying to run a knn query in version 8.14.2 of dotnet client by passing  json string query into elastic client RequestResponseSerializer.
Considering that the feature is included based on comment : https://github.com/elastic/elasticsearch-net/issues/8012#issuecomment-2063358493
Below is the json string use for constructing the typed query.

When I run it in elastic search dasboard in dev console it works .
But when i pass the query as a string to the  RequestResponseSerializer : 
```
           using var stream = new MemoryStream(Encoding.UTF8.GetBytes(query));
         var deserializedSearchRequest = _elasticClient.RequestResponseSerializer.Deserialize<SearchRequest>(stream);
```
i get the following error during deserialization : 

```
HEAD https://0c855f771a5f47dd8541e202bb8c6640.westeurope.azure.elastic-cloud.com/default_indextestnew
Status: 200


fail: OrchardCore.Search.Elasticsearch.Core.Services.ElasticQueryService[0]
      Error while querying elastic with exception: The JSON value could not be converted to Elastic.Clients.Elasticsearch.QueryDsl.FieldAndFormat. Path: $[0] | LineNumber: 0 | BytePositionInLine: 16.
      System.Text.Json.JsonException: The JSON value could not be converted to Elastic.Clients.Elasticsearch.QueryDsl.FieldAndFormat. Path: $[0] | LineNumber: 0 | BytePositionInLine: 16.
         at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo`1 jsonTypeInfo)
         at Elastic.Clients.Elasticsearch.SearchRequestConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /_/src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchRequest.g.cs:line 229
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Stream utf8Json)
         at Elastic.Clients.Elasticsearch.Serialization.SystemTextJsonSerializer.Deserialize[T](Stream stream) in /_/src/Elastic.Clients.Elasticsearch.Shared/Serialization/SystemTextJsonSerializer.cs:line 71
         at OrchardCore.Search.Elasticsearch.Core.Services.ElasticQueryService.SearchAsync(String indexName, String query) in C:\IntelliDev20\src\OrchardCore\OrchardCore.Search.Elasticsearch.Core\Services\ElasticQueryService.cs:line 45


```

Im using openai embeddings to generate and store the embeddings in elastic search.
This uses a dense vector of 1536 points.

here is th entire json query string (it works when i run it in the dev console but not from the typed client):

```
{
    "fields": ["ContentItemId", "ContentItem_FullText"],
    "_source": false,
    "knn": {
        "query_vector": [
      0.0185484141,
      -0.000538613356,
       -------------------omitting points for brevitiy--------
      -0.0159369558,
      -0.0194094907
    ],
        "field": "ContentItem_Vector.vector",
        "k": 2,
        "num_candidates": 2
    }
}


```

**Comment by flobernd** [comment]
Hi @giannik,

I think this might be the same case that I tried to explain to you a few days ago in this [comment](https://github.com/elastic/elasticsearch-net/issues/8240#issuecomment-2167404686).

> Manual (De-)serialization of the data structures is an unsupported use-case.
> [...] certain types only implement either serialization OR deserialization

For the majority of cases, `Request` types only implement `serialization` (because they are never deserialized in the client).

Could you please check, if the same query as well causes an error, if you build it by using e.g. the fluent API? If that's the case I will investigate further, but otherwise this best thing I can recommend to you is:

> Usually we suggest using your own custom CLR types and copy over / assign the values from the Elasticsearch types.

**Comment by giannik** [comment]
i can confirm that using the typed client for knn works : 

```
 var floatList = new List<float> { 0.0185484141f, -0.000538613356f };

                var searchResponse1 = await _elasticClient.SearchAsync<Dictionary<string, object>>(s =>
                                s.Index(_indexPrefix + indexName)

                                .Knn(qd =>
                                {
                                    qd.k(2)
                                        .NumCandidates(100)
                                        .Field("ContentItem_Vector.vector")
                                        .QueryVector(floatList);
                                }));


```




but i was looking for a generic mechanism to just pass the json i write in the dev console to the c# client and execute it . it works for query dsl type queries  but not for knn.


so basically given my current code for the generic mechanism is this : 


```

    using var stream = new MemoryStream(Encoding.UTF8.GetBytes(query));
                var deserializedSearchRequest = _elasticClient.RequestResponseSerializer.Deserialize<SearchRequest>(stream);

                var searchRequest = new SearchRequest(_indexPrefix + indexName)
                {

                   // Knn = deserializedSearchRequest.Knn,
                    Query = deserializedSearchRequest.Query,
                    From = deserializedSearchRequest.From,
                    Size = deserializedSearchRequest.Size,
                    Fields = deserializedSearchRequest.Fields,
                    Sort = deserializedSearchRequest.Sort,
                    Source = deserializedSearchRequest.Source,
                };

                var searchResponse = await _elasticClient.SearchAsync<Dictionary<string, object>>(searchRequest);

```


the sugestion is i should skip this part : 

```
  using var stream = new MemoryStream(Encoding.UTF8.GetBytes(query));
                var deserializedSearchRequest = _elasticClient.RequestResponseSerializer.Deserialize<SearchRequest>(stream);
```


and rather deserialize to my own objects and then pass in the values needed the the client : 


```

                var searchRequest = new SearchRequest(_indexPrefix + indexName)
                {

                    Knn = MYdeserializedSearchRequest.Knn,
                    Query = MYdeserializedSearchRequest.Query,
                    From = MYdeserializedSearchRequest.From,
                    Size = MYdeserializedSearchRequest.Size,
                    Fields = MYdeserializedSearchRequest.Fields,
                    Sort = MYdeserializedSearchRequest.Sort,
                    Source = MYdeserializedSearchRequest.Source,
                };

   var searchResponse = await _elasticClient.SearchAsync<Dictionary<string, object>>(searchRequest);
```


Correct ?

**Comment by flobernd** [comment]
Hi @giannik, yes that's essentially what we suggest in these cases 🙂 

I understand that a full round-trippable (de-)serialization would provide a convenient way of executing queries that are stored as JSON, but at the moment there are not plans to support this.

>  i was looking for a generic mechanism to just pass the json i write in the dev console to the c# client and execute it . it works for query dsl type queries but not for knn.

The query-dsl types are round-trippable, because they are as well returned by some APIs, which mans we need both serialization- and deserialization support for them in the client.

Maybe reflection could be used to implement a completely generic way of executing queries for your console app use-case.

**Comment by flobernd** [comment]
Going to close this issue for now, but please feel free to open a new one, if you have additional questions, etc.
