### ISSUE TITLE
Configuration is null in RequestConfigurationDescriptor constructor since 8.16

### ISSUE THREAD

**Issue by LionelVallet** [elastic/elasticsearch-net#8425]
**Elastic.Clients.Elasticsearch version**: 8.16.2

**Elasticsearch version**: 8.16.1

**.NET runtime version**: 8.0.11

**Operating system version**: Debian 12

**Description of the problem including expected versus actual behavior**:

Since 8.16, request configuration does not work anymore

``` csharp
var response = await elasticsearchClient.SearchAsync<BaseDocument>(r =>
{
    r.RequestConfiguration(rc => rc.DisableDirectStreaming());
    r.Query(q => q)
    // [...]
});
```

``` log
System.ArgumentNullException: Value cannot be null. (Parameter 'config')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at Elastic.Transport.RequestConfigurationDescriptor..ctor(IRequestConfiguration config)
   at Elastic.Clients.Elasticsearch.Requests.RequestDescriptor`2.RequestConfiguration(Func`2 configurationSelector) in /_/src/Elastic.Clients.Elasticsearch/_Shared/Core/Request/RequestDescriptor.cs:line 63
   at Reporting.Services.ReportsService.<>c__DisplayClass14_2.<GetResultAsync>b__9(SearchRequestDescriptor`1 r) in C:\Repos\src\Services\Reporting\Reporting\Services\ReportsService.cs:line 87
   at Elastic.Clients.Elasticsearch.ElasticsearchClient.SearchAsync[TDocument](Action`1 configureRequest, CancellationToken cancellationToken) in /_/src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs:line 9410
```

**Steps to reproduce**:
 1. try to configure request as example above
 2. observing, powerless, the exception

**Expected behavior**
be able to configure request in elastic client methods

**Comment by flobernd** [comment]
Hi @LionelVallet,

thanks for reporting! Should be fixed in 8.16.3.
